__собираем объявления о продаже недвижимости в одну таблицу__

_Evgeny S. Borisov <parser@mechanoid.su>_

In [1]:
!date

Пн 16 сен 2024 13:39:54 MSK

In [2]:
from os import listdir
import re
import pandas as pd

In [3]:
data_root_folder = 'data/2024'
source = {
         'flat':[data_root_folder+'/raw/flat/cian',data_root_folder+'/raw/flat/avito'],
        'house':[data_root_folder+'/raw/house/cian',data_root_folder+'/raw/house/avito'],
         'land':[data_root_folder+'/raw/land/cian',data_root_folder+'/raw/land/avito'],
    }

---

In [4]:
obj_type = 'flat'
files = [ f'{d}/{f}' for d in source[obj_type] for f in listdir(d) if f[-4:]=='.pkl' ]
display( len(files) )

cols = ['url','place','title','subtitle','price','address','description','ts',]

df_flat = pd.concat([
        pd.read_pickle(f).drop_duplicates(['url'])
        for f in files
    ]).reset_index(drop=True)[cols]

display( len(df_flat) )
display(df_flat.sample(9))

80

74010

,url,place,title,subtitle,price,address,description,ts
39628,https://www.avito.ru/3128132896,sevastopol,"3-к. квартира, 73,2 м², 4/10 эт.",NaN,9700000,"ул. Александра Маринеско, 4А","Трехкомнатная квартира 73.2 м2, на 4/10 этаже ...",2024-08-12 11:14:17.523749
50117,https://www.avito.ru/3943903152,sevastopol,"Апартаменты-студия, 23,2 м², 1/10 эт.",NaN,7350000,"Севастопольская зона ЮБК, 20А",Арт. 69446216 Предлагается к продаже комфортаб...,2024-08-06 11:02:57.284493
1602,https://sevastopol.cian.ru/sale/flat/299736648/,sevastopol,"2-комн. квартира, 74 м², 3/3 этаж",,19800000,"Севастополь, р-н Гагаринский, мкр. Стрелецкая ...",Отличное предложение для дружной семьи или в к...,2024-06-19 12:14:54.696204
19724,https://sevastopol.cian.ru/sale/flat/299737558/,sevastopol,"1-комн. апартаменты, 41,3 м², 8/10 этаж",,9500000,"Севастополь, р-н Гагаринский, улица Парковая, 11","Апартаменты в комплексе Аквамарин 41.3 м2, на ...",2024-09-03 13:42:38.866585
3532,https://sevastopol.cian.ru/sale/flat/302904000/,sevastopol,"1-комн. апартаменты, 30 м², 2/3 этаж",,4850000,"Севастополь, р-н Балаклавский, шоссе Фиолентов...",Продаются шикарные апартаменты с видом на море...,2024-07-16 12:28:31.306616
6182,https://sevastopol.cian.ru/sale/flat/302661895/,sevastopol,"Студия, 30 м², 7/8 этаж",,6200000,"Севастополь, р-н Ленинский, улица Токарева, 18В",Объект 4340. В продаже квартира-студия в самом...,2024-06-14 12:56:14.435965
8426,https://sevastopol.cian.ru/sale/flat/300548152/,sevastopol,"1-комн. квартира, 33 м², 2/5 этаж",,6200000,"Севастополь, р-н Гагаринский, мкр. Стрелецкая ...",Объект 1683. Продается уютная однокомнатная кв...,2024-06-11 10:13:23.305322
58707,https://www.avito.ru/3596024893,sudak,"1-к. квартира, 31 м², 2/6 эт.",NaN,5300000,Гвардейская ул.,"Квартира в центре города, рядом садик, школа, ...",2024-08-26 15:02:47.280197
6157,https://sevastopol.cian.ru/sale/flat/299737489/,sevastopol,"3-комн. квартира, 51 м², 2/3 этаж",,5300000,"Севастополь, р-н Нахимовский, с. Дальнее, 2","Трёхкомнатная квартира 51 м2, на 2/3 этаже дом...",2024-06-14 12:56:14.435965

In [5]:
from lib.cleaner import CleanerFlat

df_flat = CleanerFlat().transform(df_flat)
display( len(df_flat) )
display(df_flat.sample(9))

74010

,url,place,title,subtitle,price,address,description,ts,nrooms,floor,...,area,is_studio,is_apartment,is_part,is_auction,is_openspace,is_roof,is_SNT,priceM,is_last_floor
56810,https://www.avito.ru/3936000899,sevastopol,"1-к. квартира, 29 м², 2/5 эт.",NaN,6800000,"проспект Юрия Гагарина, 6",Продается однокомнатная квартира в Стрелке. Ря...,2024-07-08 13:29:07.581057,1,2,...,29.0,False,False,False,False,False,False,False,6.8000,False
55911,https://www.avito.ru/3721458371,sevastopol,"3-к. квартира, 72 м², 4/5 эт.",NaN,8150000,"улица Хрусталёва, 149","Продаётся тpexкомнатнaя квaртира 72.6 м2, на 4...",2024-07-30 16:15:15.853171,3,4,...,72.0,False,False,False,False,False,False,False,8.1500,False
7086,https://sevastopol.cian.ru/sale/flat/292150635/,sevastopol,"1-комн. квартира, 42 м², 16/16 этаж",,10000000,"Севастополь, р-н Гагаринский, улица Парковая, 12",Супер предложение! Однокомнатная квартира у мо...,2024-06-11 10:13:23.305322,0,6,...,42.0,False,False,False,False,False,False,False,10.0000,False
57289,https://www.avito.ru/3961442809,sevastopol,"1-к. квартира, 43 м², 10/10 эт.",NaN,7400000,"улица Степаняна, 9А",Дом Сдан В Эксплуотацию! Документы получены! К...,2024-07-08 13:29:07.581057,1,0,...,43.0,False,False,False,False,False,False,False,7.4000,False
70317,https://www.avito.ru/3625366118,sevastopol,"1-к. квартира, 47,2 м², 3/9 эт.",NaN,7740800,"ЖК «Доброгород»\n улица Токарева, 8 этап, блок 2","Доступна ипотека! Ипотека с господдержкой, вое...",2024-06-13 11:17:37.489999,1,3,...,47.2,False,False,False,False,False,False,False,7.7408,False
50682,https://www.avito.ru/4187417011,sevastopol,"квартира-студия, 39 м², 9/10 эт.",NaN,7400000,"улица Пожарова, 20/1",Продается уютная однокомнатная квартира. Общая...,2024-08-06 11:02:57.284493,0,9,...,39.0,True,False,False,False,False,False,False,7.4000,False
36940,https://www.avito.ru/3981512228,sevastopol,"квартира-студия, 27,5 м², 3/9 эт.",NaN,4922500,"ЖК «Доброгород»\n улица Токарева, 8 этап, блок 1",Крупнейший в городе Севастополь семейный район...,2024-06-24 12:47:24.649620,0,3,...,27.5,True,False,False,False,False,False,False,4.9225,False
25534,https://krym.cian.ru/sale/flat/300284977/,sudak,"2-комн. квартира, 52,7 м², 1/5 этаж",,10300000,"Республика Крым, Судак, улица Мичурина, 6","К продаже 2х квартира, с ремонтом в центре гор...",2024-06-07 11:43:44.424563,0,1,...,52.7,False,False,False,False,False,False,False,10.3000,False
16403,https://sevastopol.cian.ru/sale/flat/299844664/,sevastopol,"3-комн. квартира, 69,3 м², 5/5 этаж",,7800000,"Севастополь, р-н Ленинский, мкр. Острякова, ул...",Продам трехкомнатную квартиру в самом развитом...,2024-07-08 13:17:33.822433,0,5,...,69.3,False,False,False,False,False,False,False,7.8000,True

---

In [6]:
obj_type = 'land'
files = [ f'{d}/{f}' for d in source[obj_type] for f in listdir(d) if f[-4:]=='.pkl' ]
display( len(files) )

cols = ['url','place','title','subtitle','price','address','description','ts',]

df_land = pd.concat([
        pd.read_pickle(f).drop_duplicates(['url'])
        for f in files
    ]).reset_index(drop=True)[cols]

display( len(df_land) )
display(df_land.sample(9))

100

63718

,url,place,title,subtitle,price,address,description,ts
49714,https://www.avito.ru/3989964132,sudak,"Участок 5,2 сот. (ИЖС)",NaN,9500000,ул. Ашик-Умер,Продается земельный участок всего в 200 метрах...,2024-07-16 12:51:23.262228
29784,https://www.avito.ru/3719360317,sevastopol,"Участок 6,7 сот. (ИЖС)",NaN,15990000,"садоводческое товарищество Луч, 75","Позвоните, рекомендуем не тянуть с просмотром!...",2024-07-16 12:41:33.250588
34035,https://www.avito.ru/1547198272,bahchisaray,Участок 8 сот. (ИЖС),NaN,4000000,"Республика Крым, Бахчисарайский район",". Объект расположен: Республика Крым, Бахчисар...",2024-06-07 12:09:12.165236
30942,https://www.avito.ru/4428435576,bahchisaray,"Участок 12 сот. (СНТ, ДНП)",NaN,2200000,"с. Предущельное, Ущельная ул.","Продам участок. Лкх можно строить, участок на ...",2024-09-09 13:06:18.507053
54318,https://www.avito.ru/4160098790,sevastopol,"Участок 4 сот. (СНТ, ДНП)",NaN,2700000,садоводческое товарищество Троллейбусник-2,"Участок 4 сотки (СТ) в г. Севастополь, Гагарин...",2024-08-20 09:50:33.232766
55555,https://www.avito.ru/3899080592,sudak,"Участок 5,7 сот. (СНТ, ДНП)",NaN,2900000,"с. Миндальное, СНТ Солнечная Долина, Морская ул.",Кадастровый номер 90:23:080114:168. До асфальт...,2024-07-30 16:31:43.840579
31250,https://www.avito.ru/3657586606,bahchisaray,Участок 10 сот. (ИЖС),NaN,900000,"с. Севастьяновка, Партизанская ул.",Продам участок.,2024-06-11 10:49:42.413688
27802,https://www.avito.ru/2325112089,bahchisaray,"Участок 1,8 га (СНТ, ДНП)",NaN,3000000,с. Верхоречье,Участок приватизирован! Продаётся земельный уч...,2024-07-30 16:34:04.489119
20765,https://sevastopol.cian.ru/sale/suburban/29111...,sevastopol,"Участок, 4.6 сот., Садоводство",,2800000,"Севастополь, р-н Балаклавский, Балаклава г., Б...",Предлагается к продаже шикарный видовой земель...,2024-06-10 11:18:48.884876

In [7]:
from lib.cleaner import CleanerLand

df_land = CleanerLand().transform(df_land)

display( len(df_land) )
display(df_land.sample(9))

63718

,url,place,title,subtitle,price,address,description,ts,area,is_IJS,priceM,priceMU,area_size_category
13035,https://sevastopol.cian.ru/sale/suburban/30170...,sevastopol,"участок, 10 сот., ижс",,4000000,"Севастополь, р-н Балаклавский, с. Родниковское...",Продаю 10 соток ИЖС в с. Родниковое в Байдарск...,2024-06-19 12:23:33.870565,10.0,True,4.000000,0.400000,8-12
59421,https://www.avito.ru/3795693821,sevastopol,"участок 10 сот. (снт, днп)",NaN,1500000,67Н-16,"Продаю свои участки от10 до 12 соток, в селе Ш...",2024-06-11 10:32:52.971878,10.0,False,1.500000,0.150000,8-12
38457,https://www.avito.ru/2989413766,sevastopol,участок 7 сот. (ижс),NaN,3200000,"пос. Кача, ул. Евграфа Рыжова, 23",Пгт Кача. Лучшее предложение данного района. В...,2024-09-09 12:53:24.129387,7.0,True,3.200000,0.457143,4-8
13212,https://sevastopol.cian.ru/sale/suburban/30026...,sevastopol,"участок, 10 сот., ижс",,4500000,"Севастополь, р-н Нахимовский, улица Крейсерска...",Продам ВИДОВОЙ участок - шикарный вид на откры...,2024-06-19 12:23:33.870565,10.0,True,4.500000,0.450000,8-12
59510,https://www.avito.ru/3880962339,sevastopol,"участок 4 сот. (снт, днп)",NaN,2400000,садоводческое товарищество Гераклея,"Продам видовой участок площадью 4 сотки. Свет,...",2024-06-11 10:32:52.971878,4.0,False,2.400000,0.600000,2-4
48841,https://www.avito.ru/4197246874,sevastopol,"участок 6 сот. (снт, днп)",NaN,2250000,"Монастырское ш., 116А/1",Добpого вpемeни суток. Продаю зeмельный учaсто...,2024-07-30 16:22:13.854597,6.0,False,2.250000,0.375000,4-8
38215,https://www.avito.ru/4206886362,sevastopol,"участок 4,5 сот. (ижс)",NaN,4250000,"Балаклава, ул. Крестовского",Первая Линия Видовойижс. Идеально под Коммерци...,2024-09-09 12:53:24.129387,4.5,True,4.250000,0.944444,4-8
52596,https://www.avito.ru/3851105681,bahchisaray,участок 5 га (личное подсобное хозяйство (лпх)),NaN,4999999,с. Новенькое,Объект №1568. Продам участок сельскохозяйствен...,2024-07-08 13:48:33.488742,500.0,False,4.999999,0.010000,20+
53321,https://www.avito.ru/3792024062,sevastopol,участок 5 сот. (ижс),NaN,4400000,"Крепостное ш., 23к9",Продам земельный участок расположенный на Креп...,2024-08-20 09:50:33.232766,5.0,True,4.400000,0.880000,4-8

---

In [8]:
obj_type = 'house'
files = [ f'{d}/{f}' for d in source[obj_type] for f in listdir(d) if f[-4:]=='.pkl' ]
display( len(files) )

cols = ['url','place','title','subtitle','price','address','description','ts',]

df_house = pd.concat([
        pd.read_pickle(f).drop_duplicates(['url'])
        for f in files
    ]).reset_index(drop=True)[cols]

display( len(df_house) )
display(df_house.sample(9))

100

57214

,url,place,title,subtitle,price,address,description,ts
31627,https://www.avito.ru/4081489874,bahchisaray,Дом 275 м² на участке 12 сот.,NaN,23000000,"с. Баштановка, Первомайская ул., 58",Объект №290. Продам Домовладение В Окружении Г...,2024-07-16 12:53:15.108359
45343,https://www.avito.ru/834246415,sudak,Дом 100 м² на участке 3 сот.,NaN,11000000,"ул. Айвазовского, 7",Продаю Срочно в живописном уголке Крыма дом 95...,2024-07-08 13:46:29.585102
39398,https://www.avito.ru/3168893284,sevastopol,"Дом 56,4 м² на участке 4,2 сот.",NaN,6500000,"с. Орловка, Школьная ул., 18",Собственник! Идеально Для Сертификата! Продаёт...,2024-06-24 13:01:06.410833
29469,https://www.avito.ru/4040660626,sevastopol,"Дом 177,2 м² на участке 8 сот.",NaN,14500000,"с. Осипенко, Лазурная ул., 38","Супер предложение — прекрасный дом, в живописн...",2024-08-12 11:27:30.996664
42076,https://www.avito.ru/4073536554,sevastopol,"Дом 275 м² на участке 2,8 сот.",NaN,15500000,ул. Крошицкого,Продается новый современный дом 270 м2 в прест...,2024-08-20 09:57:45.024714
24715,https://www.avito.ru/2343268492,sevastopol,Дом 192 м² на участке 6 сот.,NaN,15000000,"садовое товарищество Поиск, 238",Продажа нового дома от застройщика. Монолитный...,2024-06-17 08:43:09.491886
627,https://sevastopol.cian.ru/sale/suburban/30033...,sevastopol,"Дом, 30 м², 5.5 сот., Садоводство",,3300000,"Севастополь, р-н Нахимовский, Дружба садоводче...",Продам жилую дачу в СНТ Дружба( Доковая балка)...,2024-06-11 10:23:05.308675
21142,https://www.avito.ru/3816071387,bahchisaray,Дом 52 м² на участке 1 сот.,NaN,2500000,"с. Брянское, Черноморская ул., 1",Продается 50% часть жилого помещения на террит...,2024-06-14 13:24:56.973530
42190,https://www.avito.ru/2380215856,bahchisaray,Дом 250 м² на участке 17 сот.,NaN,12500000,с. Красный Мак,"Добротный дом свежей постройки, в котором сейч...",2024-06-13 11:37:16.726876

In [9]:
# cols = ['title','address','place','url']
# df_house[ (df_house['place']=='sevastopol') & (df_house['address'].str.match(r'.*Судак.*')) ][cols]

In [10]:
from lib.cleaner import CleanerHouse

df_house = CleanerHouse().transform(df_house)

display( len(df_house) )
display(df_house.sample(9))

57214

,url,place,title,subtitle,price,address,description,ts,house_area,is_part,is_townhouse,is_SNT,land_area,priceM,land_size_category,house_size_category
51363,https://www.avito.ru/3776110645,sevastopol,дом 110 м² на участке 4 сот.,NaN,12500000,СТ Конус,"Дом 110 м² на участке 4 сотки, одноэтажный. Ра...",2024-07-22 11:20:00.587621,110.0,False,False,True,4.0,12.500,2-4,70-110
20788,https://krym.cian.ru/sale/suburban/304150387/,sudak,"дом, 117 м², 6 сот., садоводство",,5447000,"Республика Крым, Судак городской округ, с. Мин...",Предлагаем вашему вниманию дом от надежного за...,2024-07-16 12:55:43.335990,117.0,False,False,False,6.0,5.447,4-8,110-180
43993,https://www.avito.ru/3461309704,sevastopol,"дом 108,8 м² на участке 5,5 сот.",NaN,10500000,"Лукомская ул., 245",Предлагается к продаже новый одноэтажный трехк...,2024-08-06 11:17:09.275527,108.8,False,False,False,5.5,10.500,4-8,70-110
8200,https://sevastopol.cian.ru/sale/suburban/29897...,sevastopol,"дом, 230 м², 5.51 сот.",,15000000,"Севастополь, р-н Балаклавский, Родник ТСН, ули...","Дом 230 м2 на участке 5,51 сотка, трехэтажный....",2024-06-10 11:23:47.056251,230.0,False,False,True,51.0,15.000,20+,180-300
44697,https://www.avito.ru/2425690272,bahchisaray,дом 100 м² на участке 15 сот.,NaN,35000000,"с. Новоульяновка, Молодёжная ул.",Сдам или продам газифицированый дом в Новоулья...,2024-09-03 13:49:48.105323,100.0,False,False,False,15.0,35.000,12-20,70-110
28087,https://www.avito.ru/4208313692,sevastopol,"дом 108 м² на участке 4,3 сот.",NaN,6200000,"ТСН Эра-2, 242",Продам новый дом в Тсн СТ Эра-2 улица Майора Б...,2024-08-12 11:27:30.996664,108.0,False,False,True,4.3,6.200,4-8,70-110
41513,https://www.avito.ru/3899600602,sevastopol,"дом 70 м² на участке 2,8 сот.",NaN,4500000,Персиковая ул.,Лот № 74012. В прямой продаже дом. Дом 70 м² н...,2024-08-20 09:57:45.024714,70.0,False,False,False,2.8,4.500,2-4,50-70
36402,https://www.avito.ru/2900859000,sevastopol,дом 120 м² на участке 4 сот.,NaN,9000000,"садоводческое товарищество Атлантика-3, 51","Объект №27262. Продаю новый, солнечный дом 120...",2024-06-10 11:33:36.811644,120.0,False,False,True,4.0,9.000,2-4,110-180
10969,https://sevastopol.cian.ru/sale/suburban/29906...,sevastopol,"дом, 180 м², 8 сот.",,11500000,"Севастополь, р-н Гагаринский, мкр. Фиолент, Бр...",Дом 180 м² на участке 8 соток Дом 180 м² на уч...,2024-06-19 12:37:23.275933,180.0,False,False,True,8.0,11.500,4-8,110-180

## обновляем таблицу адресов

In [11]:
# !pip install geopy

In [12]:
# df_flat['address'].str.strip().drop_duplicates().sort_values().to_csv('tmp/flat_address.txt',index=False,header=False)
# df_land['address'].str.strip().drop_duplicates().sort_values().to_csv('tmp/land_address.txt',index=False,header=False)
# df_house['address'].str.strip().drop_duplicates().sort_values().to_csv('tmp/house_address.txt',index=False,header=False)

In [13]:
from lib.locator import AddressTransformer

atr = AddressTransformer()

places = { 
# поле 'place' и название города
'bahchisaray': 'Бахчисарай,',
      'sudak': 'Судак,',
  'sevastopol': 'Севастополь,',
}

def address_norm(df,atr=atr):
    df['address_orig'] =  df['address']
    df['address'] =  df['address'].apply(atr.transform)
    df['place_'] =  df['place'].map(places)
    df['address'] = df[['address','place_']].apply(lambda d: d[0] if d[1] in d[0] else d[1]+','+d[0],axis=1) 
    df['address'] = (
        df['address']
        .str.replace(', ',',')
        .str.replace(',,',',')
        .str.replace('. ','.')
        .str.replace('\n',' ')
        .str.replace('  ',' ')
        .str.lower()
    )
    return df

In [14]:
df_flat = address_norm(df_flat)
df_land = address_norm(df_land)
df_house = address_norm(df_house)

/tmp/ipykernel_3195287/776805188.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['address'] = df[['address','place_']].apply(lambda d: d[0] if d[1] in d[0] else d[1]+','+d[0],axis=1)
/tmp/ipykernel_3195287/776805188.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['address'] = df[['address','place_']].apply(lambda d: d[0] if d[1] in d[0] else d[1]+','+d[0],axis=1)
/tmp/ipykernel_3195287/776805188.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['address'] = df[['address','place_']].apply(lambda d: d[0] if d[1] in d[0] else d[1]+','+d[0],axis=1)

In [15]:
# df_flat[['address','address_orig']]

In [16]:
address = pd.concat([
        df_flat[['address','address_orig']],
        df_land[['address','address_orig']],
        df_house[['address','address_orig']],
    ]).drop_duplicates(['address']).reset_index(drop=True)

display(len(address))
display(address.sample(5))

13704

,address,address_orig
6637,"севастополь,пр.артиллеристов",пр. Артиллеристов
13051,"севастополь,пос.кача,ул.покрышкина","пос. Кача, ул. Покрышкина"
7141,"севастополь,1-я комендорская ул.",1-я Комендорская ул.
4711,"севастополь,р-н нахимовский,мкр.корабельная ст...","Севастополь, р-н Нахимовский, мкр. Корабельная..."
11020,"бахчисарай,ул.ленина",ул. Ленина

In [17]:
from os.path import exists as path_exists
loc_file_path = 'data/location.pkl' # таблица адресов

location = pd.DataFrame([],columns=['address','latitude','longitude',])
if path_exists( loc_file_path ):
    location = pd.read_pickle(loc_file_path).drop_duplicates(['address']).reset_index(drop=True)
    
display(len(location))
display(location.sample(5))

19980

                                                 address   latitude  longitude
3538     севастополь,нахимовский район ,мкр-н горпищенко  44.596556   33.56379
17128             севастополь,улица генерала жидилова,28  44.605554  33.568659
2891                           севастополь,кирпичная ул.  44.608628  33.512748
14110          севастополь,садовое товарищество скиф,312  44.516867  33.507007
5229   севастополь,р-н балаклавский,пос.1-е отделение...   44.53265  33.594018

---

In [18]:
# def address_norm_(df):
#     df['address_orig'] =  df['address']
#     # df['address'] =  df['address'].apply(atr.transform)
#     df['address'] = (
#         df['address']
#         .str.replace(', ',',')
#         .str.replace(',,',',')
#         .str.replace('. ','.')
#         .str.replace('\n',' ')
#         .str.replace('  ',' ')
#         .str.lower()
#     )
#     return df

In [19]:
# location = address_norm_(location)

In [20]:
# location = location[['address','latitude','longitude']]

---

In [21]:
# собираем все адреса в один список
location = location.merge(
        address[['address']].drop_duplicates(),
        how='outer',
        on='address',
    ).drop_duplicates(['address']).reset_index(drop=True)

display(len(location))
display(location.sample(5))

20180

                                                 address   latitude  longitude
19594  судак,республика крым,судак городской округ,с....  44.872395  35.108847
16891                         севастополь,ул.сладкова,2д  44.597801    33.4781
9477   севастополь,р-н нахимовский,улица ромашковая,135а  44.585618  33.577786
7154   севастополь,р-н гагаринский,мкр.фиолент,чайка-...  44.527503  33.468425
13350   севастополь,садоводческое товарищество пищевик,1   44.57035  33.505435

In [22]:
display(len(location))
display(location['latitude'].isnull().sum())

20180

200

In [23]:
# собираем все адреса с геопозицией
location_def = location[~location['latitude'].isna()].reset_index(drop=True)
display(len(location_def))

# собираем все адреса без геопозиции
location_undef = location[location['latitude'].isna()][['address']].reset_index(drop=True)
display(len(location_undef))

19980

200

In [24]:
display(location_undef)

                                      address
0                бахчисарай,кольцевая ул.,10а
1        бахчисарай,с.голубинка,ул.ленина,18а
2           бахчисарай,с.каштаны,плодовая ул.
3    бахчисарай,с.прохладное,парниковая ул.,1
4           бахчисарай,с.танковое,ул.дружбы,6
..                                        ...
195        судак,с.миндальное,сот капсель,103
196         судак,с.миндальное,сот капсель,53
197        судак,с.радостное,колхозная ул.,10
198    судак,садовое товарищество ветеран,120
199                  судак,улица 14 апреля,17

[200 rows x 1 columns]

In [25]:
from tqdm.auto import tqdm
tqdm.pandas()

In [26]:
# from lib.locator import GeocoderSimpleOSM
from lib.locator import GeocoderYandex
from yandex_keys import keys

atr = AddressTransformer()
locator = GeocoderYandex(keys[0])
# locator = GeocoderSimpleOSM()

if len(location_undef)>0:
    # определяем координаты по строке адреса
    location_undef = location_undef.join( 
            location_undef['address'].progress_apply(locator.transform).apply(pd.Series) 
        ).dropna()     
    display(f'LocationUpdater: {len(location_undef)} new addresses found')
    location = pd.concat([location_def,location_undef]).reset_index(drop=True) 
    assert len(location)>0
    # location.to_pickle(loc_file_path)

  0%|          | 0/200 [00:00<?, ?it/s]

'LocationUpdater: 200 new addresses found'

In [27]:
display( len(location) )
display( location.sample(3) )

20180

                                                address   latitude  longitude
3928                       севастополь,планерная ул.,73  44.577837  33.494593
3276                       севастополь,маслиновая улица  44.644373  33.542087
188   бахчисарай,республика крым,бахчисарайский райо...  44.659339  33.809353

In [28]:
assert len(location)>0
location.to_pickle(loc_file_path)

## дополняем данные геометкой

In [29]:
display( len(df_flat) )
df_flat  = df_flat.merge(location,on='address').reset_index(drop=True) 
display( len(df_flat) )
display( df_flat.sample(3) )

74010

74010

,url,place,title,subtitle,price,address,description,ts,nrooms,floor,...,is_auction,is_openspace,is_roof,is_SNT,priceM,is_last_floor,address_orig,place_,latitude,longitude
13441,https://krym.cian.ru/sale/flat/304546463/,sudak,"1-комн. квартира, 46,8 м², 6/8 этаж",,9800000,"республика крым,судак,улица ленина,35а",Ваша уютная гавань в центре города! Предлагаем...,2024-08-06 11:15:49.423503,0,6,...,False,False,False,False,9.800,False,"Республика Крым, Судак, улица Ленина, 35А","Судак,",44.854309,34.97613
43678,https://www.avito.ru/3801414208,sevastopol,"3-к. квартира, 70,1 м², 1/3 эт.",NaN,14600000,"севастополь,партизанская улица ,9","Трехкомнатная квартира 70.1 м2, на 1/ 3 этаже ...",2024-06-17 08:29:48.414678,3,1,...,False,False,False,False,14.600,False,"Партизанская улица , 9","Севастополь,",44.609603,33.515595
7129,https://sevastopol.cian.ru/sale/flat/292656591/,sevastopol,"студия, 25,8 м², 3/3 этаж",Секция 1 • Сдача корпуса 4 кв. 2024,2838000,"севастополь,р-н гагаринский,сатурн ст ,аллея з...","ЖК ""Голубая Бухта"" — это неповторимое сочетани...",2024-06-11 10:13:23.305322,0,3,...,False,False,False,True,2.838,True,"Севастополь, р-н Гагаринский, Сатурн СТ , алле...","Севастополь,",44.556593,33.412478

In [30]:
display( len(df_land) )
df_land  = df_land.merge(location,on='address').reset_index(drop=True) 
display( len(df_land) )
display( df_land.sample(3) )

63718

63718

,url,place,title,subtitle,price,address,description,ts,area,is_IJS,priceM,priceMU,area_size_category,address_orig,place_,latitude,longitude
51686,https://www.avito.ru/2718220761,bahchisaray,"участок 6 сот. (снт, днп)",NaN,500000,"бахчисарай,садоводческий потребительский коопе...",Отличная возможность построить дом. До моря — ...,2024-06-24 13:05:30.092315,6.0,False,0.5,0.083333,4-8,садоводческий потребительский кооператив Энтуз...,"Бахчисарай,",44.815279,33.789276
9253,https://sevastopol.cian.ru/sale/suburban/30115...,sevastopol,"участок, 8 сот., ижс",,3300000,"севастополь,р-н нахимовский,улица комиссара ищ...","Участок 8 соток (ИЖС) в г. Севастополь, Нахимо...",2024-09-03 13:49:29.818498,8.0,True,3.3,0.412500,4-8,"Севастополь, р-н Нахимовский, улица Комиссара ...","Севастополь,",44.600741,33.5698
61819,https://www.avito.ru/2756888618,sevastopol,участок 4 сот. (ижс),NaN,1700000,"севастополь,район северная сторона",Kaд. Номep 91:04:011001:1031. Продается видово...,2024-06-07 11:38:45.101812,4.0,True,1.7,0.425000,2-4,район Северная Сторона,"Севастополь,",44.630185,33.538206

In [31]:
display( len(df_house) )
df_house = df_house.merge(location,on='address').reset_index(drop=True) 
display( len(df_house) )
display( df_house.sample(3) )

57214

57214

,url,place,title,subtitle,price,address,description,ts,house_area,is_part,is_townhouse,is_SNT,land_area,priceM,land_size_category,house_size_category,address_orig,place_,latitude,longitude
8802,https://sevastopol.cian.ru/sale/suburban/27351...,sevastopol,"дом, 40 м², 5 сот., садоводство",,8100000,"севастополь,р-н нахимовский,мкр.северная сторо...","Объект 119. Дом на земельном участке 5,38 сото...",2024-06-10 11:23:47.056251,40.0,False,False,True,5.0,8.1,4-8,30-50,"Севастополь, р-н Нахимовский, мкр. Северная ст...","Севастополь,",44.637575,33.535206
25801,https://www.avito.ru/3200578699,sevastopol,"коттедж 425 м² на участке 7,5 сот.",NaN,99900000,"севастополь,тендровская ул.,87","Дом 425 м² на участке 7,5 соток. Дом 425 м² на...",2024-06-17 08:43:09.491886,425.0,False,False,False,7.5,99.9,4-8,300+,"Тендровская ул., 87","Севастополь,",44.547247,33.538026
13770,https://sevastopol.cian.ru/sale/suburban/29902...,sevastopol,"дом, 78 м², 4 сот., ижс",,7800000,"севастополь,р-н ленинский,улица феодосийская,78",Не упустите шанс купить дом по хорошей цене! П...,2024-06-18 10:55:44.416781,78.0,False,False,False,4.0,7.8,2-4,70-110,"Севастополь, р-н Ленинский, улица Феодосийская...","Севастополь,",44.584411,33.49939

In [32]:
# def address_filter(df):
#     #           46.319437, 33.911048
#     #
#     # 45.402617, 32.455625 |  45.545301, 36.684702
#     #
#     #          44.320887, 33.917013

#     df['latitude'] = pd.to_numeric( df['latitude'], errors='coerce' )
#     df['longitude'] = pd.to_numeric( df['longitude'], errors='coerce' )

#     df = df.query('(32.4<longitude<36.7) & (44.3<latitude<46.4)') 

#     df.loc[ df['url']=='https://avito.ru/2322251740', ['latitude','longitude']] = None

#     df.loc[ df['address']=='Севастополь,Чёрное море', ['latitude','longitude'] ] = None
#     df.loc[ df['address'].str.lower().str.match('чёрное море'), ['latitude','longitude'] ] = None 

#     df.loc[ df['address']=='квартал Старый Город', 'place'] = 'turkie'
#     df.loc[ df['address'].str.lower().str.match('анталья'), 'place' ] = 'turkie' 

#     df.loc[ df['address'].str.lower().str.match(r'.*бахчисарай.*'), 'place' ] = 'bahchisaray'
#     df.loc[ df['address'].str.lower().str.match(r'.*севастополь,.*'), 'place' ] = 'sevastopol'

#     df.loc[ df['address'].str.lower().str.match(r'.*мысовское.*'), 'place' ] = 'kerch'
#     df.loc[ df['address'].str.lower().str.match(r'.*алушта.*'), 'place' ] = 'alushta'
#     df.loc[ df['address'].str.lower().str.match(r'.*гурзуф.*'), 'place' ] = 'gurzuf'

#     df.loc[ df['address'].str.lower().str.match(r'.*с.лучистое.*'), 'place' ] = 'alushta'
#     df.loc[ df['address'].str.lower().str.match(r'.*снт солнечная долина.*'), 'place' ] = 'sudak'
#     df.loc[ df['address'].str.lower().str.match(r'.*пгт.новоозёрное.*'), 'place' ] = 'evpatoria'

#     df.loc[ df['address'].str.lower().str.match(r'.*с.мирное.*'), 'place' ] = 'simferopol'
#     df.loc[ df['address'].str.lower().str.match(r'.*тсн аэрофлот.*'), 'place' ] = 'simferopol'

#     df.loc[ df['address'].str.lower().str.match(r'.*семисот.*'), 'place' ] = 'kerch'

#     df.loc[ df['address'].str.lower().str.match(r'.*ялта.*') , 'place' ] = 'yalta'
#     df.loc[ df['address'].str.lower().str.match(r'.*феодосия.*') , 'place' ] = 'feodosia'
#     df.loc[ df['address'].str.lower().str.match(r'.*окуневка.*') , 'place' ] = 'tarkhankut'
#     df.loc[ df['address'].str.lower().str.match(r'.*заветное.*') , 'place' ] = 'kerch'
#     df.loc[ df['address'].str.lower().str.match(r'.*евпатория.*') , 'place' ] = 'evpatoria'
#     df.loc[ df['address'].str.lower().str.match(r'.*симферопольский район.*'), 'place' ] = 'simferopol'

#     df.loc[df['address'].str.match(r'.*белогорск.*'),'place'] = 'belogorsk'
#     df.loc[df['address'].str.match(r'.*кировский.*'),'place'] = 'kirovsky'
#     df.loc[df['address'].str.match(r'.*сакский район.*'),'place'] = 'saki'
#     df.loc[df['address'].str.match(r'.*керчь.*'),'place'] = 'kerch'
#     df.loc[df['address'].str.match(r'.*белогорский.*'),'place'] = 'belogorsk'
#     df.loc[df['address'].str.match(r'.*кировский.*'),'place'] = 'kirovski'

#     df.loc[df['address'].str.match(r'.*кореиз.*'),'place'] = 'ubk'
#     df.loc[df['address'].str.match(r'.*малый маяк.*'),'place'] = 'ubk'
#     df.loc[df['address'].str.match(r'.*светлый мир.*'),'place'] = 'simferopol'
#     df.loc[df['address'].str.match(r'.*доброе.*'),'place'] = 'simferopol'
#     df.loc[df['address'].str.match(r'.*родниково.*'),'place'] = 'simferopol'
#     df.loc[df['address'].str.match(r'.*уютное.*'),'place'] = 'evpatoria'
#     df.loc[df['address'].str.match(r'.*коктебель.*'),'place'] = 'koktebel'
#     df.loc[df['address'].str.match(r'.*новосельское.*'),'place'] = 'tarhankut'

#     df = df.dropna(subset=['latitude','longitude'])
    
#     return df

In [33]:
# display(len(df_flat))
# df_flat = address_filter(df_flat)
# display(len(df_flat))

# display(len(df_land))
# df_land = address_filter(df_land)
# display(len(df_land))

# display(len(df_house))
# df_house = address_filter(df_house)
# display(len(df_house))

In [34]:
assert len(df_flat)>0
df_flat.to_pickle(f'{data_root_folder}/df_flat.pkl')

assert len(df_land)>0
df_land.to_pickle(f'{data_root_folder}/df_land.pkl')

assert len(df_house)>0
df_house.to_pickle(f'{data_root_folder}/df_house.pkl')

In [35]:
!date

Пн 16 сен 2024 13:41:53 MSK