__собираем объявления о продаже недвижимости в одну таблицу__

_Evgeny S. Borisov <parser@mechanoid.su>_

In [1]:
!date

Чт 13 июн 2024 11:39:55 MSK

In [2]:
from os import listdir
import re
import pandas as pd

In [3]:
data_root_folder = 'data/2024'
source = {
         'flat':[data_root_folder+'/raw/flat/cian',data_root_folder+'/raw/flat/avito'],
        'house':[data_root_folder+'/raw/house/cian',data_root_folder+'/raw/house/avito'],
         'land':[data_root_folder+'/raw/land/cian',data_root_folder+'/raw/land/avito'],
    }

---

In [4]:
obj_type = 'flat'
files = [ f'{d}/{f}' for d in source[obj_type] for f in listdir(d) if f[-4:]=='.pkl' ]
display( len(files) )

cols = ['url','place','title','subtitle','price','address','description','ts',]

df_flat = pd.concat([
        pd.read_pickle(f).drop_duplicates(['url'])
        for f in files
    ]).reset_index(drop=True)[cols]

display( len(df_flat) )
display(df_flat.sample(9))

16

16906

,url,place,title,subtitle,price,address,description,ts
12130,https://www.avito.ru/3800817009,sevastopol,"2-к. квартира, 51,3 м², 1/5 эт.",NaN,9000000,"Казачья ул., 8",Двухкомнатная квартира «чешского» проекта обще...,2024-06-11 10:25:30.856703
9103,https://www.avito.ru/3819485941,sevastopol,"2-к. квартира, 53,1 м², 5/5 эт.",NaN,9750000,"Боцманская ул., 3",Объект №1553. В продаже уютная 2-комнатная ква...,2024-06-07 11:27:07.236636
9835,https://www.avito.ru/3880755918,sevastopol,"2-к. квартира, 60 м², 3/9 эт.",NaN,8900000,"ул. Героев Бреста, 27",Продам 2-комнатную квартиру в одном из лучших ...,2024-06-07 11:27:07.236636
13029,https://www.avito.ru/3755007774,sevastopol,"1-к. квартира, 42,2 м², 7/10 эт.",NaN,12000000,"ул. Адмирала Фадеева, 46Бк2","Однокомнатная квартира 42,2 м2 на 7/10 этаже д...",2024-06-13 11:17:37.489999
2783,https://sevastopol.cian.ru/sale/flat/302799805/,sevastopol,"1-комн. квартира, 39,6 м², 5/5 этаж",,5500000,"Севастополь, р-н Нахимовский, мкр. Радиогорка,...","Продаю видовую квартиру в городе Севастополе, ...",2024-06-11 10:13:23.305322
15839,https://www.avito.ru/3144744959,sevastopol,"1-к. квартира, 31 м², 3/3 эт.",NaN,4500000,"ул. Надежды Краевой, 5",Продаю 1-х комнатную квартиру на Северной стор...,2024-06-10 11:17:35.151941
12519,https://www.avito.ru/4165759945,sevastopol,"1-к. квартира, 31,2 м², 3/3 эт.",NaN,5499000,"ул. Надежды Краевой, 15",Продаётся однокомнатная квартира на Северной с...,2024-06-13 11:17:37.489999
15802,https://www.avito.ru/3703747863,sevastopol,"3-к. квартира, 70,5 м², 2/3 эт.",NaN,14900000,"Большая Морская ул., 25",Продается трехкoмнaтнaя кваpтиpа на ул. Больша...,2024-06-10 11:17:35.151941
13924,https://www.avito.ru/3672346322,sevastopol,"1-к. апартаменты, 18 м², 1/3 эт.",NaN,3300000,"ул. Военных Строителей, 1В/1","Апартаменты 18 м2, 1/3 эт. Апартаменты 18 м2, ...",2024-06-13 11:17:37.489999

In [5]:
from lib.cleaner import CleanerFlat

df_flat = CleanerFlat().transform(df_flat)
display( len(df_flat) )
display(df_flat.sample(9))

16906

,url,place,title,subtitle,price,address,description,ts,nrooms,floor,...,area,is_studio,is_apartment,is_part,is_auction,is_openspace,is_roof,is_SNT,priceM,is_last_floor
956,https://sevastopol.cian.ru/sale/flat/299737202/,sevastopol,"3-комн. квартира, 76,3 м², 8/9 этаж",,12990000,"Севастополь, р-н Гагаринский, мкр. Камышовая б...","Трехкомнатная квартира 76,3 м2, на 8/9 этаже д...",2024-06-07 11:33:12.800097,0,8,...,76.3,False,False,False,False,False,False,False,12.990000,False
9004,https://www.avito.ru/3994531857,sevastopol,"3-к. квартира, 69 м², 2/3 эт.",NaN,13500000,"Большая Морская улица , 29",Объект №851. Продается трехкомнатная квартира ...,2024-06-07 11:27:07.236636,3,2,...,69.0,False,False,False,False,False,False,False,13.500000,False
12546,https://www.avito.ru/4123168040,sevastopol,"3-к. квартира, 75,2 м², 8/9 эт.",NaN,11100000,ЖК «Porto Franco»\n улица Западный берег Камыш...,"Продаётся 3-комнатная квартира №77, площадь 75...",2024-06-13 11:17:37.489999,3,8,...,75.2,False,False,False,False,False,False,False,11.100000,False
8997,https://www.avito.ru/3847232709,sevastopol,"3-к. квартира, 63,1 м², 9/9 эт.",NaN,12500000,"Лоцманская улица , 3","Видовая квартира с ремонтом! Дом панельный, ме...",2024-06-07 11:27:07.236636,3,9,...,63.1,False,False,False,False,False,False,False,12.500000,True
4395,https://sevastopol.cian.ru/sale/flat/303063389/,sevastopol,"1-комн. квартира, 25,3 м², 1/3 этаж",,5350000,"Севастополь, р-н Ленинский, мкр. Центр, улица ...",Продам 1-комнатную квартиру в самом сердце г. ...,2024-06-10 11:06:41.395615,0,1,...,25.3,False,False,False,False,False,False,False,5.350000,False
8817,https://www.avito.ru/3903416013,sevastopol,"1-к. квартира, 34,8 м², 9/12 эт.",NaN,5931695,"ЖК «Александрия»\n улица Колобова, д. 2/1, сек...",Открыты продажи 4 секции в ЖК «Александрия». С...,2024-06-07 11:27:07.236636,1,9,...,34.8,False,False,False,False,False,False,False,5.931695,False
3391,https://sevastopol.cian.ru/sale/flat/299736297/,sevastopol,"3-комн. квартира, 61,9 м², 4/5 этаж",,7500000,"Севастополь, р-н Ленинский, мкр. Острякова, пр...","Трехкомнатная квартира 61,9 м2, на 4/5 этаже д...",2024-06-10 11:06:41.395615,0,4,...,61.9,False,False,False,False,False,False,False,7.500000,False
7164,https://www.avito.ru/3813899983,sudak,"1-к. квартира, 40,7 м², 3/9 эт.",NaN,6098000,Комплекс апартаментов «Бирюзовый квартал»\n ул...,"Ипотека от 11,5% платеж от 26 000р. Кладовка В...",2024-06-13 11:33:20.210428,1,3,...,40.7,False,False,False,False,False,False,False,6.098000,False
1567,https://sevastopol.cian.ru/sale/flat/301225217/,sevastopol,"2-комн. квартира, 46 м², 2/5 этаж",,6200000,"Севастополь, р-н Ленинский, мкр. Острякова, пр...","Продам двухкомнатную квартиру площадью 46 м2, ...",2024-06-07 11:33:12.800097,0,2,...,46.0,False,False,False,False,False,False,False,6.200000,False

---

In [6]:
obj_type = 'land'
files = [ f'{d}/{f}' for d in source[obj_type] for f in listdir(d) if f[-4:]=='.pkl' ]
display( len(files) )

cols = ['url','place','title','subtitle','price','address','description','ts',]

df_land = pd.concat([
        pd.read_pickle(f).drop_duplicates(['url'])
        for f in files
    ]).reset_index(drop=True)[cols]

display( len(df_land) )
display(df_land.sample(9))

20

14209

,url,place,title,subtitle,price,address,description,ts
10590,https://www.avito.ru/3802852848,sevastopol,"Участок 10 сот. (СНТ, ДНП)",NaN,2650000,товарищество собственников недвижимость Сухарн...,Лот № 73912. Предлагаем к продаже земельный уч...,2024-06-13 11:24:39.283050
1946,https://sevastopol.cian.ru/sale/suburban/30279...,sevastopol,"Участок, 8.43 сот.",,1265000,"Севастополь, р-н Балаклавский, с. Широкое",ПРОДАМ земельный участок в Севастополе в тихом...,2024-06-07 11:37:10.690720
9862,https://www.avito.ru/4514218070,sevastopol,"Участок 10,8 сот. (СНТ, ДНП)",NaN,6800000,"СНТ Сапун-гора, 1593",Объект №373. Участок 10.8 сотки (СТ) расположе...,2024-06-13 11:24:39.283050
9242,https://www.avito.ru/3912831984,bahchisaray,"Участок 2 га (СНТ, ДНП)",NaN,1600000,"Республика Крым, Ароматненское сельское поселение",Продаётся уникальный участок земли площадью 2 ...,2024-06-13 11:36:28.263004
6163,https://www.avito.ru/3747128765,sevastopol,Участок 6 сот. (ИЖС),NaN,2000000,"ул. Коли Жартовского, 45",Видовой участок 6 соток! Под строительство час...,2024-06-10 11:25:16.532576
12629,https://www.avito.ru/3808378007,sevastopol,"Участок 5,2 сот. (ИЖС)",NaN,2450000,Маслиновая ул.,"Участок 5,17 соток СТ. Участок 5,17 соток (СТ)...",2024-06-11 10:32:52.971878
9456,https://www.avito.ru/4101073267,sevastopol,Участок 4 сот. (ИЖС),NaN,3350000,садоводческое товарищество Икар-2,Продам участок площадью 4 сотки в Гагаринском ...,2024-06-13 11:24:39.283050
1070,https://sevastopol.cian.ru/sale/suburban/29266...,sevastopol,"Участок, 10 сот., ИЖС",,3300000,"Севастополь, р-н Балаклавский, с. Передовое, у...","В одном из лучших мест Байдарской долины, в се...",2024-06-11 10:17:41.455159
1518,https://sevastopol.cian.ru/sale/suburban/29646...,sevastopol,"Участок, 4.2 сот., Садоводство",,2300000,"Севастополь, р-н Гагаринский, Строитель садово...",Объект 1718. Продается в районе города участок...,2024-06-07 11:37:10.690720

In [7]:
from lib.cleaner import CleanerLand

df_land = CleanerLand().transform(df_land)

display( len(df_land) )
display(df_land.sample(9))

14209

,url,place,title,subtitle,price,address,description,ts,area,is_IJS,priceM,priceMU,area_size_category
8649,https://www.avito.ru/2525275422,bahchisaray,участок 8 сот. (ижс),NaN,2500000,"с. Синапное, Зелёная ул., 13","Продам земельный участок 8 сот., в селе есть г...",2024-06-10 11:38:42.490270,8.0,True,2.50,0.312500,4-8
2158,https://sevastopol.cian.ru/sale/suburban/30261...,sevastopol,"участок, 4 сот., ижс",,2300000,"Севастополь, р-н Нахимовский, с. Полюшко",Представляем Вашему вниманию уникальное предло...,2024-06-07 11:37:10.690720,4.0,True,2.30,0.575000,2-4
1845,https://sevastopol.cian.ru/sale/suburban/28910...,sevastopol,"участок, 9.96 сот., ижс",,3500000,"Севастополь, р-н Балаклавский, улица Чернорече...","Участок 9,96 соток СТ Участок 9,96 соток (СТ) ...",2024-06-07 11:37:10.690720,96.0,True,3.50,0.036458,20+
10170,https://www.avito.ru/3408967124,sevastopol,"участок 5,6 сот. (ижс)",NaN,4700000,"Редутная ул., 25",Объект №1083. Продам участок по улице Редутная...,2024-06-13 11:24:39.283050,5.6,True,4.70,0.839286,4-8
259,https://sevastopol.cian.ru/sale/suburban/30112...,sevastopol,"участок, 4.5 сот., ижс",,3850000,"Севастополь, р-н Балаклавский, Бриз СНТ, 132","Участок 4,46 сотки (СТ) расположен в г. Севаст...",2024-06-11 10:17:41.455159,5.0,True,3.85,0.770000,4-8
313,https://sevastopol.cian.ru/sale/suburban/29999...,sevastopol,"участок, 4.99 сот., ижс",,2500000,"Севастополь, р-н Гагаринский, Рябинушка садово...",,2024-06-11 10:17:41.455159,99.0,True,2.50,0.025253,20+
8071,https://www.avito.ru/3944787097,bahchisaray,участок 4 сот. (ижс),NaN,5800000,"ул. Ракитского, 7В",Продам участок со всеми коммуникациями в центр...,2024-06-10 11:38:42.490270,4.0,True,5.80,1.450000,2-4
852,https://sevastopol.cian.ru/sale/suburban/29783...,sevastopol,"участок, 4.5 сот., садоводство",,2700000,"Севастополь, р-н Нахимовский, Качинский муници...",Объект 28156. Прекрасный земельный участок с в...,2024-06-11 10:17:41.455159,5.0,False,2.70,0.540000,4-8
1088,https://sevastopol.cian.ru/sale/suburban/30277...,sevastopol,"участок, 5.5 сот., ижс",,3500000,"Севастополь, р-н Нахимовский, Сапун-гора СНТ, 2",Продаётся участок в городе Севастополь СНТ Сап...,2024-06-11 10:17:41.455159,5.0,True,3.50,0.700000,4-8

---

In [8]:
obj_type = 'house'
files = [ f'{d}/{f}' for d in source[obj_type] for f in listdir(d) if f[-4:]=='.pkl' ]
display( len(files) )

cols = ['url','place','title','subtitle','price','address','description','ts',]

df_house = pd.concat([
        pd.read_pickle(f).drop_duplicates(['url'])
        for f in files
    ]).reset_index(drop=True)[cols]

display( len(df_house) )
display(df_house.sample(9))

20

13909

,url,place,title,subtitle,price,address,description,ts
2782,https://sevastopol.cian.ru/sale/suburban/29976...,sevastopol,"Дом, 83,6 м², 4 сот.",,10300000,"Севастополь, р-н Гагаринский, Ветерок ДСК садо...","Продается дом 83,6 м² на участке 4 соток Распо...",2024-06-13 11:22:19.008525
5099,https://sevastopol.cian.ru/sale/suburban/26506...,sevastopol,"Дом, 60 м², 1.5 сот., ИЖС",,3450000,"Севастополь, р-н Нахимовский, мкр. Корабельная...","В самом центре Нахимовского района, рядом с ис...",2024-06-07 11:42:40.789431
12716,https://www.avito.ru/3505237140,sevastopol,"Дом 111,4 м² на участке 4,7 сот.",NaN,11300000,"ул. Артиллеристов, 41","Продам, в связи с переездом, дом общей площадь...",2024-06-07 11:52:05.094685
3478,https://sevastopol.cian.ru/sale/suburban/29024...,sevastopol,"Дом, 280 м², 4 сот.",,27000000,"Севастополь, р-н Гагаринский, Казачья Бухта мк...",Дом 280 м² на участке 4 сотки Дом 280 м² на уч...,2024-06-10 11:23:47.056251
780,https://sevastopol.cian.ru/sale/suburban/28807...,sevastopol,"Дом, 260 м², 4 сот., Садоводство",,6497000,"Севастополь, р-н Нахимовский, Нахимовец садово...",Арт. 45199468 Продам недостоенный большой дом....,2024-06-11 10:23:05.308675
5874,https://sevastopol.cian.ru/sale/suburban/28005...,sevastopol,"Дом, 147,1 м², 10.9 сот., Садоводство",,10000000,"Севастополь, р-н Гагаринский, мкр. Фиолент, Пл...",Внимание для ПОКУПАТЕЛЕЙ! Если у Вас есть встр...,2024-06-07 11:42:40.789431
8220,https://www.avito.ru/3927413172,bahchisaray,Дом 50 м² на участке 10 сот.,NaN,4200000,пгт. Куйбышево,Частный дом в районе поссовета пгт. Куйбышево....,2024-06-11 10:50:38.246567
6477,https://www.avito.ru/3334975347,sevastopol,"Дом 215 м² на участке 8,2 сот.",NaN,20000000,ТСН Союз,"Новый и готовый дом, 2019 г постройки, с ремон...",2024-06-13 11:32:06.964835
9013,https://www.avito.ru/3929566827,sevastopol,Дом 118 м² на участке 5 сот.,NaN,9349439,садовое товарищество Скиф,Продажа Дома от Застройщика в Севастополе в Ль...,2024-06-10 11:33:36.811644

In [9]:
# cols = ['title','address','place','url']
# df_house[ (df_house['place']=='sevastopol') & (df_house['address'].str.match(r'.*Судак.*')) ][cols]

In [10]:
from lib.cleaner import CleanerHouse

df_house = CleanerHouse().transform(df_house)

display( len(df_house) )
display(df_house.sample(9))

13909

,url,place,title,subtitle,price,address,description,ts,house_area,is_part,is_townhouse,is_SNT,land_area,priceM,land_size_category,house_size_category
10864,https://www.avito.ru/3589172005,sevastopol,"дом 135 м² на участке 4,5 сот.",NaN,9990000,"садовое товарищество Гавань, ул. Николая Юрков...",Внимание! Просторный одноэтажный дом из ракуше...,2024-06-11 10:41:08.345000,135.0,False,False,True,4.5,9.99,4-8,70-150
8562,https://www.avito.ru/4179345164,sevastopol,"дом 58,1 м² на участке 4,2 сот.",NaN,6150000,"садоводческое товарищество Скиф, 162",Представляю Вашему вниманию замечательный и ую...,2024-06-10 11:33:36.811644,58.1,False,False,True,4.2,6.15,4-8,50-70
793,https://sevastopol.cian.ru/sale/suburban/30299...,sevastopol,"дом, 70 м², 4.08 сот., садоводство",,6500000,"Севастополь, р-н Балаклавский, Медик-88 садово...","Продается одноэтажный дом с ремонтом ""Под ключ...",2024-06-11 10:23:05.308675,70.0,False,False,True,8.0,6.50,4-8,50-70
857,https://sevastopol.cian.ru/sale/suburban/29227...,sevastopol,"дом, 86 м², 16 сот., ижс",,6900000,"Севастополь, р-н Балаклавский, с. Россошанка, ...",Объект 1412. Участок с домом в экологически чи...,2024-06-11 10:23:05.308675,86.0,False,False,False,16.0,6.90,8-20,70-150
8909,https://www.avito.ru/3541633987,sevastopol,дом 100 м² на участке 4 сот.,NaN,4850000,"СТ Технолог, Перламутровая ул.",Горячее предложение: Продается дом в дачном ко...,2024-06-10 11:33:36.811644,100.0,False,False,True,4.0,4.85,2-4,70-150
11680,https://www.avito.ru/3820974276,bahchisaray,"дом 102,9 м² на участке 9,9 сот.",NaN,4700000,садоводческий потребительский кооператив Энтуз...,"Продаётся дом с правом прописки 103 м2, распол...",2024-06-13 11:37:16.726876,102.9,False,False,True,9.9,4.70,8-20,70-150
11582,https://www.avito.ru/3043446454,bahchisaray,"дом 273 м² на участке 12,5 сот.",NaN,22000000,"с. Голубинка, Речная ул., 27",В самом сердце горного Крыма. На расстоянии пр...,2024-06-13 11:37:16.726876,273.0,False,False,False,12.5,22.00,8-20,150-300
5102,https://sevastopol.cian.ru/sale/suburban/30279...,sevastopol,"дом, 54,5 м², 5.31 сот., ижс",,3500000,"Севастополь, р-н Балаклавский, с. Орлиное, ули...",Дом недострой в 2 этажа со статусом жилой на 5...,2024-06-07 11:42:40.789431,54.5,False,False,False,31.0,3.50,20+,50-70
11718,https://www.avito.ru/3657308376,bahchisaray,"дом 53,3 м² на участке 1 сот.",NaN,7400000,Киевский пер.,Продается дом в исторической части города Бахч...,2024-06-13 11:37:16.726876,53.3,False,False,False,1.0,7.40,<1,50-70

---

## обновляем таблицу адресов

In [11]:
# !pip install geopy

In [12]:
from lib.locator import AddressTransformer

atr = AddressTransformer()

places = { 
# поле 'place' и название города
'bahchisaray': 'Бахчисарай,',
      'sudak': 'Судак,',
  'sevastopol': 'Севастополь,',
}

def address_norm(df,atr=atr):
    df['address_orig'] =  df['address']
    df['address'] =  df['address'].apply(atr.transform)
    df['place_'] =  df['place'].map(places)
    df['address'] = df[['address','place_']].apply(lambda d: d[0] if d[1] in d[0] else d[1]+','+d[0],axis=1) 
    df['address'] = (
        df['address']
        .str.replace(', ',',')
        .str.replace(',,',',')
        .str.replace('. ','.')
        .str.replace('\n',' ')
        .str.replace('  ',' ')
        .str.lower()
    )
    return df

In [13]:
df_flat = address_norm(df_flat)
df_land = address_norm(df_land)
df_house = address_norm(df_house)

/tmp/ipykernel_1028882/776805188.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['address'] = df[['address','place_']].apply(lambda d: d[0] if d[1] in d[0] else d[1]+','+d[0],axis=1)
/tmp/ipykernel_1028882/776805188.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['address'] = df[['address','place_']].apply(lambda d: d[0] if d[1] in d[0] else d[1]+','+d[0],axis=1)
/tmp/ipykernel_1028882/776805188.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['address'] = df[['address','place_']].apply(lambda d: d[0] if d[1] in d[0] else d[1]+','+d[0],axis=1)

In [14]:
# df_flat[['address','address_orig']]

In [15]:
address = pd.concat([
        df_flat[['address','address_orig']],
        df_land[['address','address_orig']],
        df_house[['address','address_orig']],
    ]).drop_duplicates(['address']).reset_index(drop=True)

display(len(address))
display(address.sample(5))

8218

,address,address_orig
6510,"севастополь,р-н балаклавский,гераклея садовое ...","Севастополь, р-н Балаклавский, Гераклея садово..."
5002,"севастополь,пушкарский пер.,14","Пушкарский пер., 14"
6062,"севастополь,р-н нахимовский,берег садовое това...","Севастополь, р-н Нахимовский, Берег садовое то..."
3468,"севастополь,р-н балаклавский,улица второй обор...","Севастополь, р-н Балаклавский, улица Второй Об..."
3332,"севастополь,р-н нахимовский,улица ясеневая,67","Севастополь, р-н Нахимовский, улица Ясеневая, 67"

In [16]:
from os.path import exists as path_exists
loc_file_path = 'data/location.pkl' # таблица адресов

location = pd.DataFrame([],columns=['address','latitude','longitude',])
if path_exists( loc_file_path ):
    location = pd.read_pickle(loc_file_path).drop_duplicates(['address']).reset_index(drop=True)
    
display(len(location))
display(location.sample(5))

15524

                                                address   latitude  longitude
6382  севастополь,р-н нахимовский,мкр.северная сторо...  44.629473  33.538682
4960  севастополь,р-н гагаринский,мкр.омега,набережн...  44.603134  33.435133
566                      бахчисарай,севастопольская ул.  44.752096  33.865031
6381  севастополь,р-н нахимовский,мкр.северная сторо...  44.630307  33.561733
2739              севастополь,монастырское шоссе,116/34  44.512798  33.505561

---

In [17]:
# def address_norm_(df):
#     df['address_orig'] =  df['address']
#     # df['address'] =  df['address'].apply(atr.transform)
#     df['address'] = (
#         df['address']
#         .str.replace(', ',',')
#         .str.replace(',,',',')
#         .str.replace('. ','.')
#         .str.replace('\n',' ')
#         .str.replace('  ',' ')
#         .str.lower()
#     )
#     return df

In [18]:
# location = address_norm_(location)

In [19]:
# location = location[['address','latitude','longitude']]

---

In [20]:
# собираем все адреса в один список
location = location.merge(
        address[['address']].drop_duplicates(),
        how='outer',
        on='address',
    ).drop_duplicates(['address']).reset_index(drop=True)

display(len(location))
display(location.sample(5))

15718

                                              address   latitude  longitude
14857               севастополь,улица хрусталёва,167д  44.553485  33.527642
12606                севастополь,ул.2-я линия,106/265  44.679654  33.561589
3689       севастополь,проспект героев сталинграда,39  44.589636  33.443568
12321                     севастополь,тсн родник,30/3   44.54471  33.556118
5845   севастополь,р-н гагаринский,шоссе камышовое,33  44.552039  33.490694

In [21]:
display(len(location))
display(location['latitude'].isnull().sum())

15718

194

In [22]:
# собираем все адреса с геопозицией
location_def = location[~location['latitude'].isna()].reset_index(drop=True)
display(len(location_def))

# собираем все адреса без геопозиции
location_undef = location[location['latitude'].isna()][['address']].reset_index(drop=True)
display(len(location_undef))

15524

194

In [32]:
display(location_undef)

                                       address  longitude   latitude
0          бахчисарай,с.красный мак,лесная ул.  33.776816  44.635612
1         бахчисарай,с.кудрино,прогонная ул.,9   33.94437   44.70451
2          бахчисарай,с.танковое,подлесная ул.  33.810494  44.658506
3    бахчисарай,с.холмовка,комсомольская ул.,2  33.756811  44.654941
4         бахчисарай,с.холмовка,рабочая ул.,11  33.757664  44.655082
..                                         ...        ...        ...
189    судак,с.миндальное,ул.никитская слобода  35.048103  44.840773
190                      судак,санаторный пер.  34.971288  44.846691
191                       судак,ул.бака-таш,16  34.980595   44.84471
192                          судак,ул.нахимова  34.970076  44.846346
193                   судак,яблоневая улица ,4  34.977082  44.853395

[194 rows x 3 columns]

In [23]:
from tqdm.auto import tqdm
tqdm.pandas()

In [24]:
# from lib.locator import GeocoderSimpleOSM
from lib.locator import GeocoderYandex
from yandex_keys import keys

atr = AddressTransformer()
locator = GeocoderYandex(keys[0])
# locator = GeocoderSimpleOSM()

if len(location_undef)>0:
    # определяем координаты по строке адреса
    location_undef = location_undef.join( 
            location_undef['address'].progress_apply(locator.transform).apply(pd.Series) 
        ).dropna()     
    display(f'LocationUpdater: {len(location_undef)} new addresses found')
    location = pd.concat([location_def,location_undef]).reset_index(drop=True) 
    assert len(location)>0
    # location.to_pickle(loc_file_path)

  0%|          | 0/194 [00:00<?, ?it/s]

'LocationUpdater: 194 new addresses found'

In [25]:
display( len(location) )
display( location.sample(3) )

15718

                                                 address   latitude  longitude
14814                      севастополь,улица шабалина,24  44.573214  33.497881
3596           севастополь,проспект генерала острякова,3  44.585072   33.51847
5122   севастополь,р-н гагаринский,мкр.стрелецкая бух...   44.59619  33.478234

In [26]:
assert len(location)>0
location.to_pickle(loc_file_path)

## дополняем данные геометкой

In [27]:
display( len(df_flat) )
df_flat  = df_flat.merge(location,on='address').reset_index(drop=True) 
display( len(df_flat) )
display( df_flat.sample(3) )

16906

16906

,url,place,title,subtitle,price,address,description,ts,nrooms,floor,...,is_auction,is_openspace,is_roof,is_SNT,priceM,is_last_floor,address_orig,place_,latitude,longitude
10540,https://www.avito.ru/3945378606,sevastopol,"1-к. квартира, 30 м², 1/5 эт.",NaN,5400000,"севастополь,улица маршала геловани,2",Продам 1-комнатную квартиру в Ленинском районе...,2024-06-11 10:25:30.856703,1,1,...,False,False,False,False,5.400,False,"улица Маршала Геловани, 2","Севастополь,",44.572738,33.524255
7242,https://www.avito.ru/3813688928,sudak,"1-к. квартира, 35,4 м², 8/9 эт.",NaN,6369000,"судак,комплекс апартаментов «бирюзовый квартал...","Ипотека от 11,5% платеж от 26 000р. Кладовка В...",2024-06-13 11:33:20.210428,1,8,...,False,False,False,False,6.369,False,Комплекс апартаментов «Бирюзовый квартал»\n ул...,"Судак,",44.851593,34.969177
7727,https://www.avito.ru/3813839589,sudak,"1-к. квартира, 32,7 м², 8/9 эт.",NaN,5879000,"судак,комплекс апартаментов «бирюзовый квартал...","Ипотека от 11,5% платеж от 26 000р. Кладовка В...",2024-06-11 10:42:36.408387,1,8,...,False,False,False,False,5.879,False,Комплекс апартаментов «Бирюзовый квартал»\n ул...,"Судак,",44.851593,34.969177

In [28]:
display( len(df_land) )
df_land  = df_land.merge(location,on='address').reset_index(drop=True) 
display( len(df_land) )
display( df_land.sample(3) )

14209

14209

,url,place,title,subtitle,price,address,description,ts,area,is_IJS,priceM,priceMU,area_size_category,address_orig,place_,latitude,longitude
12661,https://www.avito.ru/3803494308,sevastopol,"участок 17 сот. (снт, днп)",NaN,2200000,"севастополь,весенняя ул.",Лот № 73930. Предлагаем к продаже земельный уч...,2024-06-11 10:32:52.971878,17.00,False,2.20,0.129412,8-20,Весенняя ул.,"Севастополь,",44.639268,33.555139
4176,https://sevastopol.cian.ru/sale/suburban/30279...,sevastopol,"участок, 5 сот., садоводство",,1600000,"севастополь,р-н нахимовский,качинский район ,п...",Продам ВИДОВОЙ участок 5 соток у самого побере...,2024-06-10 11:18:48.884876,5.00,False,1.60,0.320000,4-8,"Севастополь, р-н Нахимовский, Качинский муници...","Севастополь,",44.789825,33.542176
3044,https://sevastopol.cian.ru/sale/suburban/29946...,sevastopol,"участок 5,67 соток ижс","Участок, 5.67 сот., ИЖС",2850000,"севастополь,р-н балаклавский,автомобилист садо...","Участок 5,67 соток (ИЖС) в г. Севастополь, Бал...",2024-06-13 11:16:11.805581,5.67,True,2.85,0.502646,4-8,"Севастополь, р-н Балаклавский, Автомобилист са...","Севастополь,",44.513126,33.503378

In [29]:
display( len(df_house) )
df_house = df_house.merge(location,on='address').reset_index(drop=True) 
display( len(df_house) )
display( df_house.sample(3) )

13909

13909

,url,place,title,subtitle,price,address,description,ts,house_area,is_part,is_townhouse,is_SNT,land_area,priceM,land_size_category,house_size_category,address_orig,place_,latitude,longitude
10917,https://www.avito.ru/3997559983,sevastopol,"дом 115 м² на участке 4,8 сот.",NaN,11500000,"севастополь,садоводческое товарищество интерна...",Спешите приобрести дом мечты в ипотеку под 8 п...,2024-06-11 10:41:08.345000,115.0,False,False,True,4.8,11.5,4-8,70-150,"садоводческое товарищество Интернационалист, 95","Севастополь,",44.540039,33.467859
3783,https://sevastopol.cian.ru/sale/suburban/30057...,sevastopol,"дом, 90 м², 4 сот., садоводство",,6300000,"севастополь,р-н гагаринский,фрегат садоводческ...",Не упустите шанс купить дом по хорошей цене! П...,2024-06-10 11:23:47.056251,90.0,False,False,True,4.0,6.3,2-4,70-150,"Севастополь, р-н Гагаринский, Фрегат садоводче...","Севастополь,",44.536473,33.492248
9947,https://www.avito.ru/3836648290,sevastopol,дом 215 м² на участке 6 сот.,NaN,12500000,"севастополь,садоводческое товарищество рассвет...",Готов рассмотреть вариант обмена. Предлагайте ...,2024-06-11 10:41:08.345000,215.0,False,False,True,6.0,12.5,4-8,150-300,"садоводческое товарищество Рассвет-3, 127","Севастополь,",44.535876,33.464418

In [30]:
assert len(df_flat)>0
df_flat.to_pickle(f'{data_root_folder}/df_flat.pkl')

assert len(df_land)>0
df_land.to_pickle(f'{data_root_folder}/df_land.pkl')

assert len(df_house)>0
df_house.to_pickle(f'{data_root_folder}/df_house.pkl')

In [31]:
!date

Чт 13 июн 2024 11:41:02 MSK