In [1]:
from os import listdir
import re
import pandas as pd

In [2]:
data_root_folder = 'data/2024'
source = {
         'flat':[data_root_folder+'/raw/flat/cian',data_root_folder+'/raw/flat/avito'],
        'house':[data_root_folder+'/raw/house/cian',data_root_folder+'/raw/house/avito'],
         'land':[data_root_folder+'/raw/land/cian',data_root_folder+'/raw/land/avito'],
    }

---

In [3]:
obj_type = 'flat'
files = [ f'{d}/{f}' for d in source[obj_type] for f in listdir(d) if f[-4:]=='.pkl' ]
display( len(files) )

cols = ['url','place','title','subtitle','price','address','description','ts',]

df_flat = pd.concat([
        pd.read_pickle(f).drop_duplicates(['url'])
        for f in files
    ]).reset_index(drop=True)[cols]

display( len(df_flat) )
display(df_flat.sample(9))

12

12708

,url,place,title,subtitle,price,address,description,ts
3480,https://sevastopol.cian.ru/sale/flat/299735823/,sevastopol,"4-комн. квартира, 78,8 м², 1/3 этаж",,12800000,"Севастополь, р-н Балаклавский, мкр. Балаклава,...","Четырехкомнатная квартира 78,8 м2, на 1/3 этаж...",2024-06-10 11:06:41.395615
2911,https://sevastopol.cian.ru/sale/flat/302448680/,sevastopol,"1-комн. квартира, 36 м², 5/9 этаж",,5990000,"Севастополь, р-н Гагаринский, мкр. Летчики, пр...",Объект 3259. Продается однокомнатная квартира ...,2024-06-11 10:13:23.305322
12669,https://www.avito.ru/3625042720,sevastopol,"Квартира-студия, 27,5 м², 2/9 эт.",NaN,4867500,"ЖК «Доброгород»\nул. Токарева, 8 этап, блок 3","Доступна ипотека! Ипотека с господдержкой, вое...",2024-06-10 11:17:35.151941
9365,https://www.avito.ru/2967875754,sevastopol,"5-к. квартира, 105 м², 2/3 эт.",NaN,15000000,"Восточная ул., 16А/6","Хотите купить не только дом своей мечты, но и ...",2024-06-11 10:25:30.856703
6442,https://www.avito.ru/3985289034,sevastopol,"1-к. квартира, 49 м², 1/5 эт.",NaN,6000000,"пр-т Генерала Острякова, 174",Предлагается к продаже 1 к квартира расположен...,2024-06-07 11:27:07.236636
5689,https://www.avito.ru/3614557742,sudak,"1-к. квартира, 39,8 м², 4/8 эт.",NaN,9333859,"ЖК «Долина Роз»\nкв-л Долина роз, 1 оч.","Продается квартира общей площадью 39,81 м2 в к...",2024-06-10 11:35:05.787844
6497,https://www.avito.ru/2121191708,sevastopol,"1-к. квартира, 32 м², 9/9 эт.",NaN,5900000,"пр-т Октябрьской Революции, 40/1","Уютная, теплая квартира. Однокомнатная квартир...",2024-06-07 11:27:07.236636
7301,https://www.avito.ru/3965505387,sevastopol,"2-к. квартира, 63 м², 3/10 эт.",NaN,14500000,"Парковая ул., 29","Квартира на Парковой, лучшее местоположение го...",2024-06-07 11:27:07.236636
9437,https://www.avito.ru/3831807966,sevastopol,"1-к. апартаменты, 24,8 м², 1/4 эт.",NaN,5200000,"ул. Челюскинцев, 49/4","В Продаже Весь Апарт Комплекс! От 24.8 до 42,2...",2024-06-11 10:25:30.856703

In [4]:
from lib.cleaner import CleanerFlat

df_flat = CleanerFlat().transform(df_flat)
display( len(df_flat) )
display(df_flat.sample(9))

12708

,url,place,title,subtitle,price,address,description,ts,nrooms,floor,...,area,is_studio,is_apartment,is_part,is_auction,is_openspace,is_roof,is_SNT,priceM,is_last_floor
11453,https://www.avito.ru/3945263234,sevastopol,"2-к. квартира, 51,3 м², 5/12 эт.",NaN,11500000,"улица Адмирала Юмашева, 14","Двухкомнатная квартира 51,3 м2 на 5/12 этаже д...",2024-06-10 11:17:35.151941,2,5,...,51.30,False,False,False,False,False,False,False,11.5000,False
3511,https://sevastopol.cian.ru/sale/flat/299736765/,sevastopol,"3-комн. квартира, 42,77 м², 2/4 этаж",,6400000,"Севастополь, р-н Ленинский, мкр. Матюшенко, ул...","Трехкомнатная квартира 42,77 м2, на 2/4 этаже ...",2024-06-10 11:06:41.395615,0,2,...,42.77,False,False,False,False,False,False,False,6.4000,False
1865,https://sevastopol.cian.ru/sale/flat/301969016/,sevastopol,"1-к кв., 32,4 кв.м, 5/5 эт.","1-комн. квартира, 32,4 м², 5/5 этаж",6000000,"Севастополь, р-н Ленинский, улица Мечникова, 5",Арт. 64091994 Предлагается к покупке однокомна...,2024-06-11 10:13:23.305322,0,5,...,0.00,False,False,False,False,False,False,False,6.0000,True
10057,https://www.avito.ru/3657294343,sevastopol,"3-к. квартира, 49,7 м², 2/4 эт.",NaN,8600000,"улица Адмирала Октябрьского, 9",Продаю 3-хкомнатную квартиру в центральной час...,2024-06-11 10:25:30.856703,3,2,...,49.70,False,False,False,False,False,False,False,8.6000,False
11729,https://www.avito.ru/3370916323,sevastopol,"3-к. квартира, 63,8 м², 5/5 эт.",NaN,9000000,"улица Хрусталёва, 75",Объект №1241. Продам 3-х комнатную квартиру «Ч...,2024-06-10 11:17:35.151941,3,5,...,63.80,False,False,False,False,False,False,False,9.0000,True
1744,https://sevastopol.cian.ru/sale/flat/298638790/,sevastopol,"2-комн. квартира, 63,21 м², 8/9 этаж",Секция 3 • Сдача корпуса 4 кв. 2024,8880000,"Севастополь, р-н Гагаринский, улица Братьев Ма...",,2024-06-11 10:13:23.305322,0,8,...,63.21,False,False,False,False,False,False,False,8.8800,False
2913,https://sevastopol.cian.ru/sale/flat/301573087/,sevastopol,"2-комн. квартира, 29,6 м², 1/2 этаж",,5975000,"Севастополь, р-н Нахимовский, мкр. Северная ст...",Объект 16788. Предлагается к продаже двухкомна...,2024-06-11 10:13:23.305322,0,1,...,29.60,False,False,False,False,False,False,False,5.9750,False
4313,https://sevastopol.cian.ru/sale/flat/302591475/,sevastopol,"2-комн. квартира, 43 м², 2/2 этаж",,4900000,"Севастополь, р-н Нахимовский, улица Мореходная...",Продаю квартиру-студию в клубном доме город Се...,2024-06-10 11:06:41.395615,0,2,...,43.00,False,False,False,False,False,False,False,4.9000,True
4482,https://sevastopol.cian.ru/sale/flat/302327733/,sevastopol,"2-комн. квартира, 43,2 м², 4/4 этаж",,5699900,"Севастополь, р-н Нахимовский, мкр. Горпищенко,...",Продается 2к квартира на ул. Горпищенко 86. 4 ...,2024-06-10 11:06:41.395615,0,4,...,43.20,False,False,False,False,False,False,False,5.6999,True

---

In [5]:
obj_type = 'land'
files = [ f'{d}/{f}' for d in source[obj_type] for f in listdir(d) if f[-4:]=='.pkl' ]
display( len(files) )

cols = ['url','place','title','subtitle','price','address','description','ts',]

df_land = pd.concat([
        pd.read_pickle(f).drop_duplicates(['url'])
        for f in files
    ]).reset_index(drop=True)[cols]

display( len(df_land) )
display(df_land.sample(9))

15

11379

,url,place,title,subtitle,price,address,description,ts
8589,https://www.avito.ru/3240584594,sevastopol,"Участок 4 сот. (СНТ, ДНП)",NaN,1600000,садоводческое товарищество Гераклея,"Если нет связи, пишите, пожалуйста в личные со...",2024-06-11 10:32:52.971878
560,https://sevastopol.cian.ru/sale/suburban/30266...,sevastopol,"Участок, 6 сот., ИЖС",,1899000,"Севастополь, р-н Нахимовский, мкр. Северная ст...","Продам участок квадратной правильной формы, ра...",2024-06-11 10:17:41.455159
10327,https://www.avito.ru/1987285198,sevastopol,Участок 10 сот. (ИЖС),NaN,4000000,"ул. Лётчика Мусатова, 36",Срочно цена актуальна до конца месяца! Продает...,2024-06-07 11:38:45.101812
1004,https://sevastopol.cian.ru/sale/suburban/30194...,sevastopol,"Участок, 5.88 сот., Садоводство",,3200000,"Севастополь, р-н Гагаринский, Интеграл садовод...",Арт. 65498302 Участок можно приобрести в ипоте...,2024-06-11 10:17:41.455159
10196,https://www.avito.ru/4121637376,sevastopol,Участок 4 сот. (ИЖС),NaN,2600000,садоводческое товарищество Подорожник,"Продам собственный участок 4,04 сот. В СТ «Под...",2024-06-07 11:38:45.101812
4204,https://sevastopol.cian.ru/sale/suburban/29863...,sevastopol,"Участок, 4.5 сот., Садоводство",,3300000,"Севастополь, р-н Гагаринский, Интеграл садовод...","Продаётся земельный участок в ТСН ""Интеграл"". ...",2024-06-10 11:18:48.884876
10943,https://www.avito.ru/3941160881,sevastopol,"Участок 7,7 сот. (СНТ, ДНП)",NaN,7710000,"СТ Здоровье, 32",*Продается земельный участок в СТ «Здоровье»! ...,2024-06-07 11:38:45.101812
5516,https://www.avito.ru/4418491045,sevastopol,Участок 8 сот. (ИЖС),NaN,2800000,ул. Комиссара Ищенко,Объект №145. Участок 8 соток (Ижс) в г. Севаст...,2024-06-10 11:25:16.532576
7514,https://www.avito.ru/2476228379,bahchisaray,"Участок 5,91 га (СНТ, ДНП)",NaN,5000000,с. Тургеневка,"Продам пай 6 га(591 сотка), часть известного л...",2024-06-10 11:38:42.490270

In [6]:
from lib.cleaner import CleanerLand

df_land = CleanerLand().transform(df_land)

display( len(df_land) )
display(df_land.sample(9))

11379

,url,place,title,subtitle,price,address,description,ts,area,is_IJS,priceM,priceMU,area_size_category
5614,https://www.avito.ru/3589253322,sevastopol,участок 8 сот. (ижс),NaN,8700000,"1-й Планерный пер., 11",Пpeдлагaeтся к пpoдаже земельный учaстoк по ад...,2024-06-10 11:25:16.532576,8.0,True,8.700,1.087500,4-8
7301,https://www.avito.ru/2853725029,bahchisaray,"участок 2,52 га (снт, днп)",NaN,800000,"Республика Крым, Бахчисарайский район, Вилинск...",Продаётся земельный пай сельхозназначения. Пло...,2024-06-10 11:38:42.490270,252.0,False,0.800,0.003175,20+
2315,https://sevastopol.cian.ru/sale/suburban/30098...,sevastopol,"участок, 4.05 сот., садоводство",,2699000,"Севастополь, р-н Гагаринский, Клеры-3 СНТ, 109",Продается земельный участок: СНТ Клеры-3. Кате...,2024-06-07 11:37:10.690720,5.0,False,2.699,0.539800,4-8
1055,https://sevastopol.cian.ru/sale/suburban/30256...,sevastopol,"участок, 4.41 сот., садоводство",,3300000,"Севастополь, р-н Балаклавский, Мидэус садовое ...",,2024-06-11 10:17:41.455159,41.0,False,3.300,0.080488,20+
9343,https://www.avito.ru/3534883709,sevastopol,участок 6 сот. (ижс),NaN,3000000,Фёдоровская ул.,Продам Видовой земельный участок Ижс. Вид на М...,2024-06-11 10:32:52.971878,6.0,True,3.000,0.500000,4-8
2072,https://sevastopol.cian.ru/sale/suburban/30229...,sevastopol,"участок, 9.8 сот., ижс",,2000000,"Севастополь, р-н Балаклавский, с. Штурмовое, у...",Объект 1147. Участок 9.83 сотки (ИЖС) располож...,2024-06-07 11:37:10.690720,8.0,True,2.000,0.250000,4-8
2950,https://krym.cian.ru/sale/suburban/302159927/,sudak,"участок, 1 сот.",,500000,"Республика Крым, Судак, Энергетиков кв-л","Уникальный участок 100 кв.м. в г. Судак, кварт...",2024-06-10 11:24:54.355096,1.0,False,0.500,0.500000,<1
11023,https://www.avito.ru/3945322565,sevastopol,"участок 8,5 сот. (снт, днп)",NaN,5100000,садовое товарищество Чайка-1,Уникальное предложение по своим параметрам! Уч...,2024-06-07 11:38:45.101812,8.5,False,5.100,0.600000,8-20
11,https://sevastopol.cian.ru/sale/suburban/29540...,sevastopol,"участок, 5.6 сот., ижс",,6300000,"Севастополь, р-н Гагаринский, Казачья Бухта мк...","Участок 5,6 соток ИЖС Участок 5,6 соток (ИЖС) ...",2024-06-11 10:17:41.455159,6.0,True,6.300,1.050000,4-8

---

In [7]:
obj_type = 'house'
files = [ f'{d}/{f}' for d in source[obj_type] for f in listdir(d) if f[-4:]=='.pkl' ]
display( len(files) )

cols = ['url','place','title','subtitle','price','address','description','ts',]

df_house = pd.concat([
        pd.read_pickle(f).drop_duplicates(['url'])
        for f in files
    ]).reset_index(drop=True)[cols]

display( len(df_house) )
display(df_house.sample(9))

15

10402

,url,place,title,subtitle,price,address,description,ts
10064,https://www.avito.ru/3798249491,sevastopol,Дом 112 м² на участке 4 сот.,NaN,9900000,садоводческое товарищество Старый Фиолент,"Предлагаем новый жилой дом, общей площадью 112...",2024-06-07 11:52:05.094685
4582,https://krym.cian.ru/sale/suburban/268730311/,sudak,"Дом, 50 м², 8 сот., ИЖС",,12400000,"Республика Крым, Судак, улица Спендиарова, 69","На участке есть хоз. постройке: гараж, сарай, ...",2024-06-11 10:24:26.015453
5804,https://www.avito.ru/3115099821,sevastopol,Дом 90 м² на участке 6 сот.,NaN,7350000,"садоводческое товарищество Гераклея, 243",Продам дом в г. Севастополе СТ Гераклея. С шик...,2024-06-10 11:33:36.811644
5756,https://www.avito.ru/1328316585,sevastopol,Коттедж 177 м² на участке 1 сот.,NaN,5000000,"с. Угловое, ул. Комарова","Продам дом (по документам гараж), можно исполь...",2024-06-10 11:33:36.811644
2683,https://sevastopol.cian.ru/sale/suburban/30280...,sevastopol,"Дом, 114 м², 4.24 сот., Садоводство",,9000000,"Севастополь, р-н Балаклавский, с. Кизиловое, п...",Продам каркасный дом в самом экологично чистом...,2024-06-10 11:23:47.056251
9402,https://www.avito.ru/3861434452,sevastopol,Дом 263 м² на участке 6 сот.,NaN,16500000,"ул. Генерала Саймонова, 45",Дом 230 кв. М. Из Лстк (лёгкие стальные тонкос...,2024-06-07 11:52:05.094685
5381,https://www.avito.ru/3805659797,sevastopol,"Дом 113 м² на участке 4,2 сот.",NaN,8000000,"СОТ Южный, 254",Возможен Торг! Продаётся одноэтажный дом в пеш...,2024-06-10 11:33:36.811644
5334,https://www.avito.ru/4102371070,sevastopol,"Дом 94 м² на участке 1,7 сот.",NaN,11990000,"ул. Мельникова, 44","Продается коттедж 94,4 м². Элитный ЖК «Зeлёный...",2024-06-10 11:33:36.811644
1356,https://sevastopol.cian.ru/sale/suburban/30149...,sevastopol,"Дом, 140 м², 5.3 сот., Садоводство",,10800000,"Севастополь, р-н Гагаринский, мкр. Фиолент, Ге...",Продаётся дом общей площадью 140 м2 на участке...,2024-06-11 10:23:05.308675

In [8]:
# cols = ['title','address','place','url']
# df_house[ (df_house['place']=='sevastopol') & (df_house['address'].str.match(r'.*Судак.*')) ][cols]

In [9]:
from lib.cleaner import CleanerHouse

df_house = CleanerHouse().transform(df_house)

display( len(df_house) )
display(df_house.sample(9))

10402

,url,place,title,subtitle,price,address,description,ts,house_area,is_part,is_townhouse,is_SNT,land_area,priceM,land_size_category,house_size_category
7985,https://www.avito.ru/3359934606,sevastopol,"дом 80 м² на участке 5,3 сот.",NaN,6400000,"СТСН Южный Экспресс, 71","Дом 80 м² на участке 5,3 сотки. Дом 80 м² на у...",2024-06-11 10:41:08.345000,80.0,False,False,True,5.3,6.40,4-8,70-150
7074,https://www.avito.ru/2512827704,sevastopol,дом 157 м² на участке 4 сот.,NaN,14000000,"Муромская ул., 138","Арт. 31435576. Продам новый, современный жилой...",2024-06-11 10:41:08.345000,157.0,False,False,False,4.0,14.00,2-4,150-300
7,https://sevastopol.cian.ru/sale/suburban/29293...,sevastopol,"дом, 189,2 м², 5 сот., садоводство",,11500000,"Севастополь, р-н Балаклавский, шоссе Монастырское",Продаю просторный дом более 190 кв.м. в Севаст...,2024-06-11 10:23:05.308675,189.2,False,False,False,5.0,11.50,4-8,150-300
4067,https://sevastopol.cian.ru/sale/suburban/30157...,sevastopol,"дом, 73 м², 4.1 сот., садоводство",,7730000,"Севастополь, р-н Нахимовский, Чайка-1 садовое ...",Объект 9165. Продается новый дом 73 квадратных...,2024-06-07 11:42:40.789431,73.0,False,False,True,1.0,7.73,<1,70-150
8484,https://www.avito.ru/4121665045,bahchisaray,дом 25 м² на участке 9 сот.,NaN,2350000,садоводческий потребительский кооператив Энтуз...,В продаже уютный домик в непосредственной близ...,2024-06-10 11:39:39.442400,25.0,False,False,True,9.0,2.35,8-20,<30
4896,https://www.avito.ru/3007785996,bahchisaray,"дом 114,4 м² на участке 25 сот.",NaN,9000000,"с. Высокое, Куйбышевская ул., 12",Продам дом 114.40 кв. М. На земельном участке ...,2024-06-07 12:10:08.505306,114.4,False,False,False,25.0,9.00,20+,70-150
9716,https://www.avito.ru/3110959162,sevastopol,дом 152 м² на участке 10 сот.,NaN,5000000,"Тюбекская ул., 4",Дом у моря в тихом месте! Дом находится на зап...,2024-06-07 11:52:05.094685,152.0,True,False,False,10.0,5.00,8-20,150-300
4911,https://www.avito.ru/3178724696,bahchisaray,"дом 167 м² на участке 6,6 сот.",NaN,5950000,"с. Голубинка, Набережная ул., 8","Продается 2-ух этажный жилой дом 167 кв. М, на...",2024-06-07 12:10:08.505306,167.0,False,False,False,6.6,5.95,4-8,150-300
9665,https://www.avito.ru/3728689549,sevastopol,"дом 113,8 м² на участке 4 сот.",NaN,8000000,"садоводческое товарищество Полюшко-2, 87","Объект №134. Предлагаю приобрести дом 113,8 м....",2024-06-07 11:52:05.094685,113.8,False,False,True,4.0,8.00,2-4,70-150

---

## обновляем таблицу адресов

In [10]:
# !pip install geopy

In [11]:
from lib.locator import AddressTransformer

atr = AddressTransformer()

places = { 
# поле 'place' и название города
'bahchisaray': 'Бахчисарай,',
      'sudak': 'Судак,',
  'sevastopol': 'Севастополь,',
}

def address_norm(df,atr=atr):
    df['address_orig'] =  df['address']
    df['address'] =  df['address'].apply(atr.transform)
    df['place_'] =  df['place'].map(places)
    df['address'] = df[['address','place_']].apply(lambda d: d[0] if d[1] in d[0] else d[1]+','+d[0],axis=1) 
    df['address'] = (
        df['address']
        .str.replace(', ',',')
        .str.replace(',,',',')
        .str.replace('. ','.')
        .str.replace('\n',' ')
        .str.replace('  ',' ')
        .str.lower()
    )
    return df

In [12]:
df_flat = address_norm(df_flat)
df_land = address_norm(df_land)
df_house = address_norm(df_house)

/tmp/ipykernel_575929/776805188.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['address'] = df[['address','place_']].apply(lambda d: d[0] if d[1] in d[0] else d[1]+','+d[0],axis=1)
/tmp/ipykernel_575929/776805188.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['address'] = df[['address','place_']].apply(lambda d: d[0] if d[1] in d[0] else d[1]+','+d[0],axis=1)
/tmp/ipykernel_575929/776805188.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['address'] = df[['address','place_']].apply(lambda d: d[0] if d[1] in d[0] else d[1]+','+d[0],axis=1)

In [13]:
# df_flat[['address','address_orig']]

In [14]:
address = pd.concat([
        df_flat[['address','address_orig']],
        df_land[['address','address_orig']],
        df_house[['address','address_orig']],
    ]).drop_duplicates(['address']).reset_index(drop=True)

display(len(address))
display(address.sample(5))

7914

,address,address_orig
5685,"севастополь,р-н ленинский,тополек садовое това...","Севастополь, р-н Ленинский, Тополек садовое то..."
502,"севастополь,р-н гагаринский,мкр.стрелецкая бух...","Севастополь, р-н Гагаринский, мкр. Стрелецкая ..."
5645,"севастополь,р-н балаклавский,с.кизиловое,улица...","Севастополь, р-н Балаклавский, с. Кизиловое, у..."
4055,"севастополь,садоводческое товарищество фрегат,127","садоводческое товарищество Фрегат, 127"
6917,"севастополь,ул.горпищенко,153/9","ул. Горпищенко, 153/9"

In [15]:
from os.path import exists as path_exists
loc_file_path = 'data/location.pkl' # таблица адресов

location = pd.DataFrame([],columns=['address','latitude','longitude',])
if path_exists( loc_file_path ):
    location = pd.read_pickle(loc_file_path).drop_duplicates(['address']).reset_index(drop=True)
    
display(len(location))
display(location.sample(5))

15317

                                                 address   latitude  longitude
13891                        севастополь,улица ленина,36  44.609629  33.526231
6617   севастополь,р-н нахимовский,сапун-гора снт,ули...  44.568526  33.569656
5294   севастополь,р-н гагаринский,мкр.фиолент,планер...  44.529887  33.465155
471                   бахчисарай,с.танковое,ул.ленина,48  44.660981  33.812345
7313   севастополь,район гагаринский,летчики,улица ад...  44.595073  33.465065

---

In [16]:
# def address_norm_(df):
#     df['address_orig'] =  df['address']
#     # df['address'] =  df['address'].apply(atr.transform)
#     df['address'] = (
#         df['address']
#         .str.replace(', ',',')
#         .str.replace(',,',',')
#         .str.replace('. ','.')
#         .str.replace('\n',' ')
#         .str.replace('  ',' ')
#         .str.lower()
#     )
#     return df

In [17]:
# location = address_norm_(location)

In [18]:
# location = location[['address','latitude','longitude']]

---

In [19]:
# собираем все адреса в один список
location = location.merge(
        address[['address']].drop_duplicates(),
        how='outer',
        on='address',
    ).drop_duplicates(['address']).reset_index(drop=True)

display(len(location))
display(location.sample(5))

15524

                                                 address   latitude  longitude
5884   севастополь,р-н ленинский,мкр.острякова,проспе...  44.579525  33.517634
15175                        судак,партизанская улица ,9  44.849497  34.977226
9391   севастополь,садоводческое некоммерческое товар...  44.527837  33.510376
2236                 севастополь,кача,улица авиаторов,19  44.775782  33.542176
8651                      севастополь,редутная улица ,31   44.58201  33.573555

In [20]:
display(len(location))
display(location['latitude'].isnull().sum())

15524

207

In [21]:
# собираем все адреса с геопозицией
location_def = location[~location['latitude'].isna()].reset_index(drop=True)
display(len(location_def))

# собираем все адреса без геопозиции
location_undef = location[location['latitude'].isna()][['address']].reset_index(drop=True)
display(len(location_undef))

15317

207

In [22]:
from tqdm.auto import tqdm
tqdm.pandas()

In [23]:
# from lib.locator import GeocoderSimpleOSM
from lib.locator import GeocoderYandex
from yandex_keys import keys

atr = AddressTransformer()
locator = GeocoderYandex(keys[0])
# locator = GeocoderSimpleOSM()

if len(location_undef)>0:
    # определяем координаты по строке адреса
    location_undef = location_undef.join( 
            location_undef['address'].progress_apply(locator.transform).apply(pd.Series) 
        ).dropna()     
    display(f'LocationUpdater: {len(location_undef)} new addresses found')
    location = pd.concat([location_def,location_undef]).reset_index(drop=True) 
    assert len(location)>0
    # location.to_pickle(loc_file_path)

  0%|          | 0/207 [00:00<?, ?it/s]

'LocationUpdater: 207 new addresses found'

In [24]:
display( len(location) )
display( location.sample(3) )

15524

                                                address   latitude  longitude
7407  севастополь,район гагаринский,омега,проспект а...  44.588949  33.432169
8307  севастополь,район нахимовский,победа,улица ген...  44.588006   33.55425
1075                  севастополь,античный проспект ,68  44.588526  33.431432

In [25]:
assert len(location)>0
location.to_pickle(loc_file_path)

## дополняем данные геометкой

In [26]:
display( len(df_flat) )
df_flat  = df_flat.merge(location,on='address').reset_index(drop=True) 
display( len(df_flat) )
display( df_flat.sample(3) )

12708

12708

,url,place,title,subtitle,price,address,description,ts,nrooms,floor,...,is_auction,is_openspace,is_roof,is_SNT,priceM,is_last_floor,address_orig,place_,latitude,longitude
11195,https://www.avito.ru/3679632002,sevastopol,"1-к. квартира, 32,7 м², 3/5 эт.",NaN,4950000,"севастополь,улица лизы чайкиной,97",Предлагаю к продаже однокомнатную квартиру в Г...,2024-06-10 11:17:35.151941,1,3,...,False,False,False,False,4.9500,False,"улица Лизы Чайкиной, 97","Севастополь,",44.593154,33.481351
9889,https://www.avito.ru/3625452714,sevastopol,"квартира-студия, 30,8 м², 9/9 эт.",NaN,5451600,"севастополь,жк «доброгород» улица токарева,8 э...","Доступна ипотека! Ипотека с господдержкой, вое...",2024-06-11 10:25:30.856703,0,9,...,False,False,False,False,5.4516,True,"ЖК «Доброгород»\n улица Токарева, 8 этап, блок 3","Севастополь,",44.5807,33.506621
9926,https://www.avito.ru/3849263134,sevastopol,"1-к. квартира, 32,5 м², 4/5 эт.",NaN,6000000,"севастополь,улица бориса михайлова,25","Прекрасное предложение для тех, кто мечтает о ...",2024-06-11 10:25:30.856703,1,4,...,False,False,False,False,6.0000,False,"улица Бориса Михайлова, 25","Севастополь,",44.577997,33.444979

In [27]:
display( len(df_land) )
df_land  = df_land.merge(location,on='address').reset_index(drop=True) 
display( len(df_land) )
display( df_land.sample(3) )

11379

11379

,url,place,title,subtitle,price,address,description,ts,area,is_IJS,priceM,priceMU,area_size_category,address_orig,place_,latitude,longitude
7603,https://www.avito.ru/2922152092,bahchisaray,участок 8 сот. (ижс),NaN,1500000,"бахчисарай,с.речное",Очень красивое место! Всем всего хорошего!,2024-06-10 11:38:42.490270,8.0,True,1.5,0.1875,4-8,с. Речное,"Бахчисарай,",44.737167,33.786797
2298,https://sevastopol.cian.ru/sale/suburban/29813...,sevastopol,"участок, 8 сот., ижс",,2600000,"севастополь,р-н балаклавский,с.передовое,улица...",Объект 5643. Продается эксклюзивный красивейши...,2024-06-07 11:37:10.690720,8.0,True,2.6,0.3250,4-8,"Севастополь, р-н Балаклавский, с. Передовое, у...","Севастополь,",44.51571,33.824589
1934,https://sevastopol.cian.ru/sale/suburban/30157...,sevastopol,"участок, 5 сот., садоводство",,1100000,"севастополь,р-н балаклавский,мкр.инкерман,раду...",Объект 11443. Продам участок. Участок 5 соток ...,2024-06-07 11:37:10.690720,5.0,False,1.1,0.2200,4-8,"Севастополь, р-н Балаклавский, мкр. Инкерман, ...","Севастополь,",44.62096,33.605409

In [28]:
display( len(df_house) )
df_house = df_house.merge(location,on='address').reset_index(drop=True) 
display( len(df_house) )
display( df_house.sample(3) )

10402

10402

,url,place,title,subtitle,price,address,description,ts,house_area,is_part,is_townhouse,is_SNT,land_area,priceM,land_size_category,house_size_category,address_orig,place_,latitude,longitude
6864,https://www.avito.ru/2594826773,sevastopol,дом 68 м² на участке 10 сот.,NaN,9900000,"севастополь,балаклава,композиторская ул.,42",Очень Срочно пока не продан интересующий меня ...,2024-06-11 10:41:08.345000,68.0,False,False,False,10.0,9.9,8-20,50-70,"Балаклава, Композиторская ул., 42","Севастополь,",44.501806,33.624705
7328,https://www.avito.ru/2600083960,sevastopol,"дом 270,7 м² на участке 13,8 сот.",NaN,6000000,"севастополь,с.полюшко,молодёжная ул.,22",Продам 2-х этажный дом 270 кв. М из природного...,2024-06-11 10:41:08.345000,270.7,False,False,False,13.8,6.0,8-20,150-300,"с. Полюшко, Молодёжная ул., 22","Севастополь,",44.745189,33.591072
3079,https://krym.cian.ru/sale/suburban/289180166/,sudak,"дом, 77 м², 8 сот., ижс",,11900000,"республика крым,судак,улица ленина,29","Продам дом 76м2, на участке 8 соток в центре г...",2024-06-07 11:44:14.693655,77.0,False,False,False,8.0,11.9,4-8,70-150,"Республика Крым, Судак, улица Ленина, 29","Судак,",44.855241,34.975519

In [29]:
assert len(df_flat)>0
df_flat.to_pickle(f'{data_root_folder}/df_flat.pkl')

assert len(df_land)>0
df_land.to_pickle(f'{data_root_folder}/df_land.pkl')

assert len(df_house)>0
df_house.to_pickle(f'{data_root_folder}/df_house.pkl')

In [30]:
!date

Вт 11 июн 2024 10:55:29 MSK