__собираем объявления о продаже недвижимости в одну таблицу__

_Evgeny S. Borisov <parser@mechanoid.su>_

In [1]:
!date

Пн 12 авг 2024 11:36:46 MSK

In [2]:
from os import listdir
import re
import pandas as pd

In [3]:
data_root_folder = 'data/2024'
source = {
         'flat':[data_root_folder+'/raw/flat/cian',data_root_folder+'/raw/flat/avito'],
        'house':[data_root_folder+'/raw/house/cian',data_root_folder+'/raw/house/avito'],
         'land':[data_root_folder+'/raw/land/cian',data_root_folder+'/raw/land/avito'],
    }

---

In [4]:
obj_type = 'flat'
files = [ f'{d}/{f}' for d in source[obj_type] for f in listdir(d) if f[-4:]=='.pkl' ]
display( len(files) )

cols = ['url','place','title','subtitle','price','address','description','ts',]

df_flat = pd.concat([
        pd.read_pickle(f).drop_duplicates(['url'])
        for f in files
    ]).reset_index(drop=True)[cols]

display( len(df_flat) )
display(df_flat.sample(9))

60

55847

,url,place,title,subtitle,price,address,description,ts
19473,https://sevastopol.cian.ru/sale/flat/282199914/,sevastopol,"1-комн. квартира, 56,6 м², 4/11 этаж",,12452000,"Севастополь, р-н Гагаринский, улица Парковая, 7",,2024-06-24 12:36:04.449533
5292,https://sevastopol.cian.ru/sale/flat/300552843/,sevastopol,"1-комн. квартира, 31,3 м², 3/9 этаж",,5500000,"Севастополь, р-н Гагаринский, мкр. Камышовая б...","Объект 38. Продается с ремонтом, мебелью и тех...",2024-06-07 11:33:12.800097
18764,https://sevastopol.cian.ru/sale/flat/302626030/,sevastopol,"1-комн. квартира, 30,8 м², 6/9 этаж",,5800000,"Севастополь, р-н Гагаринский, мкр. Летчики, ул...",БЕЗ КОМИССИИ ДЛЯ ПОКУПАТЕЛЯ!!! Продается однок...,2024-06-18 10:45:27.403294
41938,https://www.avito.ru/4055895313,sevastopol,"1-к. квартира, 43 м², 3/5 эт.",NaN,6250000,"ул. Генерала Лебедя, 10","Продам в г. Севастополе ул. Генерала Лебедя,10...",2024-07-08 13:29:07.581057
30858,https://www.avito.ru/3850625763,sevastopol,"1-к. квартира, 30,3 м², 5/5 эт.",NaN,5400000,"ул. Маршала Блюхера, 18",Объект №1566. Продаётся уютная 1-комнатная ква...,2024-07-22 11:05:31.760224
40459,https://www.avito.ru/3981055273,sevastopol,"3-к. квартира, 70,1 м², 4/5 эт.",NaN,7700000,"Казачья ул., 9",K Пpодaже Предлагаeтcя Прoстoрhaя Kbaртирa В Л...,2024-07-30 16:15:15.853171
38269,https://www.avito.ru/3225447540,sevastopol,"1-к. апартаменты, 30 м², 5/10 эт.",NaN,11200000,"Парковая ул., 7",Продаются элитные апартаменты в лучшем 5-ти зв...,2024-08-06 11:02:57.284493
34073,https://www.avito.ru/3813713058,sudak,"1-к. квартира, 34,5 м², 8/9 эт.",NaN,6734000,Комплекс апартаментов «Бирюзовый квартал»\nул....,Ремонт В Подарок до 15.08.24г. Скидка 100 000 ...,2024-07-30 16:30:58.800714
9919,https://krym.cian.ru/sale/flat/301444448/,sudak,"3-комн. апартаменты, 89,3 м², 2/3 этаж",,35700000,"Республика Крым, Судак, улица Набережная, 75к11","Первая линия моря, круглогодичный спа комплекс...",2024-07-22 11:12:52.007628

In [5]:
from lib.cleaner import CleanerFlat

df_flat = CleanerFlat().transform(df_flat)
display( len(df_flat) )
display(df_flat.sample(9))

55847

,url,place,title,subtitle,price,address,description,ts,nrooms,floor,...,area,is_studio,is_apartment,is_part,is_auction,is_openspace,is_roof,is_SNT,priceM,is_last_floor
6400,https://sevastopol.cian.ru/sale/flat/295065037/,sevastopol,"студия, 33 м², 1/3 этаж",,3300000,"Севастополь, р-н Гагаринский, мкр. Стрелецкая ...",Продаётся квартира-студия в Гагаринском районе...,2024-06-14 12:56:14.435965,0,1,...,33.00,True,False,False,False,False,False,False,3.300000,False
30425,https://www.avito.ru/3625364275,sevastopol,"1-к. квартира, 43,2 м², 4/9 эт.",NaN,7084800,"ЖК «Доброгород»\n улица Токарева, 8 этап, блок 4",Сдача объекта — I кв. 2027 г. Доступна ипотека...,2024-06-17 08:29:48.414678,1,4,...,43.20,False,False,False,False,False,False,False,7.084800,False
190,https://krym.cian.ru/sale/flat/296384951/,sudak,"2-комн. квартира, 117,93 м², 7/8 этаж",Секция С5 • Сдача корпуса 1 кв. 2027,20944128,"Республика Крым, Судак, Долина Роз ЖК","Продается квартира общей площадью 117,93 м2 в ...",2024-06-18 10:56:35.757139,0,7,...,117.93,False,False,False,False,False,False,False,20.944128,False
53798,https://www.avito.ru/3755167168,sevastopol,"3-к. квартира, 77 м², 3/3 эт.",NaN,9950000,"улица Челнокова, 39",Объект №1432. Продам 3-комнатную квартиру в мо...,2024-06-10 11:17:35.151941,3,3,...,77.00,False,False,False,False,False,False,False,9.950000,True
9357,https://sevastopol.cian.ru/sale/flat/299737090/,sevastopol,"1-комн. апартаменты, 53 м², 2/10 этаж",,14500000,"Севастополь, р-н Гагаринский, улица Парковая, 7","Однокомнатные апартаменты 53 м2, на 2/10 эт. О...",2024-07-30 16:07:58.352115,0,2,...,53.00,False,True,False,False,False,False,False,14.500000,False
46352,https://www.avito.ru/4236136486,sevastopol,"1-к. квартира, 34,1 м², 3/11 эт.",NaN,6820000,"улица Тараса Шевченко, 18","Квартира от собственника, на 3 этаже 11 этажно...",2024-06-07 11:27:07.236636,1,3,...,34.10,False,False,False,False,False,False,False,6.820000,False
50264,https://www.avito.ru/3880876291,sevastopol,"1-к. квартира, 44,3 м², 4/5 эт.",NaN,7400000,"улица Героев Бреста, 31",Предлагаем Вашему вниманию однокомнатную кварт...,2024-06-11 10:25:30.856703,1,4,...,44.30,False,False,False,False,False,False,False,7.400000,False
7921,https://sevastopol.cian.ru/sale/flat/302531616/,sevastopol,"1-комн. квартира, 22 м², 4/5 этаж",,4200000,"Севастополь, р-н Балаклавский, село Первомайск...",Продаётся уютная однокомнатная квартира в живо...,2024-06-11 10:13:23.305322,0,4,...,22.00,False,False,False,False,False,False,False,4.200000,False
19219,https://sevastopol.cian.ru/sale/flat/276529734/,sevastopol,купить квартиру в севастополе. пр,"1-комн. апартаменты, 46,6 м², 4/5 этаж",4500000,"Севастополь, р-н Гагаринский, улица Адмирала Ф...",Срочно!Продаются видовые апартаменты в Стрелец...,2024-06-24 12:36:04.449533,0,0,...,0.00,False,False,False,False,False,False,False,4.500000,True

---

In [6]:
obj_type = 'land'
files = [ f'{d}/{f}' for d in source[obj_type] for f in listdir(d) if f[-4:]=='.pkl' ]
display( len(files) )

cols = ['url','place','title','subtitle','price','address','description','ts',]

df_land = pd.concat([
        pd.read_pickle(f).drop_duplicates(['url'])
        for f in files
    ]).reset_index(drop=True)[cols]

display( len(df_land) )
display(df_land.sample(9))

75

50163

,url,place,title,subtitle,price,address,description,ts
31927,https://www.avito.ru/2800811623,sevastopol,"Участок 5 сот. (СНТ, ДНП)",NaN,2050000,"садоводческое товарищество Лукулл, 9",Цена актуальна до конца недели. Собственник. П...,2024-07-08 13:36:06.464523
6771,https://sevastopol.cian.ru/sale/suburban/30256...,sevastopol,"Участок, 5.3 сот., Садоводство",,4200000,"Севастополь, р-н Балаклавский, шоссе Монастырс...",Продаю участок на первой линии в районе конечн...,2024-06-17 08:22:17.440170
19684,https://www.avito.ru/3937499205,sevastopol,"Участок 4,5 сот. (СНТ, ДНП)",NaN,2500000,садоводческое товарищество Техника,"Угловой, с уклоном, квадратной формы, частично...",2024-06-17 08:36:13.464806
10762,https://sevastopol.cian.ru/sale/suburban/30257...,sevastopol,"Участок, 6.2 сот., Садоводство",,3500000,"Севастополь, р-н Гагаринский, мкр. Фиолент, Гр...","Продам участок на Фиоленте, СНТ Гранат, 6,2 со...",2024-06-19 12:23:33.870565
45885,https://www.avito.ru/3503970097,sevastopol,Участок 9 сот. (ИЖС),NaN,1100000,"с. Фронтовое, Солнечная ул.",Продам земельный участок в Нахимовском районе ...,2024-06-11 10:32:52.971878
15541,https://sevastopol.cian.ru/sale/suburban/30419...,sevastopol,"Участок, 10 сот., ИЖС",,2450000,"Севастополь, р-н Балаклавский, с. Родниковское...",Объект 16864. Южный берег Крыма (сокращенно ЮБ...,2024-07-30 16:15:42.641826
42746,https://www.avito.ru/3890295706,sudak,"Участок 5,8 сот. (ИЖС)",NaN,3500000,квартал Алчак,Продается участок недалеко от Восточного шоссе...,2024-06-07 12:06:21.568118
24232,https://www.avito.ru/3664350929,bahchisaray,"Участок 8,1 сот. (ИЖС)",NaN,3500000,Альминская ул.,"Продам участок, документы Российские, я собств...",2024-07-30 16:34:04.489119
33720,https://www.avito.ru/3503160306,bahchisaray,"Участок 3 га (СНТ, ДНП)",NaN,9999000,с. Новополье,Продам уникальный земельный участок 3 га в с. ...,2024-06-10 11:38:42.490270

In [7]:
from lib.cleaner import CleanerLand

df_land = CleanerLand().transform(df_land)

display( len(df_land) )
display(df_land.sample(9))

50163

,url,place,title,subtitle,price,address,description,ts,area,is_IJS,priceM,priceMU,area_size_category
21749,https://www.avito.ru/3864743358,sevastopol,участок 8 сот. (ижс),NaN,2850000,с. Угловое,"Продается земельный участок, ровный, без уклон...",2024-06-10 11:25:16.532576,8.0,True,2.850000,0.356250,4-8
42806,https://www.avito.ru/2138394932,sudak,"участок 8,3 сот. (ижс)",NaN,1900000,"с. Богатовка, ул. Новый квартал","Продается участок в селе Богатовка, ул. Новый ...",2024-06-07 12:06:21.568118,8.3,True,1.900000,0.228916,8-12
44224,https://www.avito.ru/4167067976,bahchisaray,"участок 35 сот. (снт, днп)",NaN,2500000,"с. Солнечноселье, Зелёный пер.",Прекрасный видовой участок Лпх 35 соток рядом ...,2024-07-22 11:24:37.881374,35.0,False,2.500000,0.071429,20+
44504,https://www.avito.ru/4187510003,bahchisaray,"участок 8 сот. (снт, днп)",NaN,600000,квартал Новый Город,"Продаются земельные участки по 8 соток, земли ...",2024-07-22 11:24:37.881374,8.0,False,0.600000,0.075000,4-8
3746,https://sevastopol.cian.ru/sale/suburban/29754...,sevastopol,"участок, 4 сот., ижс",,5700000,"Севастополь, р-н Нахимовский, Солнышко садовод...","Участок 4 сотки (СТ) в г. Севастополь, Нахимов...",2024-08-12 11:10:58.029975,4.0,True,5.700000,1.425000,2-4
31445,https://www.avito.ru/4070075853,sevastopol,"участок 3,9 сот. (снт, днп)",NaN,4500000,"ТСН Дружба, ул. Старшины Бабажанова","Квадратный участок, ровный. Городская вода( кр...",2024-07-08 13:36:06.464523,3.9,False,4.500000,1.153846,2-4
39400,https://www.avito.ru/3819342594,sudak,участок 8 сот. (ижс),NaN,3700001,"с. Солнечная Долина, ул. Матвиенко",Угловой участок. Расположен на пересечении ули...,2024-07-16 12:51:23.262228,8.0,True,3.700001,0.462500,4-8
27464,https://www.avito.ru/3811899199,bahchisaray,участок 16 сот. (ижс),NaN,3000000,"с. Вилино, ул. Шалаева",Собственник! Важно дочитать объявление до конц...,2024-06-11 10:49:42.413688,16.0,True,3.000000,0.187500,12-20
20303,https://www.avito.ru/3550706740,sevastopol,участок 7 сот. (ижс),NaN,28500000,"Древняя ул., 8",Предлагается к продаже земельный участок в гор...,2024-06-17 08:36:13.464806,7.0,True,28.500000,4.071429,4-8

---

In [8]:
obj_type = 'house'
files = [ f'{d}/{f}' for d in source[obj_type] for f in listdir(d) if f[-4:]=='.pkl' ]
display( len(files) )

cols = ['url','place','title','subtitle','price','address','description','ts',]

df_house = pd.concat([
        pd.read_pickle(f).drop_duplicates(['url'])
        for f in files
    ]).reset_index(drop=True)[cols]

display( len(df_house) )
display(df_house.sample(9))

75

46014

,url,place,title,subtitle,price,address,description,ts
16356,https://sevastopol.cian.ru/sale/suburban/29714...,sevastopol,"Дом, 110,8 м², 4 сот., Садоводство",,9980000,"Севастополь, р-н Гагаринский, Торпеда садоводч...",ДОМ НА ЗЕМЕЛЬНОМ УЧАСТКЕ У ЧЕРНОГО МОРЯ! (г. С...,2024-06-14 13:06:13.997742
12795,https://sevastopol.cian.ru/sale/suburban/30259...,sevastopol,"Дом, 110 м², 4 сот., Садоводство",,11000000,"Севастополь, р-н Гагаринский, Янтарь садоводче...","Продается одноэтажный дом в СТ ""Янтарь"" площад...",2024-06-18 10:55:44.416781
2105,https://sevastopol.cian.ru/sale/suburban/28548...,sevastopol,"Дом, 50,1 м², 16 сот.",,5400000,"Севастополь, р-н Балаклавский, с. Родниковское...",Продам дом в одном из самых красивых мест Крым...,2024-06-17 08:27:31.304082
23106,https://www.avito.ru/3250911497,sevastopol,Дом 106 м² на участке 4 сот.,NaN,14000000,Камышовое ш.,"Продается дом в Гагаринском районе, в черте го...",2024-06-13 11:32:06.964835
10202,https://sevastopol.cian.ru/sale/suburban/29475...,sevastopol,"Дом, 45,5 м², 4 сот., Садоводство",,6400000,"Севастополь, р-н Гагаринский, мкр. Фиолент, Ко...","Дом 45,5 м² на участке 4 сотки Дом 45,5 м² на ...",2024-06-19 12:37:23.275933
29087,https://www.avito.ru/3816689204,bahchisaray,"Дом 44,7 м² на участке 24 сот.",NaN,5100000,"с. Высокое, 34","Продается одноэтажный дом 44,7 кв. М. На участ...",2024-06-24 13:06:17.982273
39901,https://www.avito.ru/2849235377,bahchisaray,Дом 116 м² на участке 10 сот.,NaN,3700000,"ул. Висовина, 17",Продам дом в центре города. Требует капитально...,2024-07-08 13:49:26.679246
29902,https://www.avito.ru/3751777855,sevastopol,"Дом 190,7 м² на участке 8,8 сот.",NaN,13499000,"садовое товарищество Гавань, ул. Волонтеров, 12",Арт. 63569957 Срочная Продажа! Экодом с приуса...,2024-06-10 11:33:36.811644
19336,https://www.avito.ru/3285141880,bahchisaray,"Дом 52,3 м² на участке 6 сот.",NaN,4950000,Новая ул.,"Дом находится в городе Бахчисарай, недалеко от...",2024-06-14 13:24:56.973530

In [9]:
# cols = ['title','address','place','url']
# df_house[ (df_house['place']=='sevastopol') & (df_house['address'].str.match(r'.*Судак.*')) ][cols]

In [10]:
from lib.cleaner import CleanerHouse

df_house = CleanerHouse().transform(df_house)

display( len(df_house) )
display(df_house.sample(9))

46014

,url,place,title,subtitle,price,address,description,ts,house_area,is_part,is_townhouse,is_SNT,land_area,priceM,land_size_category,house_size_category
19108,https://krym.cian.ru/sale/suburban/284017012/,sudak,"дом, 300 м², 5.5 сот., ижс",,10300000,"Республика Крым, Судак, улица Лазурная",Продается недостроенный дом расположенный в кв...,2024-07-16 12:55:43.335990,300.0,False,False,False,5.0,10.3,4-8,180-300
40938,https://www.avito.ru/3998350887,bahchisaray,"дом 110,6 м² на участке 6,8 сот.",NaN,2700000,садоводческий потребительский кооператив Энтуз...,"Продается жилой дом в дачном кооперативе, дом ...",2024-06-10 11:39:39.442400,110.6,False,False,True,6.8,2.7,4-8,110-180
29268,https://www.avito.ru/3720063196,sevastopol,дом 110 м² на участке 8 сот.,NaN,12300000,СТ Берег,Продам дом в одном из лучших СТ Северной сторо...,2024-06-10 11:33:36.811644,110.0,False,False,True,8.0,12.3,4-8,70-110
15510,https://sevastopol.cian.ru/sale/suburban/29669...,sevastopol,"дом, 47 м², 4 сот.",,5200000,"Севастополь, р-н Балаклавский, Технолог садово...",Дом 50 м² на участке 4 сотки Дом 50 м² на учас...,2024-06-14 13:06:13.997742,47.0,False,False,True,4.0,5.2,2-4,30-50
1488,https://sevastopol.cian.ru/sale/suburban/30268...,sevastopol,"дом, 110 м², 4 сот., ижс",,9600000,"Севастополь, р-н Нахимовский, улица Генерала Р...",Объект 242. Предлагаю приобрести дом в совреме...,2024-06-17 08:27:31.304082,110.0,False,False,False,4.0,9.6,2-4,70-110
7541,https://krym.cian.ru/sale/suburban/295803442/,sudak,"дом, 2 248 м², 15 сот.",,130000000,"Республика Крым, Судак, улица Консульская, 20",Продается недостроенный многоквартирный дом на...,2024-06-10 11:25:21.743717,248.0,False,False,False,15.0,130.0,12-20,180-300
12817,https://sevastopol.cian.ru/sale/suburban/30141...,sevastopol,"дом, 150 м², 4 сот., садоводство",,11000000,"Севастополь, р-н Гагаринский, мкр. Фиолент, Лу...",Двухэтажный дом в СТ Лукоморье!!! Дом 150 м2 н...,2024-06-18 10:55:44.416781,150.0,False,False,True,4.0,11.0,2-4,110-180
2168,https://sevastopol.cian.ru/sale/suburban/29855...,sevastopol,"дом, 53,3 м², 3.95 сот., садоводство",,6100000,"Севастополь, р-н Балаклавский, Корабел СТ, 320","Уникальное предложение! Продаётся уютный, небо...",2024-06-17 08:27:31.304082,53.3,False,False,True,95.0,6.1,20+,50-70
20435,https://www.avito.ru/4208071690,sevastopol,"дом 25 м² на участке 5,4 сот.",NaN,4500000,"садоводческое товарищество Дергачи-4, 187",Арт. 69557313 Этот объект можно купить в ипоте...,2024-07-16 12:49:11.298800,25.0,False,False,True,5.4,4.5,4-8,<30

---

## обновляем таблицу адресов

In [11]:
# !pip install geopy

In [12]:
from lib.locator import AddressTransformer

atr = AddressTransformer()

places = { 
# поле 'place' и название города
'bahchisaray': 'Бахчисарай,',
      'sudak': 'Судак,',
  'sevastopol': 'Севастополь,',
}

def address_norm(df,atr=atr):
    df['address_orig'] =  df['address']
    df['address'] =  df['address'].apply(atr.transform)
    df['place_'] =  df['place'].map(places)
    df['address'] = df[['address','place_']].apply(lambda d: d[0] if d[1] in d[0] else d[1]+','+d[0],axis=1) 
    df['address'] = (
        df['address']
        .str.replace(', ',',')
        .str.replace(',,',',')
        .str.replace('. ','.')
        .str.replace('\n',' ')
        .str.replace('  ',' ')
        .str.lower()
    )
    return df

In [13]:
df_flat = address_norm(df_flat)
df_land = address_norm(df_land)
df_house = address_norm(df_house)

/tmp/ipykernel_2301970/776805188.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['address'] = df[['address','place_']].apply(lambda d: d[0] if d[1] in d[0] else d[1]+','+d[0],axis=1)
/tmp/ipykernel_2301970/776805188.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['address'] = df[['address','place_']].apply(lambda d: d[0] if d[1] in d[0] else d[1]+','+d[0],axis=1)
/tmp/ipykernel_2301970/776805188.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['address'] = df[['address','place_']].apply(lambda d: d[0] if d[1] in d[0] else d[1]+','+d[0],axis=1)

In [14]:
# df_flat[['address','address_orig']]

In [15]:
address = pd.concat([
        df_flat[['address','address_orig']],
        df_land[['address','address_orig']],
        df_house[['address','address_orig']],
    ]).drop_duplicates(['address']).reset_index(drop=True)

display(len(address))
display(address.sample(5))

12337

,address,address_orig
7204,"бахчисарай,с.новоульяновка,советская ул.","с. Новоульяновка, Советская ул."
7407,"севастополь,пл.лазарева",пл. Лазарева
3106,"севастополь,балаклава,улица аксютина,39","Балаклава, улица Аксютина, 39"
8521,"севастополь,р-н нахимовский,с.вишневое,улица к...","Севастополь, р-н Нахимовский, с. Вишневое, ули..."
5671,"севастополь,садоводческое товарищество золотая...","садоводческое товарищество Золотая Балка, 98"

In [16]:
from os.path import exists as path_exists
loc_file_path = 'data/location.pkl' # таблица адресов

location = pd.DataFrame([],columns=['address','latitude','longitude',])
if path_exists( loc_file_path ):
    location = pd.read_pickle(loc_file_path).drop_duplicates(['address']).reset_index(drop=True)
    
display(len(location))
display(location.sample(5))

18817

                                                 address   latitude  longitude
9449       севастополь,район гагаринский,улица щитовая,8  44.603616  33.463619
7712   севастополь,р-н нахимовский,мкр.горпищенко,ули...  44.595214  33.558912
9974   севастополь,район нахимовский,кача,улица авиат...  44.774067  33.542796
18527  бахчисарай,садоводческое товарищество строител...  44.740253  33.894433
10216   севастополь,район нахимовский,улица курчатова,15  44.628614  33.570437

---

In [17]:
# def address_norm_(df):
#     df['address_orig'] =  df['address']
#     # df['address'] =  df['address'].apply(atr.transform)
#     df['address'] = (
#         df['address']
#         .str.replace(', ',',')
#         .str.replace(',,',',')
#         .str.replace('. ','.')
#         .str.replace('\n',' ')
#         .str.replace('  ',' ')
#         .str.lower()
#     )
#     return df

In [18]:
# location = address_norm_(location)

In [19]:
# location = location[['address','latitude','longitude']]

---

In [20]:
# собираем все адреса в один список
location = location.merge(
        address[['address']].drop_duplicates(),
        how='outer',
        on='address',
    ).drop_duplicates(['address']).reset_index(drop=True)

display(len(location))
display(location.sample(5))

19065

                                                 address   latitude  longitude
18397  судак,республика крым,судак городской округ,с....  44.849484  34.885068
5080            севастополь,р-н балаклавский,рубин ст,58  44.539467  33.584245
7918   севастополь,р-н нахимовский,мираж садовое това...   44.71718  33.551914
2670                 севастополь,кача,улица авиаторов,25  44.775936  33.545392
12102  севастополь,садоводческое товарищество золотая...  44.519733  33.550836

In [21]:
display(len(location))
display(location['latitude'].isnull().sum())

19065

248

In [22]:
# собираем все адреса с геопозицией
location_def = location[~location['latitude'].isna()].reset_index(drop=True)
display(len(location_def))

# собираем все адреса без геопозиции
location_undef = location[location['latitude'].isna()][['address']].reset_index(drop=True)
display(len(location_undef))

18817

248

In [23]:
display(location_undef)

                                       address
0         бахчисарай,пгт.почтовое,вишнёвая ул.
1        бахчисарай,с.вилино,спортивная ул.,35
2           бахчисарай,с.высокое,ул.строителей
3         бахчисарай,с.глубокий яр,ул.чешме,32
4       бахчисарай,с.красный мак,ул.ленина,46а
..                                         ...
243  судак,с.солнечная долина,квартал бугаз,79
244     судак,садовое товарищество ветеран,147
245                  судак,серный переулок ,12
246               судак,улица айвазовского,4/1
247                     судак,улица бирюзова,4

[248 rows x 1 columns]

In [24]:
from tqdm.auto import tqdm
tqdm.pandas()

In [25]:
# from lib.locator import GeocoderSimpleOSM
from lib.locator import GeocoderYandex
from yandex_keys import keys

atr = AddressTransformer()
locator = GeocoderYandex(keys[0])
# locator = GeocoderSimpleOSM()

if len(location_undef)>0:
    # определяем координаты по строке адреса
    location_undef = location_undef.join( 
            location_undef['address'].progress_apply(locator.transform).apply(pd.Series) 
        ).dropna()     
    display(f'LocationUpdater: {len(location_undef)} new addresses found')
    location = pd.concat([location_def,location_undef]).reset_index(drop=True) 
    assert len(location)>0
    # location.to_pickle(loc_file_path)

  0%|          | 0/248 [00:00<?, ?it/s]

'LocationUpdater: 248 new addresses found'

In [26]:
display( len(location) )
display( location.sample(3) )

19065

                                                 address   latitude  longitude
10141  севастополь,район нахимовский,горпищенко,улица...  44.590586  33.566368
5545     севастополь,р-н балаклавский,улица каширская,1а  44.606074  33.590946
11119                   севастополь,с.угловое,ул.лазо,44  44.816456  33.614976

In [27]:
assert len(location)>0
location.to_pickle(loc_file_path)

## дополняем данные геометкой

In [28]:
display( len(df_flat) )
df_flat  = df_flat.merge(location,on='address').reset_index(drop=True) 
display( len(df_flat) )
display( df_flat.sample(3) )

55847

55847

,url,place,title,subtitle,price,address,description,ts,nrooms,floor,...,is_auction,is_openspace,is_roof,is_SNT,priceM,is_last_floor,address_orig,place_,latitude,longitude
9854,https://krym.cian.ru/sale/flat/304682549/,sudak,"апартаменты-студия, 31,95 м², 3/8 этаж",,5751000,"республика крым,судак,улица айвазовского,4/1",Без комиссии для покупателя ! Продаются уютные...,2024-07-22 11:12:52.007628,0,3,...,False,False,False,False,5.751,False,"Республика Крым, Судак, улица Айвазовского, 4/1","Судак,",44.851733,34.969689
52259,https://www.avito.ru/3881037543,sevastopol,"3-к. квартира, 54,3 м², 3/5 эт.",NaN,8000000,"севастополь,улица маршала блюхера,13",Продаю трехкомнатную квартиру в спальном район...,2024-06-13 11:17:37.489999,3,3,...,False,False,False,False,8.000,False,"улица Маршала Блюхера, 13","Севастополь,",44.583018,33.436957
2803,https://sevastopol.cian.ru/sale/flat/303562878/,sevastopol,"1-комн. квартира, 31,1 м², 1/5 этаж",,4950000,"севастополь,р-н ленинский,мкр.острякова,улица ...",Oднокoмнaтная квaртира в центральнoм рaйоне Ce...,2024-07-16 12:28:31.306616,0,1,...,False,False,False,False,4.950,False,"Севастополь, р-н Ленинский, мкр. Острякова, ул...","Севастополь,",44.56981,33.518865

In [29]:
display( len(df_land) )
df_land  = df_land.merge(location,on='address').reset_index(drop=True) 
display( len(df_land) )
display( df_land.sample(3) )

50163

50163

,url,place,title,subtitle,price,address,description,ts,area,is_IJS,priceM,priceMU,area_size_category,address_orig,place_,latitude,longitude
9415,https://sevastopol.cian.ru/sale/suburban/29311...,sevastopol,"участок, 7.3 сот., ижс",,16300000,"севастополь,р-н гагаринский,мкр.камышовая бухт...",Объект 1078. Продам участок по улице Героев Ст...,2024-06-13 11:16:11.805581,3.0,True,16.3,5.433333,2-4,"Севастополь, р-н Гагаринский, мкр. Камышовая б...","Севастополь,",44.588609,33.443721
35928,https://www.avito.ru/2508008634,bahchisaray,"участок 2,11 га (снт, днп)",NaN,700000,"бахчисарай,с.нововасильевка","Продам пай сельхозназначения 2,1 га. Земельный...",2024-06-13 11:36:28.263004,211.0,False,0.7,0.003318,20+,с. Нововасильевка,"Бахчисарай,",44.849005,33.915112
35858,https://www.avito.ru/1397676898,bahchisaray,"участок 2,9 га (снт, днп)",NaN,1200000,"бахчисарай,республика крым,бахчисарайский район","Продам землю с/х 2,9га рядом с Бахчисараем. По...",2024-06-13 11:36:28.263004,290.0,False,1.2,0.004138,20+,"Республика Крым, Бахчисарайский район","Бахчисарай,",44.744997,33.848035

In [30]:
display( len(df_house) )
df_house = df_house.merge(location,on='address').reset_index(drop=True) 
display( len(df_house) )
display( df_house.sample(3) )

46014

46014

,url,place,title,subtitle,price,address,description,ts,house_area,is_part,is_townhouse,is_SNT,land_area,priceM,land_size_category,house_size_category,address_orig,place_,latitude,longitude
21279,https://www.avito.ru/4186188280,sudak,"дом 213 м² на участке 7,4 сот.",NaN,15650000,"судак,коммунальная ул.",Объект №497. Продам замечательный двухэтажный ...,2024-06-19 12:39:21.598723,213.0,False,False,False,7.4,15.65,4-8,180-300,Коммунальная ул.,"Судак,",44.851542,34.984395
12905,https://sevastopol.cian.ru/sale/suburban/28784...,sevastopol,"дом, 150 м², 4 сот.",,12000000,"севастополь,р-н гагаринский,мкр.фиолент,космос...",Продам жилой дом 150 кв.м новой постройки на Ф...,2024-06-18 10:55:44.416781,150.0,False,False,True,4.0,12.00,2-4,110-180,"Севастополь, р-н Гагаринский, мкр. Фиолент, Ко...","Севастополь,",44.544613,33.455732
41192,https://www.avito.ru/2115784815,bahchisaray,дом 80 м² на участке 15 сот.,NaN,8000000,"бахчисарай,с.кудрино,новосёловская ул.,8","В красивом уголке Бахчисарайского района, сред...",2024-06-10 11:39:39.442400,80.0,False,False,False,15.0,8.00,12-20,70-110,"с. Кудрино, Новосёловская ул., 8","Бахчисарай,",44.70392,33.949562

In [31]:
def address_filter(df):
    #           46.319437, 33.911048
    #
    # 45.402617, 32.455625 |  45.545301, 36.684702
    #
    #          44.320887, 33.917013

    df['latitude'] = pd.to_numeric( df['latitude'], errors='coerce' )
    df['longitude'] = pd.to_numeric( df['longitude'], errors='coerce' )

    df = df.query('(32.4<longitude<36.7) & (44.3<latitude<46.4)') 

    df.loc[ df['url']=='https://avito.ru/2322251740', ['latitude','longitude']] = None

    df.loc[ df['address']=='Севастополь,Чёрное море', ['latitude','longitude'] ] = None
    df.loc[ df['address'].str.lower().str.match('чёрное море'), ['latitude','longitude'] ] = None 

    df.loc[ df['address']=='квартал Старый Город', 'place'] = 'turkie'
    df.loc[ df['address'].str.lower().str.match('анталья'), 'place' ] = 'turkie' 

    df.loc[ df['address'].str.lower().str.match(r'.*бахчисарай.*'), 'place' ] = 'bahchisaray'
    df.loc[ df['address'].str.lower().str.match(r'.*севастополь,.*'), 'place' ] = 'sevastopol'

    df.loc[ df['address'].str.lower().str.match(r'.*мысовское.*'), 'place' ] = 'kerch'
    df.loc[ df['address'].str.lower().str.match(r'.*алушта.*'), 'place' ] = 'alushta'
    df.loc[ df['address'].str.lower().str.match(r'.*гурзуф.*'), 'place' ] = 'gurzuf'

    df.loc[ df['address'].str.lower().str.match(r'.*с.лучистое.*'), 'place' ] = 'alushta'
    df.loc[ df['address'].str.lower().str.match(r'.*снт солнечная долина.*'), 'place' ] = 'sudak'
    df.loc[ df['address'].str.lower().str.match(r'.*пгт.новоозёрное.*'), 'place' ] = 'evpatoria'

    df.loc[ df['address'].str.lower().str.match(r'.*с.мирное.*'), 'place' ] = 'simferopol'
    df.loc[ df['address'].str.lower().str.match(r'.*тсн аэрофлот.*'), 'place' ] = 'simferopol'

    df.loc[ df['address'].str.lower().str.match(r'.*семисот.*'), 'place' ] = 'kerch'

    df.loc[ df['address'].str.lower().str.match(r'.*ялта.*') , 'place' ] = 'yalta'
    df.loc[ df['address'].str.lower().str.match(r'.*феодосия.*') , 'place' ] = 'feodosia'
    df.loc[ df['address'].str.lower().str.match(r'.*окуневка.*') , 'place' ] = 'tarkhankut'
    df.loc[ df['address'].str.lower().str.match(r'.*заветное.*') , 'place' ] = 'kerch'
    df.loc[ df['address'].str.lower().str.match(r'.*евпатория.*') , 'place' ] = 'evpatoria'
    df.loc[ df['address'].str.lower().str.match(r'.*симферопольский район.*'), 'place' ] = 'simferopol'

    df.loc[df['address'].str.match(r'.*белогорск.*'),'place'] = 'belogorsk'
    df.loc[df['address'].str.match(r'.*кировский.*'),'place'] = 'kirovsky'
    df.loc[df['address'].str.match(r'.*сакский район.*'),'place'] = 'saki'
    df.loc[df['address'].str.match(r'.*керчь.*'),'place'] = 'kerch'
    df.loc[df['address'].str.match(r'.*белогорский.*'),'place'] = 'belogorsk'
    df.loc[df['address'].str.match(r'.*кировский.*'),'place'] = 'kirovski'

    df.loc[df['address'].str.match(r'.*кореиз.*'),'place'] = 'ubk'
    df.loc[df['address'].str.match(r'.*малый маяк.*'),'place'] = 'ubk'
    df.loc[df['address'].str.match(r'.*светлый мир.*'),'place'] = 'simferopol'
    df.loc[df['address'].str.match(r'.*доброе.*'),'place'] = 'simferopol'
    df.loc[df['address'].str.match(r'.*родниково.*'),'place'] = 'simferopol'
    df.loc[df['address'].str.match(r'.*уютное.*'),'place'] = 'evpatoria'
    df.loc[df['address'].str.match(r'.*коктебель.*'),'place'] = 'koktebel'
    df.loc[df['address'].str.match(r'.*новосельское.*'),'place'] = 'tarhankut'

    df = df.dropna(subset=['latitude','longitude'])
    
    return df

In [32]:
display(len(df_flat))
df_flat = address_filter(df_flat)
display(len(df_flat))

display(len(df_land))
df_land = address_filter(df_land)
display(len(df_land))

display(len(df_house))
df_house = address_filter(df_house)
display(len(df_house))

55847

55156

50163

50139

46014

46012

In [33]:
assert len(df_flat)>0
df_flat.to_pickle(f'{data_root_folder}/df_flat.pkl')

assert len(df_land)>0
df_land.to_pickle(f'{data_root_folder}/df_land.pkl')

assert len(df_house)>0
df_house.to_pickle(f'{data_root_folder}/df_house.pkl')

In [34]:
!date

Пн 12 авг 2024 11:38:23 MSK