In [1]:
from os import listdir
import re
import pandas as pd

In [2]:
data_root_folder = 'data/2024'
source = {
         'flat':[data_root_folder+'/raw/flat/cian',data_root_folder+'/raw/flat/avito'],
        'house':[data_root_folder+'/raw/house/cian',data_root_folder+'/raw/house/avito'],
         'land':[data_root_folder+'/raw/land/cian',data_root_folder+'/raw/land/avito'],
    }

---

In [3]:
obj_type = 'flat'
files = [ f'{d}/{f}' for d in source[obj_type] for f in listdir(d) if f[-4:]=='.pkl' ]
display( len(files) )

cols = ['url','place','title','subtitle','price','address','description','ts',]

df_flat = pd.concat([
        pd.read_pickle(f).drop_duplicates(['url'])
        for f in files
    ]).reset_index(drop=True)[cols]

display( len(df_flat) )
display(df_flat.sample(9))

8

8438

,url,place,title,subtitle,price,address,description,ts
7431,https://www.avito.ru/2841438954,sevastopol,"2-к. квартира, 46,6 м², 3/4 эт.",NaN,7300000,"ул. Военных Строителей, 12/1","2-к. Квартира 46,6 м2, на 3/4 этаже дома. Расп...",2024-06-10 11:17:35.151941
6946,https://www.avito.ru/4080516348,sevastopol,"2-к. квартира, 57,5 м², 8/10 эт.",NaN,8300000,"ул. Астана Кесаева, 5/2",Квартира ждёт своих Счастливых владельцев! Про...,2024-06-10 11:17:35.151941
538,https://sevastopol.cian.ru/sale/flat/300836434/,sevastopol,Уютная квартира,"1-комн. квартира, 46 м², 5/5 этаж",6700000,"Севастополь, р-н Гагаринский, улица Вакуленчук...",Продается 1 комнатная квартира по адресу Вакул...,2024-06-07 11:33:12.800097
97,https://krym.cian.ru/sale/flat/300736642/,sudak,"Апартаменты-студия, 19 м², 1/8 этаж",,2101000,"Республика Крым, Судак, переулок Серный, 12А","Объект 129. Апартаменты, свободная планировка,...",2024-06-10 11:24:43.460368
8320,https://www.avito.ru/3625577979,sevastopol,"2-к. квартира, 60,8 м², 9/9 эт.",NaN,8998400,"ЖК «Доброгород»\nул. Токарева, 8 этап, блок 2","Доступна ипотека! Ипотека с господдержкой, вое...",2024-06-10 11:17:35.151941
17,https://krym.cian.ru/sale/flat/296834140/,sudak,"2-комн. квартира, 40 м², 2/9 этаж",,7000000,"Республика Крым, Судак, улица Бирюзова, 2","Продам квартиру в Судаке,в одном из центральны...",2024-06-10 11:24:43.460368
8073,https://www.avito.ru/3993175676,sevastopol,"2-к. квартира, 42,1 м², 2/3 эт.",NaN,8100000,"ул. Надежды Краевой, 1","Двухкомнатная квартира 42,1 м2, на 2/ 3 этаже ...",2024-06-10 11:17:35.151941
1571,https://sevastopol.cian.ru/sale/flat/302798789/,sevastopol,"1-комн. квартира, 30,1 м², 3/5 этаж",,6299000,"Севастополь, р-н Ленинский, мкр. Острякова, пр...",ПРОДАМ 1-комнатную квартиру в Ленинском районе...,2024-06-07 11:33:12.800097
4543,https://www.avito.ru/3654626977,sevastopol,"Апартаменты-студия, 45 м², 5/6 эт.",NaN,4500000,"ул. Адмирала Фадеева, 18",Недвижимость у моря — идеальный подарок! Если ...,2024-06-07 11:27:07.236636

In [4]:
from lib.cleaner import CleanerFlat

df_flat = CleanerFlat().transform(df_flat)
display( len(df_flat) )
display(df_flat.sample(9))

8438

,url,place,title,subtitle,price,address,description,ts,nrooms,floor,...,area,is_studio,is_apartment,is_part,is_auction,is_openspace,is_roof,is_SNT,priceM,is_last_floor
6537,https://www.avito.ru/2404213541,sevastopol,"3-к. квартира, 70,4 м², 1/5 эт.",NaN,9900000,"Балаклава, улица Богдана Хмельницкого, 8","Продаю свою 3-ком. «чешку„в Балаклаве, 10 мин....",2024-06-10 11:17:35.151941,3,1,...,70.4,False,False,False,False,False,False,False,9.90000,False
5941,https://www.avito.ru/3864830817,sevastopol,"1-к. квартира, 30,7 м², 3/5 эт.",NaN,5700000,"проспект Генерала Острякова, 84","Однокомнатная квартира 30,7 м2, на 3/5 этаже д...",2024-06-07 11:27:07.236636,1,3,...,30.7,False,False,False,False,False,False,False,5.70000,False
6471,https://www.avito.ru/4179233298,sevastopol,"3-к. квартира, 72,9 м², 2/9 эт.",NaN,8300000,"проспект Октябрьской Революции, 56Б",Квартира расположена в месте с развитой трансп...,2024-06-10 11:17:35.151941,3,2,...,72.9,False,False,False,False,False,False,False,8.30000,False
3737,https://www.avito.ru/2471464079,sudak,"апартаменты-студия, 46,8 м², 5/7 эт.",NaN,8999000,"Набережная улица , 75","Стоимость Ниже, чем у застройщика! Атлас — кра...",2024-06-10 11:35:05.787844,0,5,...,46.8,True,True,False,False,False,False,False,8.99900,False
4705,https://www.avito.ru/4137976114,sevastopol,"1-к. квартира, 43 м², 3/10 эт.",NaN,8900000,"проспект Октябрьской Революции, 48","Продам однокомнатную квартиру в новом доме, «Ж...",2024-06-07 11:27:07.236636,1,3,...,43.0,False,False,False,False,False,False,False,8.90000,False
4562,https://www.avito.ru/4046007645,sevastopol,"1-к. квартира, 44 м², 2/10 эт.",NaN,8600000,"Античный проспект , 26 к3","Продаем однокомнатную, уютную квартиру в Севас...",2024-06-07 11:27:07.236636,1,2,...,44.0,False,False,False,False,False,False,False,8.60000,False
512,https://sevastopol.cian.ru/sale/flat/302976036/,sevastopol,комфортная видовая однокомнатная,"1-комн. квартира, 40,6 м², 6/11 этаж",8300000,"Севастополь, р-н Гагаринский, мкр. 5-й, улица ...","ПРЕДСТАВЛЯЕМ ВАШЕМУ ВНИМАЮ СОВРЕМЕННУЮ, ФУНКЦИ...",2024-06-07 11:33:12.800097,0,0,...,0.0,False,False,False,False,False,False,False,8.30000,True
6844,https://www.avito.ru/3901207587,sevastopol,"2-к. квартира, 52,8 м², 1/12 эт.",NaN,6757120,"ЖК «Новый»\n шоссе Лабораторное, д. 33, секц. 7",В пpодажe двуxкомнaтная квартирa на 1 этaже дв...,2024-06-10 11:17:35.151941,2,1,...,52.8,False,False,False,False,False,False,False,6.75712,False
4506,https://www.avito.ru/3753503206,sevastopol,"2-к. квартира, 48,6 м², 3/5 эт.",NaN,5650000,"село Штурмовое, улица Комиссара Морозова, 8","Продаю двухкомнатную квартиру 50 кв. М., распо...",2024-06-07 11:27:07.236636,2,3,...,48.6,False,False,False,False,False,False,False,5.65000,False

---

In [5]:
obj_type = 'land'
files = [ f'{d}/{f}' for d in source[obj_type] for f in listdir(d) if f[-4:]=='.pkl' ]
display( len(files) )

cols = ['url','place','title','subtitle','price','address','description','ts',]

df_land = pd.concat([
        pd.read_pickle(f).drop_duplicates(['url'])
        for f in files
    ]).reset_index(drop=True)[cols]

display( len(df_land) )
display(df_land.sample(9))

10

7473

,url,place,title,subtitle,price,address,description,ts
325,https://sevastopol.cian.ru/sale/suburban/29585...,sevastopol,"Участок, 4 сот., ИЖС",,2000000,"Севастополь, р-н Балаклавский, Горный дачный п...",Участок 4 сотки ИЖС Участок 4 сотки (ИЖС) в г....,2024-06-07 11:37:10.690720
7185,https://www.avito.ru/3500692256,sevastopol,"Участок 15,4 сот. (СНТ, ДНП)",NaN,5000000,садоводческое товарищество УПТК,Арт. 547780 К продаже предлагается участок пло...,2024-06-07 11:38:45.101812
2116,https://sevastopol.cian.ru/sale/suburban/29864...,sevastopol,"Участок, 5 сот., Садоводство",,1500000,"Севастополь, р-н Нахимовский, Лукулл садоводче...",Объект 16157. Продам участок в Нахимовском рай...,2024-06-10 11:18:48.884876
3836,https://www.avito.ru/3740662620,sevastopol,"Участок 8,5 сот. (ИЖС)",NaN,8000000,"ул. Верещагина, 42","Земельный участок на 5 км. — Ижс 8.5 соток, в ...",2024-06-10 11:25:16.532576
5457,https://www.avito.ru/2850313072,bahchisaray,"Участок 17,5 га (СНТ, ДНП)",NaN,4300000,"Республика Крым, Бахчисарайский район, Каштано...",Продается действующее хозяйство. Площадь насаж...,2024-06-10 11:38:42.490270
6777,https://www.avito.ru/3437611419,sevastopol,"Участок 4,1 сот. (ИЖС)",NaN,13000000,"ул. Челнокова, 14/24","Продам участок Ижс 4,08 сотки. На участке все ...",2024-06-07 11:38:45.101812
4672,https://www.avito.ru/3149718293,bahchisaray,"Участок 1,33 га (СНТ, ДНП)",NaN,2000000,с. Дачное,"Продам участок. Шикарное место положения, ровн...",2024-06-07 12:09:12.165236
3288,https://www.avito.ru/3240584594,sevastopol,"Участок 4 сот. (СНТ, ДНП)",NaN,1600000,садоводческое товарищество Гераклея,"Если нет связи, пишите, пожалуйста в личные со...",2024-06-10 11:25:16.532576
4914,https://www.avito.ru/3597184432,bahchisaray,"Участок 3,6 га (СНТ, ДНП)",NaN,2800000,с. Танковое,Продаётся отличный видовой с/х участок площадь...,2024-06-07 12:09:12.165236

In [6]:
from lib.cleaner import CleanerLand

df_land = CleanerLand().transform(df_land)

display( len(df_land) )
display(df_land.sample(9))

7473

,url,place,title,subtitle,price,address,description,ts,area,is_IJS,priceM,priceMU,area_size_category
2192,https://sevastopol.cian.ru/sale/suburban/30272...,sevastopol,"участок, 9.9 сот., ижс",,2000000,"Севастополь, р-н Нахимовский, шоссе Лабораторн...",Великолепный участок 10 соток под строительств...,2024-06-10 11:18:48.884876,9.0,True,2.0,0.222222,8-20
1584,https://krym.cian.ru/sale/suburban/302203239/,sudak,"участок, 6 сот., ижс",,6000000,"Республика Крым, Судак, шоссе Восточное, 76",участок 6 соток в г. Судак. находится в прести...,2024-06-07 11:43:54.644884,6.0,True,6.0,1.000000,4-8
1479,https://sevastopol.cian.ru/sale/suburban/29631...,sevastopol,"участок, 4.7 сот., садоводство",,4500000,"Севастополь, р-н Балаклавский, Автомобилист са...","Объект 1118. В продаже участок 4,66 сотки. Уча...",2024-06-07 11:37:10.690720,7.0,False,4.5,0.642857,4-8
1587,https://krym.cian.ru/sale/suburban/291919113/,sudak,"участок, 10 сот., ижс",,10800000,"Республика Крым, Судак, переулок Колхозный, 10",Продам участок 10 соток Коммуникации централиз...,2024-06-07 11:43:54.644884,10.0,True,10.8,1.080000,8-20
126,https://sevastopol.cian.ru/sale/suburban/29754...,sevastopol,участок 6 соток ижс,"Участок, 6 сот., ИЖС",1800000,"Севастополь, р-н Нахимовский, мкр. Северная ст...","Участок 6 соток (ИЖС) в г. Севастополь, Нахимо...",2024-06-07 11:37:10.690720,6.0,True,1.8,0.300000,4-8
2009,https://sevastopol.cian.ru/sale/suburban/29914...,sevastopol,"участок, 4.4 сот., ижс",,10000000,"Севастополь, р-н Ленинский, мкр. Матюшенко, ул...",,2024-06-10 11:18:48.884876,4.0,True,10.0,2.500000,2-4
706,https://sevastopol.cian.ru/sale/suburban/29955...,sevastopol,"участок, 4.1 сот., садоводство",,2300000,"Севастополь, р-н Гагаринский, мкр. Фиолент, Ав...",Арт. 61051791 Отличный ровный участок под заст...,2024-06-07 11:37:10.690720,1.0,False,2.3,2.300000,<1
2636,https://sevastopol.cian.ru/sale/suburban/30289...,sevastopol,"участок, 9 сот.",,3200000,"Севастополь, р-н Балаклавский, с. Гончарное",Продается участок в селе Гончарное одно из кра...,2024-06-10 11:18:48.884876,9.0,False,3.2,0.355556,8-20
2555,https://sevastopol.cian.ru/sale/suburban/30265...,sevastopol,"участок, 4 сот., ижс",,3000000,"Севастополь, р-н Нахимовский, с. Полюшко","Участок 4 cотки (ИЖC) в г. Сeвaстополь, Нахимo...",2024-06-10 11:18:48.884876,4.0,True,3.0,0.750000,2-4

---

In [7]:
obj_type = 'house'
files = [ f'{d}/{f}' for d in source[obj_type] for f in listdir(d) if f[-4:]=='.pkl' ]
display( len(files) )

cols = ['url','place','title','subtitle','price','address','description','ts',]

df_house = pd.concat([
        pd.read_pickle(f).drop_duplicates(['url'])
        for f in files
    ]).reset_index(drop=True)[cols]

display( len(df_house) )
display(df_house.sample(9))

10

6858

,url,place,title,subtitle,price,address,description,ts
6077,https://www.avito.ru/3836787020,sevastopol,"Дом 200 м² на участке 4,6 сот.",NaN,42990000,"ул. Челнокова, 20к2",Уникальное Предложение На Рынке Элитной Недвиж...,2024-06-07 11:52:05.094685
3508,https://www.avito.ru/3646884836,sevastopol,"Дом 90,5 м² на участке 15,2 сот.",NaN,5000000,с. Тенистое,"Продам дом, с частичной отделкой. Участок и до...",2024-06-10 11:33:36.811644
2085,https://sevastopol.cian.ru/sale/suburban/29728...,sevastopol,"Дом, 150 м², 8 сот.",,35000000,"Севастополь, р-н Нахимовский, мкр. Северная ст...",Дом 150 м² с двумя гостевыми домами на участке...,2024-06-07 11:42:40.789431
6288,https://www.avito.ru/3967850023,sevastopol,Дача 30 м² на участке 4 сот.,NaN,5300000,"садоводческое товарищество Херсонес, 1",Объект №2881. В Гагаринском районе в Казачьей ...,2024-06-07 11:52:05.094685
5800,https://www.avito.ru/3526950256,sevastopol,"Дом 338,8 м² на участке 7,5 сот.",NaN,25914000,"садоводческое товарищество Пилот, 103",Садовый дом с земельным участком находятся в г...,2024-06-07 11:52:05.094685
2888,https://sevastopol.cian.ru/sale/suburban/30287...,sevastopol,"Дом, 200 м², 5.01 сот., Садоводство",,10000000,"Севастополь, р-н Нахимовский, Сапун-гора СНТ, ...",В продаже отличный дом общей площадью 200 кв.м...,2024-06-07 11:42:40.789431
5805,https://www.avito.ru/4151600151,sevastopol,"Дом 80 м² на участке 4,1 сот.",NaN,8000000,садоводческое товарищество Кальфа-1,"Продам дом, 80 м2. Предчистовая отделка. Сдача...",2024-06-07 11:52:05.094685
552,https://sevastopol.cian.ru/sale/suburban/30207...,sevastopol,"Дом, 35 м², 4.83 сот., Садоводство",,2500000,"Севастополь, р-н Нахимовский, Черноморец-2 сад...","В продаже дача 35 м2 на земельном участке 4,83...",2024-06-10 11:23:47.056251
4409,https://www.avito.ru/3866348603,sevastopol,"Дом 40,2 м² на участке 4,4 сот.",NaN,6500000,"садоводческое товарищество Маяк-2, 50","Объект №499. Продается дом 40,2 м² на участке ...",2024-06-10 11:33:36.811644

In [8]:
# cols = ['title','address','place','url']
# df_house[ (df_house['place']=='sevastopol') & (df_house['address'].str.match(r'.*Судак.*')) ][cols]

In [9]:
from lib.cleaner import CleanerHouse

df_house = CleanerHouse().transform(df_house)

display( len(df_house) )
display(df_house.sample(9))

6858

,url,place,title,subtitle,price,address,description,ts,house_area,is_part,is_townhouse,is_SNT,land_area,priceM,land_size_category,house_size_category
6046,https://www.avito.ru/3471015332,sevastopol,дом 200 м² на участке 6 сот.,NaN,15990000,"Пластунский пр., 7",Продается добротный трехэтажный дом по пр. Пла...,2024-06-07 11:52:05.094685,200.0,False,False,False,6.0,15.990000,4-8,150-300
5885,https://www.avito.ru/3020658515,sevastopol,"дом 130 м² на участке 4,2 сот.",NaN,8500000,СТ Металлист,Стильный качественный дом в красном кирпиче по...,2024-06-07 11:52:05.094685,130.0,False,False,True,4.2,8.500000,4-8,70-150
223,https://sevastopol.cian.ru/sale/suburban/27040...,sevastopol,"дом, 95 м², 4 сот., садоводство",,7500999,"Севастополь, р-н Балаклавский, Надежда-1 садов...","Продается новый жилой дом в ТСН СНТ ""Надежда -...",2024-06-10 11:23:47.056251,95.0,False,False,True,4.0,7.500999,2-4,70-150
2462,https://sevastopol.cian.ru/sale/suburban/30068...,sevastopol,"дом, 70 м², 4 сот., садоводство",,6800000,"Севастополь, р-н Балаклавский, Импульс-1 садов...","Объект 140. Продается дом, с удобными подъездн...",2024-06-07 11:42:40.789431,70.0,False,False,True,4.0,6.800000,2-4,50-70
22,https://krym.cian.ru/sale/suburban/296549707/,sudak,"дом, 98 м², 10 сот., ижс",,11500000,"Республика Крым, Судак, улица Тополиная","Продам очень хороший дом газифицирован ю,вода ...",2024-06-10 11:25:21.743717,98.0,False,False,False,10.0,11.500000,8-20,70-150
1558,https://krym.cian.ru/sale/suburban/302073006/,sudak,"дом, 221 м², 6 сот., ижс",,20000000,"Республика Крым, Судак, Сувук-Сув кв-л","Продается жилой дом в городе Судак, квартал Су...",2024-06-07 11:44:14.693655,221.0,False,False,False,6.0,20.000000,4-8,150-300
2890,https://sevastopol.cian.ru/sale/suburban/30289...,sevastopol,"дом, 150 м², 4.84 сот., садоводство",,10000000,"Севастополь, р-н Нахимовский, Кача садоводческ...",Продаётся новый дом в уютном живописном месте....,2024-06-07 11:42:40.789431,150.0,False,False,True,84.0,10.000000,20+,70-150
1935,https://sevastopol.cian.ru/sale/suburban/28796...,sevastopol,"дом, 250 м², 7 сот.",,32000000,"Севастополь, р-н Гагаринский, Рыбак-2Б садовое...",Дом 250 м² на участке 7 соток Дом 250 м² на уч...,2024-06-07 11:42:40.789431,250.0,False,False,True,7.0,32.000000,4-8,150-300
2897,https://sevastopol.cian.ru/sale/suburban/29572...,sevastopol,"дом, 110 м², 1 сот., ижс",,9950000,"Севастополь, р-н Ленинский, улица Урусова, 9",Арт. 19586360 В продаже дом в ЖК Зеленый кварт...,2024-06-07 11:42:40.789431,110.0,False,False,False,1.0,9.950000,<1,70-150

---

## обновляем таблицу адресов

In [10]:
# !pip install geopy

In [11]:
from lib.locator import AddressTransformer

atr = AddressTransformer()

places = { 
# поле 'place' и название города
'bahchisaray': 'Бахчисарай,',
      'sudak': 'Судак,',
  'sevastopol': 'Севастополь,',
}

def address_norm(df,atr=atr):
    df['address_orig'] =  df['address']
    df['address'] =  df['address'].apply(atr.transform)
    df['place_'] =  df['place'].map(places)
    df['address'] = df[['address','place_']].apply(lambda d: d[0] if d[1] in d[0] else d[1]+','+d[0],axis=1) 
    df['address'] = (
        df['address']
        .str.replace(', ',',')
        .str.replace(',,',',')
        .str.replace('. ','.')
        .str.replace('\n',' ')
        .str.replace('  ',' ')
        .str.lower()
    )
    return df

In [12]:
df_flat = address_norm(df_flat)
df_land = address_norm(df_land)
df_house = address_norm(df_house)

/tmp/ipykernel_315295/776805188.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['address'] = df[['address','place_']].apply(lambda d: d[0] if d[1] in d[0] else d[1]+','+d[0],axis=1)
/tmp/ipykernel_315295/776805188.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['address'] = df[['address','place_']].apply(lambda d: d[0] if d[1] in d[0] else d[1]+','+d[0],axis=1)
/tmp/ipykernel_315295/776805188.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['address'] = df[['address','place_']].apply(lambda d: d[0] if d[1] in d[0] else d[1]+','+d[0],axis=1)

In [13]:
# df_flat[['address','address_orig']]

In [14]:
address = pd.concat([
        df_flat[['address','address_orig']],
        df_land[['address','address_orig']],
        df_house[['address','address_orig']],
    ]).drop_duplicates(['address']).reset_index(drop=True)

display(len(address))
display(address.sample(5))

7609

,address,address_orig
7372,"судак,ул.чалаш смаил",ул. Чалаш Смаил
2360,"севастополь,р-н нахимовский,мкр.горпищенко,ули...","Севастополь, р-н Нахимовский, мкр. Горпищенко,..."
6530,"севастополь,садоводческое товарищество рыбак-5...","садоводческое товарищество Рыбак-5, 203"
3313,"севастополь,р-н балаклавский,с.россошанка,улиц...","Севастополь, р-н Балаклавский, с. Россошанка, ..."
5946,"севастополь,р-н балаклавский,союз тсн,161","Севастополь, р-н Балаклавский, Союз ТСН, 161"

In [15]:
from os.path import exists as path_exists
loc_file_path = 'data/location.pkl' # таблица адресов

location = pd.DataFrame([],columns=['address','latitude','longitude',])
if path_exists( loc_file_path ):
    location = pd.read_pickle(loc_file_path).drop_duplicates(['address']).reset_index(drop=True)
    
display(len(location))
display(location.sample(5))

15317

                                                 address   latitude  longitude
1685                севастополь,большая морская улица,43  44.602133  33.523761
12113              севастополь,ул.генерала мельника,102а  44.582588  33.555813
10823                        севастополь,скифская ул.,37  44.555341  33.461337
6303   севастополь,р-н нахимовский,радар-с садовое то...  44.575904  33.576357
13032            севастополь,улица генерала коломийца,28  44.574793  33.529304

---

In [16]:
# def address_norm_(df):
#     df['address_orig'] =  df['address']
#     # df['address'] =  df['address'].apply(atr.transform)
#     df['address'] = (
#         df['address']
#         .str.replace(', ',',')
#         .str.replace(',,',',')
#         .str.replace('. ','.')
#         .str.replace('\n',' ')
#         .str.replace('  ',' ')
#         .str.lower()
#     )
#     return df

In [17]:
# location = address_norm_(location)

In [18]:
# location = location[['address','latitude','longitude']]

---

In [19]:
# собираем все адреса в один список
location = location.merge(
        address[['address']].drop_duplicates(),
        how='outer',
        on='address',
    ).drop_duplicates(['address']).reset_index(drop=True)

display(len(location))
display(location.sample(5))

15317

                                                 address   latitude  longitude
14819               севастополь,ш.генерала моргунова,119  44.556208  33.561859
9372   севастополь,садоводческое товарищество алькада...  44.663475  33.565748
5110   севастополь,р-н гагаринский,мкр.фиолент,авто с...  44.544613  33.455732
11263  севастополь,снт сапун-гора,улица лейтенанта ми...  44.568982  33.570725
2511                   севастополь,лазаревская улица ,11  44.600336  33.535529

In [20]:
display(len(location))
display(location['latitude'].isnull().sum())

15317

0

In [21]:
# собираем все адреса с геопозицией
location_def = location[~location['latitude'].isna()].reset_index(drop=True)
display(len(location_def))

# собираем все адреса без геопозиции
location_undef = location[location['latitude'].isna()][['address']].reset_index(drop=True)
display(len(location_undef))

15317

0

In [22]:
from tqdm.auto import tqdm
tqdm.pandas()

In [23]:
# from lib.locator import GeocoderSimpleOSM
from lib.locator import GeocoderYandex
from yandex_keys import keys

atr = AddressTransformer()
locator = GeocoderYandex(keys[0])
# locator = GeocoderSimpleOSM()

if len(location_undef)>0:
    # определяем координаты по строке адреса
    location_undef = location_undef.join( 
            location_undef['address'].progress_apply(locator.transform).apply(pd.Series) 
        ).dropna()     
    display(f'LocationUpdater: {len(location_undef)} new addresses found')
    location = pd.concat([location_def,location_undef]).reset_index(drop=True) 
    assert len(location)>0
    # location.to_pickle(loc_file_path)

In [24]:
display( len(location) )
display( location.sample(3) )

15317

                                                 address   latitude  longitude
731    республика крым,судак,садовое товарищество вет...  44.857465  35.001822
15210                                   судак,ул.аджибей  44.872018  34.982284
5985           севастополь,р-н ленинский,улица рябова,54   44.59594  33.516413

In [25]:
assert len(location)>0
location.to_pickle(loc_file_path)

## дополняем данные геометкой

In [26]:
display( len(df_flat) )
df_flat  = df_flat.merge(location,on='address').reset_index(drop=True) 
display( len(df_flat) )
display( df_flat.sample(3) )

8438

8438

,url,place,title,subtitle,price,address,description,ts,nrooms,floor,...,is_auction,is_openspace,is_roof,is_SNT,priceM,is_last_floor,address_orig,place_,latitude,longitude
7195,https://www.avito.ru/3756644608,sevastopol,"2-к. квартира, 57 м², 7/9 эт.",NaN,8300000,"севастополь,михайловская улица ,23",На продаже 2х комнатная квартира на Северной с...,2024-06-10 11:17:35.151941,2,7,...,False,False,False,False,8.30,False,"Михайловская улица , 23","Севастополь,",44.633123,33.531109
6505,https://www.avito.ru/2248385608,sevastopol,"апартаменты-студия, 27 м², 3/4 эт.",NaN,4350000,"севастополь,фиолентовское шоссе ,134 к4",Собственник. Торг. Срочно продаём в связи с пе...,2024-06-10 11:17:35.151941,0,3,...,False,False,False,False,4.35,False,"Фиолентовское шоссе , 134 к4","Севастополь,",44.505425,33.486418
3419,https://www.avito.ru/3392076630,sudak,"апартаменты-студия, 44,1 м², 5/8 эт.",NaN,9500000,"судак,апарт-отель «атлас араrt ноtеl & sра» ул...",Продaются просторные апаpтaменты 44.6 кв. М. С...,2024-06-07 12:05:27.509755,0,5,...,False,False,False,False,9.50,False,Апарт-отель «Атлас Apart Hotel & Spa»\n улица ...,"Судак,",34.025651,-6.839395

In [27]:
display( len(df_land) )
df_land  = df_land.merge(location,on='address').reset_index(drop=True) 
display( len(df_land) )
display( df_land.sample(3) )

7473

7473

,url,place,title,subtitle,price,address,description,ts,area,is_IJS,priceM,priceMU,area_size_category,address_orig,place_,latitude,longitude
2273,https://sevastopol.cian.ru/sale/suburban/29915...,sevastopol,"участок, 8.3 сот., садоводство",,2200000,"севастополь,р-н балаклавский,скала-2 садоводче...","Объект 605. Продается участок 8,29 соток СТ в ...",2024-06-10 11:18:48.884876,3.0,False,2.20,0.733333,2-4,"Севастополь, р-н Балаклавский, Скала-2 садовод...","Севастополь,",44.521829,33.520078
6530,https://www.avito.ru/3496331556,sevastopol,участок 6 сот. (ижс),NaN,1800000,"севастополь,ул.коли жартовского",Продаётся участок Ижс с панорамным видом! Не П...,2024-06-07 11:38:45.101812,6.0,True,1.80,0.300000,4-8,ул. Коли Жартовского,"Севастополь,",44.631539,33.562451
2400,https://sevastopol.cian.ru/sale/suburban/30217...,sevastopol,"участок, 7 сот., садоводство",,2590000,"севастополь,р-н нахимовский,качинский район ,и...","Арт. 65969335 Продается участок (7 соток), СНТ...",2024-06-10 11:18:48.884876,7.0,False,2.59,0.370000,4-8,"Севастополь, р-н Нахимовский, Качинский муници...","Севастополь,",44.794194,33.59065

In [28]:
display( len(df_house) )
df_house = df_house.merge(location,on='address').reset_index(drop=True) 
display( len(df_house) )
display( df_house.sample(3) )

6858

6858

,url,place,title,subtitle,price,address,description,ts,house_area,is_part,is_townhouse,is_SNT,land_area,priceM,land_size_category,house_size_category,address_orig,place_,latitude,longitude
2454,https://sevastopol.cian.ru/sale/suburban/30265...,sevastopol,"дом, 76 м², 4.04 сот., садоводство",,6800000,"севастополь,р-н гагаринский,мкр.фиолент,авто с...","Продается дом, общей площадью 76 кв.м., постро...",2024-06-07 11:42:40.789431,76.0,False,False,True,4.0,6.80,2-4,70-150,"Севастополь, р-н Гагаринский, мкр. Фиолент, Ав...","Севастополь,",44.536859,33.466089
2336,https://sevastopol.cian.ru/sale/suburban/30045...,sevastopol,"дом, 36,7 м², 6.94 сот., садоводство",,5950000,"севастополь,р-н гагаринский,авторемонтник садо...",В продаже дом 36 м2 на земельном участке 7 сот...,2024-06-07 11:42:40.789431,36.7,False,False,True,94.0,5.95,20+,30-50,"Севастополь, р-н Гагаринский, Авторемонтник са...","Севастополь,",44.571281,33.492194
6353,https://www.avito.ru/3536056196,sevastopol,"дом 260 м² на участке 4,9 сот.",NaN,9300000,"севастополь,снт ливада,12",Арт. 50696884 В продаже 2- этажный дом в Снт Л...,2024-06-07 11:52:05.094685,260.0,False,False,True,4.9,9.30,4-8,150-300,"СНТ Ливада, 12","Севастополь,",44.559843,33.436948

In [29]:
assert len(df_flat)>0
df_flat.to_pickle(f'{data_root_folder}/df_flat.pkl')

assert len(df_land)>0
df_land.to_pickle(f'{data_root_folder}/df_land.pkl')

assert len(df_house)>0
df_house.to_pickle(f'{data_root_folder}/df_house.pkl')