__собираем объявления о продаже недвижимости в одну таблицу__

_Evgeny S. Borisov <parser@mechanoid.su>_

In [1]:
!date

Пн 08 июл 2024 14:22:59 MSK

In [2]:
from os import listdir
import re
import pandas as pd

In [3]:
data_root_folder = 'data/2024'
source = {
         'flat':[data_root_folder+'/raw/flat/cian',data_root_folder+'/raw/flat/avito'],
        'house':[data_root_folder+'/raw/house/cian',data_root_folder+'/raw/house/avito'],
         'land':[data_root_folder+'/raw/land/cian',data_root_folder+'/raw/land/avito'],
    }

---

In [4]:
obj_type = 'flat'
files = [ f'{d}/{f}' for d in source[obj_type] for f in listdir(d) if f[-4:]=='.pkl' ]
display( len(files) )

cols = ['url','place','title','subtitle','price','address','description','ts',]

df_flat = pd.concat([
        pd.read_pickle(f).drop_duplicates(['url'])
        for f in files
    ]).reset_index(drop=True)[cols]

display( len(df_flat) )
display(df_flat.sample(9))

40

38661

,url,place,title,subtitle,price,address,description,ts
7722,https://sevastopol.cian.ru/sale/flat/282200042/,sevastopol,"2-комн. квартира, 101,7 м², 6/11 этаж",,49119000,"Севастополь, р-н Гагаринский, улица Парковая, 7",Продаётся 2-комнатная квартира в сданном доме ...,2024-06-17 08:17:58.573870
9992,https://sevastopol.cian.ru/sale/flat/295142976/,sevastopol,"Студия, 38 м², 3/3 этаж",,3100000,"Севастополь, р-н Гагаринский, мкр. Стрелецкая ...",Продаётся двух уровневая квартира в Гагаринско...,2024-06-10 11:06:41.395615
9199,https://sevastopol.cian.ru/sale/flat/292975848/,sevastopol,"Апартаменты-студия, 41 м², 4/16 этаж",,14400000,"Севастополь, р-н Гагаринский, улица Парковая, 7",Продаю отличный апартамент на 4 этаже в апартк...,2024-06-10 11:06:41.395615
10614,https://sevastopol.cian.ru/sale/flat/297854089/,sevastopol,"2-комн. квартира, ул. Токарева,18","2-комн. квартира, 76,7 м², 7/8 этаж",13250000,"Севастополь, р-н Ленинский, улица Токарева, 18",Продается двухкомнатная квартира в современном...,2024-06-13 11:09:09.770094
21070,https://www.avito.ru/3916689795,sevastopol,"1-к. квартира, 46,7 м², 5/9 эт.",NaN,7658800,"ЖК «Доброгород»\nул. Токарева, 8 этап, блок 4",Крупнейший в городе Севастополь семейный район...,2024-06-17 08:29:48.414678
1339,https://sevastopol.cian.ru/sale/flat/303269319/,sevastopol,"1-комн. квартира, 32 м², 1/2 этаж",,3200000,"Севастополь, р-н Балаклавский, бульвар Английс...",Продаётся квартира-студия с пропиской. В хорош...,2024-06-19 12:14:54.696204
37733,https://www.avito.ru/3544764863,sevastopol,"1-к. квартира, 37,9 м², 1/9 эт.",NaN,6900000,"пр-т Победы, 21А/2",Продам 1 комнатную квартиру в новом доме с диз...,2024-06-10 11:17:35.151941
5401,https://sevastopol.cian.ru/sale/flat/302944286/,sevastopol,"2-комн. квартира, 54 м², 11/12 этаж",,8150000,"Севастополь, р-н Ленинский, мкр. Острякова, пр...","Продается двухкомнатная квартира ""улучшенной п...",2024-06-11 10:13:23.305322
28235,https://www.avito.ru/3256635216,sevastopol,"1-к. квартира, 33 м², 10/10 эт.",NaN,4800000,"ул. Астана Кесаева, 7/1",Продается однокомнатная квартира в Гагаринском...,2024-06-14 13:06:45.993553

In [5]:
from lib.cleaner import CleanerFlat

df_flat = CleanerFlat().transform(df_flat)
display( len(df_flat) )
display(df_flat.sample(9))

38661

,url,place,title,subtitle,price,address,description,ts,nrooms,floor,...,area,is_studio,is_apartment,is_part,is_auction,is_openspace,is_roof,is_SNT,priceM,is_last_floor
5117,https://sevastopol.cian.ru/sale/flat/302131889/,sevastopol,"2-комн. квартира, 72,35 м², 4/10 этаж",,26753600,"Севастополь, р-н Гагаринский, улица Парковая, 15",,2024-06-11 10:13:23.305322,0,4,...,72.35,False,False,False,False,False,False,False,26.7536,False
2871,https://sevastopol.cian.ru/sale/flat/301310943/,sevastopol,"1-комн. квартира, 31,1 м², 2/5 этаж",,4600000,"Севастополь, р-н Балаклавский, посёлок Сахарна...","Однокомнатная квартира 31.11кв.м, на 2/5 этаже...",2024-06-07 11:33:12.800097,0,2,...,31.10,False,False,False,False,False,False,False,4.6000,False
19481,https://www.avito.ru/2726530445,sudak,"2-к. квартира, 42 м², 3/5 эт.",NaN,6700000,"улица Истрашкина, 15",Продам двухкомнатную квартиру с шикарным видом...,2024-06-24 13:02:17.555604,2,3,...,42.00,False,False,False,False,False,False,False,6.7000,False
26552,https://www.avito.ru/3577546926,sevastopol,"2-к. апартаменты, 54 м², 3/4 эт.",NaN,7500000,"улица Лётчиков, 3Е",Продаются апартаменты у самого моря в Бухте Ом...,2024-07-08 13:29:07.581057,2,3,...,54.00,False,True,False,False,False,False,False,7.5000,False
23161,https://www.avito.ru/2518018765,sevastopol,"1-к. апартаменты, 46 м², 5/6 эт.",NaN,4900000,"улица Адмирала Фадеева, 21Б",У самого синего Моря с белоснежными Яхтами! Пр...,2024-06-19 12:22:29.452737,1,5,...,46.00,False,True,False,False,False,False,False,4.9000,False
13145,https://sevastopol.cian.ru/sale/flat/301490713/,sevastopol,"1-комн. квартира, 30,2 м², 5/5 этаж",,5800000,"Севастополь, р-н Ленинский, улица Мечникова, 5",Продам 1-комнатную квартиру в Ленинском районе...,2024-06-18 10:45:27.403294,0,5,...,30.20,False,False,False,False,False,False,False,5.8000,True
18671,https://www.avito.ru/3769368643,sevastopol,"3-к. квартира, 56 м², 2/5 эт.",NaN,8400000,"улица Адмирала Октябрьского, 14","Трехкомнатная квартира 56 м2, на 2/ 5 этаже до...",2024-06-24 12:47:24.649620,3,2,...,56.00,False,False,False,False,False,False,False,8.4000,False
1430,https://sevastopol.cian.ru/sale/flat/302664777/,sevastopol,"1-комн. апартаменты, 14,9 м², 1/4 этаж",,4500000,"Севастополь, р-н Нахимовский, село Орловка, шо...",Продам АПАРТАМЕНТЫ на 1 этаже 4-х этажного дом...,2024-06-19 12:14:54.696204,0,1,...,14.90,False,True,False,False,False,False,False,4.5000,False
7854,https://sevastopol.cian.ru/sale/flat/303685359/,sevastopol,видовая 1 комнатная у моря!,"1-комн. квартира, 43 м², 7/11 этаж",8990000,"Севастополь, р-н Гагаринский, мкр. Омега, прос...",Продам ВИДОВУЮ квартиру с новым качественным р...,2024-07-08 13:17:33.822433,0,0,...,0.00,False,False,False,False,False,False,False,8.9900,True

---

In [6]:
obj_type = 'land'
files = [ f'{d}/{f}' for d in source[obj_type] for f in listdir(d) if f[-4:]=='.pkl' ]
display( len(files) )

cols = ['url','place','title','subtitle','price','address','description','ts',]

df_land = pd.concat([
        pd.read_pickle(f).drop_duplicates(['url'])
        for f in files
    ]).reset_index(drop=True)[cols]

display( len(df_land) )
display(df_land.sample(9))

50

34591

,url,place,title,subtitle,price,address,description,ts
24044,https://www.avito.ru/2476342385,sevastopol,"Участок 9,3 сот. (СНТ, ДНП)",NaN,2000000,"пос. Кача, ул. Авиаторов, 1Г/17",Собственник! Продается классный участок в Каче...,2024-06-14 13:13:27.377070
20176,https://www.avito.ru/4274515717,bahchisaray,"Участок 30 га (СНТ, ДНП)",NaN,30000000,с. Холмовка,"Продам видовые, земельные участки в респ. Крым...",2024-06-07 12:09:12.165236
15237,https://www.avito.ru/4102353854,sevastopol,Участок 8 сот. (ИЖС),NaN,5200000,с. Полюшко,В продаже два смежных участка по 4 сотки=8сото...,2024-06-17 08:36:13.464806
27742,https://www.avito.ru/2315601392,bahchisaray,"Участок 1,5 га (СНТ, ДНП)",NaN,600000,с. Белокаменное,"Сельхоззначения участок 1,5 гектара. С понарам...",2024-06-24 13:05:30.092315
30973,https://www.avito.ru/3795949698,sevastopol,Участок 10 сот. (ИЖС),NaN,5400000,Редутная ул.,"Учаcток 10 сoток (Ижс) в г. Севастополь, Редут...",2024-06-11 10:32:52.971878
10166,https://sevastopol.cian.ru/sale/suburban/30120...,sevastopol,"Участок, 4 сот., Садоводство",,3300000,"Севастополь, р-н Гагаринский, Икар-2 садоводче...",Продам участок площадью 4 сотки в Гагаринском ...,2024-06-18 10:50:11.786732
22542,https://www.avito.ru/588056794,bahchisaray,"Участок 1 сот. (СНТ, ДНП)",NaN,800000,с. Долинное,Участок находится между с. Фурмановка и с. Кра...,2024-06-17 08:47:28.297455
21005,https://www.avito.ru/4513812185,sevastopol,Участок 10 сот. (ИЖС),NaN,4600000,"Крепостное ш., 23к18","Объект №381. Доброго времени суток, предложени...",2024-07-08 13:36:06.464523
21677,https://www.avito.ru/2375997769,sevastopol,"Участок 5,1 сот. (ИЖС)",NaN,2900000,ТСН Родник,Продам Земельный Участок в черте города! СТ Ро...,2024-07-08 13:36:06.464523

In [7]:
from lib.cleaner import CleanerLand

df_land = CleanerLand().transform(df_land)

display( len(df_land) )
display(df_land.sample(9))

34591

,url,place,title,subtitle,price,address,description,ts,area,is_IJS,priceM,priceMU,area_size_category
14083,https://www.avito.ru/3958136733,bahchisaray,участок 10 сот. (ижс),NaN,3500000,с. Трудовое,Предлагаем Вашему вниманию земельный участок И...,2024-06-14 13:24:08.712517,10.0,True,3.50,0.350000,8-12
15045,https://www.avito.ru/4025934045,sevastopol,"участок 10,8 сот. (снт, днп)",NaN,9200000,"ТСН СНТ Зеленстрой, 9","Объект №814. Продается участок 10,8 соток Идс ...",2024-06-17 08:36:13.464806,10.8,False,9.20,0.851852,8-12
30814,https://www.avito.ru/2238704970,sevastopol,"участок 6,7 сот. (ижс)",NaN,3700000,"с. Орловка, Озёрная ул., 36","Продается участок 6,7 cоток под Ижс в Севастоп...",2024-06-11 10:32:52.971878,6.7,True,3.70,0.552239,4-8
14772,https://www.avito.ru/4137876011,sevastopol,"участок 4,3 га (снт, днп)",NaN,1090000,с. Вилино,"Продаю, земельный пай для сельского хозяйства ...",2024-06-17 08:36:13.464806,430.0,False,1.09,0.002535,20+
26098,https://www.avito.ru/2021867129,sevastopol,участок 10 сот. (ижс),NaN,4000000,Аэродромное ш.,Продаётся право пользование земельным участоко...,2024-06-13 11:24:39.283050,10.0,True,4.00,0.400000,8-12
6234,https://sevastopol.cian.ru/sale/suburban/30279...,sevastopol,"участок, 4.09 сот., садоводство",,2300000,"Севастополь, р-н Ленинский, Тополек садовое то...",Продается участок 4 сотки прямо в сердце Севас...,2024-06-24 12:40:23.850839,9.0,False,2.30,0.255556,8-12
12879,https://sevastopol.cian.ru/sale/suburban/30054...,sevastopol,"участок, 5.2 сот., ижс",,2000000,"Севастополь, р-н Балаклавский, Горный дачный п...","Продаю участок в живописном, спокойном и в то ...",2024-06-10 11:18:48.884876,2.0,True,2.00,1.000000,1-2
29313,https://www.avito.ru/2404903489,sudak,участок 25 сот. (ижс),NaN,3600000,с. Краснокаменка,"Предлагается к продаже земельный участок, площ...",2024-07-08 13:45:55.868589,25.0,True,3.60,0.144000,20+
14755,https://www.avito.ru/3609031708,sevastopol,участок 4 сот. (ижс),NaN,2800000,"с. Тыловое, Ялтинская ул., 4",Объект №14601. В продаже ровный земельный учас...,2024-06-17 08:36:13.464806,4.0,True,2.80,0.700000,2-4

---

In [8]:
obj_type = 'house'
files = [ f'{d}/{f}' for d in source[obj_type] for f in listdir(d) if f[-4:]=='.pkl' ]
display( len(files) )

cols = ['url','place','title','subtitle','price','address','description','ts',]

df_house = pd.concat([
        pd.read_pickle(f).drop_duplicates(['url'])
        for f in files
    ]).reset_index(drop=True)[cols]

display( len(df_house) )
display(df_house.sample(9))

50

32965

,url,place,title,subtitle,price,address,description,ts
20843,https://www.avito.ru/3736842016,sevastopol,"Дом 148,7 м² на участке 4 сот.",NaN,8500000,садоводческое товарищество Таврия,Гагаринский район! Дом 148м. Кв на участке 400...,2024-07-08 13:43:40.723717
32800,https://www.avito.ru/3707881807,sudak,"Дача 192,5 м² на участке 5,2 сот.",NaN,8000000,"с. Миндальное, СОТ Капсель, 65",Дом оформлен и поставлен на кадастровый учет в...,2024-06-10 11:36:34.764133
30068,https://www.avito.ru/4024891184,bahchisaray,Дом 75 м² на участке 6 сот.,NaN,6809300,"ул. Фрунзе, 2",Предлагаем приобрести Дом по цене Квартиры от ...,2024-07-08 13:49:26.679246
24983,https://www.avito.ru/4083988953,sevastopol,Дом 38 м² на участке 2 сот.,NaN,4150000,СТ Дельфин,Продам в Ст Дельфин пол дома. Состояние заезжа...,2024-06-24 13:01:06.410833
13767,https://sevastopol.cian.ru/sale/suburban/29898...,sevastopol,"Дом, 205 м², 4 сот., ИЖС",,10500000,"Севастополь, р-н Гагаринский, мкр. Фиолент, Ра...",Объект 16606. Продам дом в Севастополе. Двухэт...,2024-06-14 13:06:13.997742
27596,https://www.avito.ru/3671035788,sevastopol,Дом 91 м² на участке 9 сот.,NaN,8200000,"с. Штурмовое, Ноябрьский пер.",Продается в с. Штурмовое жилой 2-х эт. Дом по ...,2024-06-14 13:20:44.492111
30700,https://www.avito.ru/3907007093,sudak,Дом 298 м² на участке 12 сот.,NaN,23700000,"с. Миндальное, СНТ Солнечная Долина, Мирный пе...",Продам Ранчо! Работающий бизнес! Дом находитьс...,2024-06-07 12:06:57.201236
20734,https://www.avito.ru/3807154941,sevastopol,"Дом 85,8 м² на участке 4,7 сот.",NaN,6800000,"садовое товарищество Чайка-1, 136","Если не дозвонились, пишите в сообщении. Я пер...",2024-07-08 13:43:40.723717
19527,https://www.avito.ru/4089649931,bahchisaray,Дом 80 м² на участке 12 сот.,NaN,1500000,садоводческое некоммерческое товарищество Садо...,Продам жилую дачу. С. Маловидное снт «Садовод»...,2024-06-07 12:10:08.505306

In [9]:
# cols = ['title','address','place','url']
# df_house[ (df_house['place']=='sevastopol') & (df_house['address'].str.match(r'.*Судак.*')) ][cols]

In [10]:
from lib.cleaner import CleanerHouse

df_house = CleanerHouse().transform(df_house)

display( len(df_house) )
display(df_house.sample(9))

32965

,url,place,title,subtitle,price,address,description,ts,house_area,is_part,is_townhouse,is_SNT,land_area,priceM,land_size_category,house_size_category
31236,https://www.avito.ru/3935409390,sudak,"дом 46,7 м² на участке 2,7 сот.",NaN,14000000,Санаторный пер.,Продаётся одноэтажный дом 46 квадратов на учас...,2024-06-14 13:23:10.259083,46.7,False,False,False,2.7,14.00,2-4,30-50
8541,https://sevastopol.cian.ru/sale/suburban/30289...,sevastopol,"дом, 115 м², 4 сот., садоводство",,7000000,"Севастополь, р-н Нахимовский, Качинский муници...",Продам дом на черноморском побережье с видом н...,2024-06-19 12:37:23.275933,115.0,False,False,True,4.0,7.00,2-4,110-180
6172,https://krym.cian.ru/sale/suburban/297645286/,sudak,"дом, 195,8 м², 5.2 сот., ижс",,28000000,"Республика Крым, Судак, улица Приморская, 48А",Продаётся современный жилой дом 2023 года пост...,2024-06-10 11:25:21.743717,195.8,False,False,False,2.0,28.00,1-2,180-300
17929,https://www.avito.ru/4090243584,sevastopol,дом 60 м² на участке 6 сот.,NaN,5380000,"СНТ Сапун-гора, 1380","Продам жилой дом на участке 6,3 сот. На первой...",2024-06-13 11:32:06.964835,60.0,False,False,True,6.0,5.38,4-8,50-70
27327,https://www.avito.ru/3891262414,sevastopol,дом 120 м² на участке 4 сот.,NaN,8500000,"Ясеневая ул., 57",У каждого человeкa свои ценности в жизни. Для ...,2024-06-14 13:20:44.492111,120.0,False,False,False,4.0,8.50,2-4,110-180
4524,https://sevastopol.cian.ru/sale/suburban/24253...,sevastopol,"дом, 425 м², 7.5 сот.",,99900000,"Севастополь, р-н Ленинский, мкр. 5-й километр,...","К продаже представлен стильный, респектабельны...",2024-06-13 11:22:19.008525,425.0,False,False,False,5.0,99.90,4-8,300+
1885,https://sevastopol.cian.ru/sale/suburban/29302...,sevastopol,"дом, 114,3 м², 3 сот., садоводство",,10900000,"Севастополь, р-н Балаклавский, Энергетик-2 сад...","Дом 114,3 м² на участке 4 сотки Дом 114,3 м² н...",2024-06-17 08:27:31.304082,114.3,False,False,True,3.0,10.90,2-4,110-180
1774,https://sevastopol.cian.ru/sale/suburban/27817...,sevastopol,"дом, 192 м², 5 сот.",,18950000,"Севастополь, р-н Нахимовский, улица 2-я Беговая",Дом 192 м2 на участке 5 соток Дом 192 м2 на уч...,2024-06-17 08:27:31.304082,192.0,False,False,False,5.0,18.95,4-8,180-300
1466,https://sevastopol.cian.ru/sale/suburban/28460...,sevastopol,"дом, 107,2 м², 2 сот.",,12000000,"Севастополь, р-н Ленинский, улица Гусева, 1",#### В центре города Севастополь в тихом частн...,2024-06-11 10:23:05.308675,107.2,False,False,False,2.0,12.00,1-2,70-110

---

## обновляем таблицу адресов

In [11]:
# !pip install geopy

In [12]:
from lib.locator import AddressTransformer

atr = AddressTransformer()

places = { 
# поле 'place' и название города
'bahchisaray': 'Бахчисарай,',
      'sudak': 'Судак,',
  'sevastopol': 'Севастополь,',
}

def address_norm(df,atr=atr):
    df['address_orig'] =  df['address']
    df['address'] =  df['address'].apply(atr.transform)
    df['place_'] =  df['place'].map(places)
    df['address'] = df[['address','place_']].apply(lambda d: d[0] if d[1] in d[0] else d[1]+','+d[0],axis=1) 
    df['address'] = (
        df['address']
        .str.replace(', ',',')
        .str.replace(',,',',')
        .str.replace('. ','.')
        .str.replace('\n',' ')
        .str.replace('  ',' ')
        .str.lower()
    )
    return df

In [13]:
df_flat = address_norm(df_flat)
df_land = address_norm(df_land)
df_house = address_norm(df_house)

/tmp/ipykernel_132927/776805188.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['address'] = df[['address','place_']].apply(lambda d: d[0] if d[1] in d[0] else d[1]+','+d[0],axis=1)
/tmp/ipykernel_132927/776805188.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['address'] = df[['address','place_']].apply(lambda d: d[0] if d[1] in d[0] else d[1]+','+d[0],axis=1)
/tmp/ipykernel_132927/776805188.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['address'] = df[['address','place_']].apply(lambda d: d[0] if d[1] in d[0] else d[1]+','+d[0],axis=1)

In [14]:
# df_flat[['address','address_orig']]

In [15]:
address = pd.concat([
        df_flat[['address','address_orig']],
        df_land[['address','address_orig']],
        df_house[['address','address_orig']],
    ]).drop_duplicates(['address']).reset_index(drop=True)

display(len(address))
display(address.sample(5))

10546

,address,address_orig
8387,"республика крым,судак,улица ароматная,2","Республика Крым, Судак, улица Ароматная, 2"
3426,"севастополь,р-н балаклавский,с.тыловое,улица л...","Севастополь, р-н Балаклавский, с. Тыловое, ули..."
8016,"севастополь,р-н нахимовский,мкр.бартеньевка,ул...","Севастополь, р-н Нахимовский, мкр. Бартеньевка..."
8750,"севастополь,тсн ст фиолент,1207","ТСН СТ Фиолент, 1207"
7972,"севастополь,р-н гагаринский,улица отрадная,68","Севастополь, р-н Гагаринский, улица Отрадная, 68"

In [16]:
from os.path import exists as path_exists
loc_file_path = 'data/location.pkl' # таблица адресов

location = pd.DataFrame([],columns=['address','latitude','longitude',])
if path_exists( loc_file_path ):
    location = pd.read_pickle(loc_file_path).drop_duplicates(['address']).reset_index(drop=True)
    
display(len(location))
display(location.sample(5))

16695

                                                 address   latitude  longitude
13472                         севастополь,ул.декабристов  44.596864  33.497898
7646   севастополь,район балаклавский,инкерман,улица ...  44.615962  33.603073
13671                  севастополь,ул.николая ехлакова,2  44.602583  33.578855
13584                           севастополь,ул.ленина,41  44.603256  33.526824
9097   севастополь,район нахимовский,улица горпищенко...  44.579776  33.579007

---

In [17]:
# def address_norm_(df):
#     df['address_orig'] =  df['address']
#     # df['address'] =  df['address'].apply(atr.transform)
#     df['address'] = (
#         df['address']
#         .str.replace(', ',',')
#         .str.replace(',,',',')
#         .str.replace('. ','.')
#         .str.replace('\n',' ')
#         .str.replace('  ',' ')
#         .str.lower()
#     )
#     return df

In [18]:
# location = address_norm_(location)

In [19]:
# location = location[['address','latitude','longitude']]

---

In [20]:
# собираем все адреса в один список
location = location.merge(
        address[['address']].drop_duplicates(),
        how='outer',
        on='address',
    ).drop_duplicates(['address']).reset_index(drop=True)

display(len(location))
display(location.sample(5))

17557

                                                 address   latitude  longitude
13313    севастополь,ст энергетик-2,ул.летчика кирсанова  44.574357   33.59347
13951                          севастополь,узловая улица  44.593822   33.60381
13820                  севастополь,тсн ст морзаводец,256  44.544626  33.569602
2773   севастополь,ленинский район ,жилой комплекс до...  44.579474  33.505983
2926                     севастополь,митридатская ул.,12  44.560685  33.464805

In [21]:
display(len(location))
display(location['latitude'].isnull().sum())

17557

862

In [22]:
# собираем все адреса с геопозицией
location_def = location[~location['latitude'].isna()].reset_index(drop=True)
display(len(location_def))

# собираем все адреса без геопозиции
location_undef = location[location['latitude'].isna()][['address']].reset_index(drop=True)
display(len(location_undef))

16695

862

In [23]:
display(location_undef)

                                       address
0                           бахчисарай,35н-806
1                 бахчисарай,гурзуфская ул.,83
2                  бахчисарай,загородная ул.,1
3                      бахчисарай,новая ул.,15
4    бахчисарай,пгт.куйбышево,колхозная ул.,12
..                                         ...
857                     судак,ул.якова кушнира
858                    судак,улица бирюзова,22
859                      судак,улица ленина,34
860                       судак,улица чехова,1
861                  судак,южнобережная ул.,76

[862 rows x 1 columns]

In [24]:
from tqdm.auto import tqdm
tqdm.pandas()

In [25]:
# from lib.locator import GeocoderSimpleOSM
from lib.locator import GeocoderYandex
from yandex_keys import keys

atr = AddressTransformer()
locator = GeocoderYandex(keys[0])
# locator = GeocoderSimpleOSM()

if len(location_undef)>0:
    # определяем координаты по строке адреса
    location_undef = location_undef.join( 
            location_undef['address'].progress_apply(locator.transform).apply(pd.Series) 
        ).dropna()     
    display(f'LocationUpdater: {len(location_undef)} new addresses found')
    location = pd.concat([location_def,location_undef]).reset_index(drop=True) 
    assert len(location)>0
    # location.to_pickle(loc_file_path)

  0%|          | 0/862 [00:00<?, ?it/s]

'LocationUpdater: 862 new addresses found'

In [26]:
display( len(location) )
display( location.sample(3) )

17557

                                                 address   latitude  longitude
14561           севастополь,улица военных строителей,5к3  44.566786   33.40689
1992   севастополь,гагаринский район ,казачья бухта,р...  44.565713  33.409603
14931              севастополь,улица дмитрия ульянова,20  44.605734  33.493066

In [27]:
assert len(location)>0
location.to_pickle(loc_file_path)

## дополняем данные геометкой

In [28]:
display( len(df_flat) )
df_flat  = df_flat.merge(location,on='address').reset_index(drop=True) 
display( len(df_flat) )
display( df_flat.sample(3) )

38661

38661

,url,place,title,subtitle,price,address,description,ts,nrooms,floor,...,is_auction,is_openspace,is_roof,is_SNT,priceM,is_last_floor,address_orig,place_,latitude,longitude
4740,https://sevastopol.cian.ru/sale/flat/303095429/,sevastopol,"2-комн. квартира, 48,5 м², 2/5 этаж",,6500000,"севастополь,р-н ленинский,мкр.острякова,улица ...",Продам двухкомнатную брежневку на 2м этаже пят...,2024-06-14 12:56:14.435965,0,2,...,False,False,False,False,6.50000,False,"Севастополь, р-н Ленинский, мкр. Острякова, ул...","Севастополь,",44.569335,33.527588
19361,https://www.avito.ru/3955755114,sudak,"2-к. апартаменты, 55,6 м², 3/8 эт.",NaN,14720750,"судак,апарт-отель «атлас араrt ноtеl & sра» ул...",В апарт-комплексе уже сдана и введена в эксплу...,2024-06-10 11:35:05.787844,2,3,...,False,False,False,False,14.72075,False,Апарт-отель «Атлас Apart Hotel & Spa»\n улица ...,"Судак,",34.025651,-6.839395
29381,https://www.avito.ru/2329220416,sevastopol,"1-к. квартира, 46,5 м², 3/6 эт.",NaN,9000000,"севастополь,улица астана кесаева,14","Однокомнатная квартира 46,5 м2 на 3/6 этаже до...",2024-06-14 13:06:45.993553,1,3,...,False,False,False,False,9.00000,False,"улица Астана Кесаева, 14","Севастополь,",44.588173,33.45557

In [29]:
display( len(df_land) )
df_land  = df_land.merge(location,on='address').reset_index(drop=True) 
display( len(df_land) )
display( df_land.sample(3) )

34591

34591

,url,place,title,subtitle,price,address,description,ts,area,is_IJS,priceM,priceMU,area_size_category,address_orig,place_,latitude,longitude
22265,https://www.avito.ru/4031932861,sevastopol,"участок 8,7 сот. (ижс)",NaN,10000000,"севастополь,с.ушаково,ул.котляревского,6","Участок 8,7 соток (Ижс) в г. Севастополь, Лени...",2024-07-08 13:36:06.464523,8.7,True,10.0,1.149425,8-12,"с. Ушаково, ул. Котляревского, 6","Севастополь,",44.542693,33.546228
7980,https://sevastopol.cian.ru/sale/suburban/29661...,sevastopol,"участок, 7.8 сот., ижс",,7000000,"севастополь,р-н балаклавский,союз тсн,6а","Участок 8 соток (СТ) в г. Севастополь, Балакла...",2024-06-19 12:23:33.870565,8.0,True,7.0,0.875000,4-8,"Севастополь, р-н Балаклавский, Союз ТСН, 6А","Севастополь,",44.509784,33.521336
3072,https://krym.cian.ru/sale/suburban/278610899/,sudak,"участок, 10.4 сот., садоводство",,4500000,"судак,республика крым,судак городской округ,с....",Продается земельный участок в 300 метрах от пл...,2024-07-08 14:07:49.322937,4.0,False,4.5,1.125000,2-4,"Республика Крым, Судак городской округ, с. При...","Судак,",44.859963,35.135078

In [30]:
display( len(df_house) )
df_house = df_house.merge(location,on='address').reset_index(drop=True) 
display( len(df_house) )
display( df_house.sample(3) )

32965

32965

,url,place,title,subtitle,price,address,description,ts,house_area,is_part,is_townhouse,is_SNT,land_area,priceM,land_size_category,house_size_category,address_orig,place_,latitude,longitude
11018,https://sevastopol.cian.ru/sale/suburban/28856...,sevastopol,хозяин продает дом,"Дом, 110 м², 6 сот., ИЖС",10300000,"севастополь,р-н балаклавский,родник тсн,1б/6",Продам одноэтажный дом новой постройки. В доме...,2024-07-08 14:05:28.543820,0.0,False,False,True,0.0,10.3,NaN,NaN,"Севастополь, р-н Балаклавский, Родник ТСН, 1Б/6","Севастополь,",44.542712,33.556864
6917,https://sevastopol.cian.ru/sale/suburban/29826...,sevastopol,"дом, 169,2 м², 2.9 сот., садоводство",,6200000,"севастополь,р-н ленинский,тополек садовое това...",Объект 1437. K продaжe 1/2 дома на участкe 3 с...,2024-06-10 11:23:47.056251,169.2,True,False,True,9.0,6.2,8-12,110-180,"Севастополь, р-н Ленинский, Тополек садовое то...","Севастополь,",44.561391,33.533723
4897,https://sevastopol.cian.ru/sale/suburban/29022...,sevastopol,"дом, 210 м², 5 сот.",,34500000,"севастополь,р-н гагаринский,рыбак-5 садовое то...",Дом 210 м² на участке 5 соток Дом 210 м² на уч...,2024-06-13 11:22:19.008525,210.0,False,False,True,5.0,34.5,4-8,180-300,"Севастополь, р-н Гагаринский, Рыбак-5 садовое ...","Севастополь,",44.574575,33.454734

In [31]:
def address_filter(df):
    #           46.319437, 33.911048
    #
    # 45.402617, 32.455625 |  45.545301, 36.684702
    #
    #          44.320887, 33.917013

    df['latitude'] = pd.to_numeric( df['latitude'], errors='coerce' )
    df['longitude'] = pd.to_numeric( df['longitude'], errors='coerce' )

    df = df.query('(32.4<longitude<36.7) & (44.3<latitude<46.4)') 

    df.loc[ df['url']=='https://avito.ru/2322251740', ['latitude','longitude']] = None

    df.loc[ df['address']=='Севастополь,Чёрное море', ['latitude','longitude'] ] = None
    df.loc[ df['address'].str.lower().str.match('чёрное море'), ['latitude','longitude'] ] = None 

    df.loc[ df['address']=='квартал Старый Город', 'place'] = 'turkie'
    df.loc[ df['address'].str.lower().str.match('анталья'), 'place' ] = 'turkie' 

    df.loc[ df['address'].str.lower().str.match(r'.*бахчисарай.*'), 'place' ] = 'bahchisaray'
    df.loc[ df['address'].str.lower().str.match(r'.*севастополь,.*'), 'place' ] = 'sevastopol'

    df.loc[ df['address'].str.lower().str.match(r'.*мысовское.*'), 'place' ] = 'kerch'
    df.loc[ df['address'].str.lower().str.match(r'.*алушта.*'), 'place' ] = 'alushta'
    df.loc[ df['address'].str.lower().str.match(r'.*гурзуф.*'), 'place' ] = 'gurzuf'

    df.loc[ df['address'].str.lower().str.match(r'.*с.лучистое.*'), 'place' ] = 'alushta'
    df.loc[ df['address'].str.lower().str.match(r'.*снт солнечная долина.*'), 'place' ] = 'sudak'
    df.loc[ df['address'].str.lower().str.match(r'.*пгт.новоозёрное.*'), 'place' ] = 'evpatoria'

    df.loc[ df['address'].str.lower().str.match(r'.*с.мирное.*'), 'place' ] = 'simferopol'
    df.loc[ df['address'].str.lower().str.match(r'.*тсн аэрофлот.*'), 'place' ] = 'simferopol'

    df.loc[ df['address'].str.lower().str.match(r'.*семисот.*'), 'place' ] = 'kerch'

    df.loc[ df['address'].str.lower().str.match(r'.*ялта.*') , 'place' ] = 'yalta'
    df.loc[ df['address'].str.lower().str.match(r'.*феодосия.*') , 'place' ] = 'feodosia'
    df.loc[ df['address'].str.lower().str.match(r'.*окуневка.*') , 'place' ] = 'tarkhankut'
    df.loc[ df['address'].str.lower().str.match(r'.*заветное.*') , 'place' ] = 'kerch'
    df.loc[ df['address'].str.lower().str.match(r'.*евпатория.*') , 'place' ] = 'evpatoria'
    df.loc[ df['address'].str.lower().str.match(r'.*симферопольский район.*'), 'place' ] = 'simferopol'

    df = df.dropna(subset=['latitude','longitude'])
    
    return df

In [32]:
display(len(df_flat))
df_flat = address_filter(df_flat)
display(len(df_flat))

display(len(df_land))
df_land = address_filter(df_land)
display(len(df_land))

display(len(df_house))
df_house = address_filter(df_house)
display(len(df_house))

38661

38247

34591

34576

32965

32964

In [33]:
assert len(df_flat)>0
df_flat.to_pickle(f'{data_root_folder}/df_flat.pkl')

assert len(df_land)>0
df_land.to_pickle(f'{data_root_folder}/df_land.pkl')

assert len(df_house)>0
df_house.to_pickle(f'{data_root_folder}/df_house.pkl')

In [34]:
!date

Пн 08 июл 2024 14:29:38 MSK