__собираем объявления о продаже недвижимости в одну таблицу__

_Evgeny S. Borisov <parser@mechanoid.su>_

In [1]:
!date

Вт 15 окт 2024 10:54:30 MSK

In [2]:
from os import listdir
import re
import pandas as pd

In [3]:
data_root_folder = 'data/2024'
source = {
         'flat':[data_root_folder+'/raw/flat/cian',data_root_folder+'/raw/flat/avito'],
        'house':[data_root_folder+'/raw/house/cian',data_root_folder+'/raw/house/avito'],
         'land':[data_root_folder+'/raw/land/cian',data_root_folder+'/raw/land/avito'],
    }

---

In [4]:
obj_type = 'flat'
files = [ f'{d}/{f}' for d in source[obj_type] for f in listdir(d) if f[-4:]=='.pkl' ]
display( len(files) )

cols = ['url','place','title','subtitle','price','address','description','ts',]

df_flat = pd.concat([
        pd.read_pickle(f).drop_duplicates(['url'])
        for f in files
    ]).reset_index(drop=True)[cols]

display( len(df_flat) )
display(df_flat.sample(9))

96

86570

,url,place,title,subtitle,price,address,description,ts
72221,https://www.avito.ru/4183672690,sevastopol,"2-к. квартира, 42,2 м², 2/5 эт.",NaN,6700000,"пр-т Генерала Острякова, 60","Продам 2-х комнатную квартиру, на 2-м этаже, к...",2024-06-14 13:06:45.993553
42911,https://www.avito.ru/3993121708,sevastopol,"1-к. квартира, 40 м², 1/10 эт.",NaN,9800000,"пр-т Октябрьской Революции, 20","Однокомнатная квартира 40 м2, на 1/10 этаже до...",2024-09-03 13:30:33.358345
8651,https://krym.cian.ru/sale/flat/306563245/,sudak,"2-комн. квартира, 69,6 м², 4/8 этаж",,15000000,"Республика Крым, Судак, переулок Серный, 12А",Объект 648. Прeдлaгaется к продаже уникальная ...,2024-09-09 12:57:55.779682
48872,https://www.avito.ru/3768773854,sevastopol,"3-к. квартира, 62 м², 3/3 эт.",NaN,12800000,"ул. Ленина, 48","Трехкомнатная квартира 62м2, на 3/3 этаже дома...",2024-08-12 11:14:17.523749
71842,https://www.avito.ru/2920859873,sevastopol,"1-к. апартаменты, 26 м², 3/3 эт.",NaN,5200000,"Качинское ш., 33/9",Продаю апартаменты в Севастополе в ЖК Нептун —...,2024-08-20 09:44:31.092411
33481,https://www.avito.ru/4169163069,sevastopol,"1-к. квартира, 29,6 м², 5/5 эт.",NaN,4780000,"пр-т Победы, 56",Представляем вашему вниманию великолепную одно...,2024-09-09 12:47:04.646000
13950,https://sevastopol.cian.ru/sale/flat/299736648/,sevastopol,"2-комн. квартира, 74 м², 3/3 этаж",,19800000,"Севастополь, р-н Гагаринский, мкр. Стрелецкая ...",Отличное предложение для дружной семьи или в к...,2024-08-12 11:06:38.188400
42221,https://www.avito.ru/3510104515,sevastopol,"Квартира-студия, 31,8 м², 2/2 эт.",NaN,2700000,"Редутная ул., 23",Предлагается к продаже просторная светлая студ...,2024-09-03 13:30:33.358345
17509,https://sevastopol.cian.ru/sale/flat/299736293/,sevastopol,"6-комн. квартира, 233 м², 2/3 этаж",,68000000,"Севастополь, р-н Гагаринский, мкр. Стрелецкая ...",Двухуровневая шестикомнатная квартира площадью...,2024-07-08 13:17:33.822433

In [5]:
display( len(df_flat) )
df_flat = df_flat[ df_flat['price'].str.match(r'\d+') ].reset_index(drop=True)
display( len(df_flat) )

86570

86568

In [6]:
from lib.cleaner import CleanerFlat

df_flat = CleanerFlat().transform(df_flat)
display( len(df_flat) )
display(df_flat.sample(9))

86568

,url,place,title,subtitle,price,address,description,ts,nrooms,floor,...,area,is_studio,is_apartment,is_part,is_auction,is_openspace,is_roof,is_SNT,priceM,is_last_floor
64555,https://www.avito.ru/3814442501,sudak,"квартира-студия, 28,9 м², 3/9 эт.",NaN,4618000,Комплекс апартаментов «Бирюзовый квартал»\n ул...,"Ипотека от 11,5% платеж от 26 000р. Кладовка В...",2024-06-17 08:44:23.764814,0,3,...,28.90,True,False,False,False,False,False,False,4.618000,False
72829,https://www.avito.ru/3551338307,sevastopol,"2-к. квартира, 44 м², 4/5 эт.",NaN,8000000,"Пролетарская улица , 23",Квартира в хорошем районе с развитой инфрастру...,2024-06-14 13:06:45.993553,2,4,...,44.00,False,False,False,False,False,False,False,8.000000,False
62769,https://www.avito.ru/4064378179,sevastopol,"3-к. квартира, 59 м², 2/5 эт.",NaN,7550000,"улица Меньшикова, 17",Объект №3032. В Гагаринском районе в Стрелецко...,2024-09-16 13:14:53.953042,3,2,...,59.00,False,False,False,False,False,False,False,7.550000,False
61901,https://www.avito.ru/2745501592,sevastopol,"1-к. апартаменты, 37,5 м², 2/10 эт.",NaN,10900000,"Парковая улица , 7",Продаются элитные апартаменты в лучшем 5-ти зв...,2024-08-06 11:02:57.284493,1,2,...,37.50,False,True,False,False,False,False,False,10.900000,False
53632,https://www.avito.ru/3949272259,sevastopol,"1-к. квартира, 47,2 м², 2/9 эт.",NaN,7835200,"ЖК «Доброгород»\n улица Токарева, 8 этап, блок 3",Крупнейший в городе Севастополь семейный район...,2024-07-22 11:05:31.760224,1,2,...,47.20,False,False,False,False,False,False,False,7.835200,False
58490,https://www.avito.ru/3287902483,sevastopol,"1-к. квартира, 30,8 м², 5/5 эт.",NaN,4850000,"Флагманская улица , 6","Однокомнатная квартира 30,8 м2, на 5/5 этаже д...",2024-06-19 12:22:29.452737,1,5,...,30.80,False,False,False,False,False,False,False,4.850000,True
78124,https://www.avito.ru/3625172418,sevastopol,"1-к. квартира, 47,2 м², 2/10 эт.",NaN,7740800,"ЖК «Доброгород»\n улица Токарева, 8 этап, блок 1","Доступна ипотека! Ипотека с господдержкой, вое...",2024-06-11 10:25:30.856703,1,2,...,47.20,False,False,False,False,False,False,False,7.740800,False
25122,https://krym.cian.ru/sale/flat/306671707/,sudak,"2-комн. квартира, 121,18 м², 7/8 этаж",Сдача корпуса 1 кв. 2027,21440022,"Республика Крым, Судак, Долина Роз ЖК","Продается квартира общей площадью 121,18 м2 в ...",2024-10-07 10:09:37.331706,0,7,...,121.18,False,False,False,False,False,False,False,21.440022,False
30150,https://www.avito.ru/3461829604,sevastopol,"1-к. квартира, 53 м², 2/10 эт.",NaN,7450000,"проспект Победы, 59 к3",Один собственник. Обременений нет. Большая лод...,2024-08-26 14:48:05.820089,1,2,...,53.00,False,False,False,False,False,False,False,7.450000,False

---

In [7]:
obj_type = 'land'
files = [ f'{d}/{f}' for d in source[obj_type] for f in listdir(d) if f[-4:]=='.pkl' ]
display( len(files) )

cols = ['url','place','title','subtitle','price','address','description','ts',]

df_land = pd.concat([
        pd.read_pickle(f).drop_duplicates(['url'])
        for f in files
    ]).reset_index(drop=True)[cols]

display( len(df_land) )
display(df_land.sample(9))

120

71746

,url,place,title,subtitle,price,address,description,ts
41108,https://www.avito.ru/3807772469,sevastopol,Участок 5 сот. (ИЖС),NaN,4900000,садоводческое некоммерческое товарищество Утёс,Участок 5 соток недалеко от моря. Участок 5 со...,2024-09-09 12:53:24.129387
70630,https://www.avito.ru/4034568174,sevastopol,"Участок 5,7 сот. (ИЖС)",NaN,2850000,садоводческое товарищество Первомайское,Продается 5.67 сотки прямоугольной формы. Есть...,2024-06-24 12:54:03.232729
18559,https://sevastopol.cian.ru/sale/suburban/29365...,sevastopol,"Участок, 8.8 сот., Садоводство",,1500000,"Севастополь, р-н Балаклавский, с. Орлиное, ули...",Цена снижена! Пpoдам нeдоpoгo хороший учaстoк ...,2024-06-14 13:00:38.621423
43656,https://www.avito.ru/3980795936,bahchisaray,"Участок 11,8 сот. (ИЖС)",NaN,800000,с. Растущее,"Арт. 67755924. Продам земельный участок, Крым,...",2024-10-07 10:33:33.269655
51306,https://www.avito.ru/1508956179,bahchisaray,Участок 8 сот. (ИЖС),NaN,2600000,"с. Верхоречье, Садовая ул.",Продам участок в живописном уголке Крыма. Свет...,2024-06-13 11:36:28.263004
52517,https://www.avito.ru/4009404203,sevastopol,"Участок 11,2 сот. (СНТ, ДНП)",NaN,4200000,ТСН Верхняя Учкуевка,Продам шикарный горизонтальный Видовой кусок з...,2024-07-22 11:12:26.881258
67527,https://www.avito.ru/3381763892,sevastopol,"Участок 6 сот. (СНТ, ДНП)",NaN,3800000,"Севастополь, Балаклавский муниципальный округ,...","Продается — ровный, без уклона участок. - комм...",2024-06-11 10:32:52.971878
41381,https://www.avito.ru/2957150390,sevastopol,"Участок 8,6 сот. (СНТ, ДНП)",NaN,4650000,садоводческое товарищество Рассвет-3,Продается земельный участок в СТ Тролейбусник-...,2024-07-08 13:36:06.464523
11883,https://krym.cian.ru/sale/suburban/255598751/,sudak,"Участок, 12 сот., Садоводство",,1100000,"Республика Крым, Судак городской округ, с. Мин...",Продам видовой участок у мыса Меганом,2024-08-06 11:21:08.852805

In [8]:
display( len(df_land) )
df_land = df_land[ df_land['price'].str.match(r'\d+') ].reset_index(drop=True)
display( len(df_land) )

71746

71743

In [9]:
from lib.cleaner import CleanerLand

df_land = CleanerLand().transform(df_land)

display( len(df_land) )
display(df_land.sample(9))

71743

,url,place,title,subtitle,price,address,description,ts,area,is_IJS,priceM,priceMU,area_size_category
8728,https://krym.cian.ru/sale/suburban/280748849/,sudak,"участок, 7 сот., ижс",,2100000,"Республика Крым, Судак городской округ, с. Вес...",Продам земельный участок общей площадью 7 сото...,2024-07-30 16:26:34.906552,7.0,True,2.100,0.300000,4-8
21300,https://sevastopol.cian.ru/sale/suburban/26920...,sevastopol,"участок, 11.82 сот., ижс",,3675000,"Севастополь, р-н Балаклавский, с. Новобобровка...","Населенный пункт: с. Ново-Бобровка, ул. Горист...",2024-06-10 11:18:48.884876,82.0,True,3.675,0.044817,20+
37032,https://www.avito.ru/3371326451,sevastopol,"участок 4,4 сот. (ижс)",NaN,4950000,"Босфорская ул., 4","Правая Гераклея! Ижс! Продам хороший, ровный, ...",2024-08-06 11:09:38.953015,4.4,True,4.950,1.125000,4-8
32873,https://www.avito.ru/4019233247,bahchisaray,"участок 13,8 сот. (ижс)",NaN,3500000,"с. Долинное, Молодёжная ул.","Продаются земельный участок по 1382 кв. М., ра...",2024-09-09 13:06:18.507053,13.8,True,3.500,0.253623,12-20
54035,https://www.avito.ru/3864372855,sevastopol,"участок 4,1 сот. (снт, днп)",NaN,3900000,"садоводческое товарищество Теремок, 254",Предлагаем к покупке отличный земельный участо...,2024-07-30 16:22:13.854597,4.1,False,3.900,0.951220,4-8
40453,https://www.avito.ru/1800960551,sevastopol,участок 9 сот. (ижс),NaN,5000000,ул. Маршала Кошевого,"Не срочно, без торга, цена до октября. В прода...",2024-09-09 12:53:24.129387,9.0,True,5.000,0.555556,8-12
44643,https://www.avito.ru/4047677851,sevastopol,участок 16 сот. (ижс),NaN,3500000,"ул. Лётчика Авдеева, 118А","Продам участок Ижс,10 соток, в данный момент р...",2024-06-14 13:13:27.377070,16.0,True,3.500,0.218750,12-20
27525,https://www.avito.ru/4123160843,sevastopol,"участок 3,66 га (снт, днп)",NaN,4100000,"с. Тенистое, ул. Мичурина",Продам земельный участок сельскохозяйственного...,2024-06-19 12:29:14.234421,366.0,False,4.100,0.011202,20+
43343,https://www.avito.ru/2373259861,bahchisaray,"участок 74 сот. (снт, днп)",NaN,1500000,с. Высокое,Продам участок 74сотки под (Лпх). Участок ровн...,2024-10-07 10:33:33.269655,74.0,False,1.500,0.020270,20+

---

In [10]:
obj_type = 'house'
files = [ f'{d}/{f}' for d in source[obj_type] for f in listdir(d) if f[-4:]=='.pkl' ]
display( len(files) )

cols = ['url','place','title','subtitle','price','address','description','ts',]

df_house = pd.concat([
        pd.read_pickle(f).drop_duplicates(['url'])
        for f in files
    ]).reset_index(drop=True)[cols]

display( len(df_house) )
display(df_house.sample(9))

120

63904

,url,place,title,subtitle,price,address,description,ts
56270,https://www.avito.ru/2720420546,sudak,"Дача 150 м² на участке 5,5 сот.",NaN,12950000,"с. Солнечная Долина, Морская ул.","Продам дом-дачу в районе Судака, бухта Бугаз, ...",2024-08-12 11:30:09.325269
35063,https://www.avito.ru/4190528370,sevastopol,Дом 40 м² на участке 5 сот.,NaN,4200000,"ул. Журналиста Хамадана, 35А",Продается дом и земельный участок в Крыму возл...,2024-10-07 10:29:36.863530
11910,https://sevastopol.cian.ru/sale/suburban/30344...,sevastopol,"Дом, 120 м², 4.3 сот., Садоводство",,9500000,"Севастополь, р-н Гагаринский, мкр. Фиолент, Су...","В продаже дом 2 этажа, 120 м2 на участке 4.3 с...",2024-06-19 12:37:23.275933
14927,https://sevastopol.cian.ru/sale/suburban/26427...,sevastopol,"Дом, 270 м², 5.7 сот., ДНП",,29000000,"Севастополь, р-н Гагаринский, Казачья Бухта мкр","Дом 270 м2 на участке 5,7 соток Дом 270 м2 на ...",2024-07-08 14:05:28.543820
28923,https://www.avito.ru/4011033846,sevastopol,Дом 96 м² на участке 4 сот.,NaN,8500000,"садоводческое товарищество Золотая Балка, 224",Собственник! Не Агентство! Никаких Комиссий! В...,2024-08-12 11:27:30.996664
1829,https://sevastopol.cian.ru/sale/suburban/29663...,sevastopol,"Дом, 140 м², 4 сот., ИЖС",,14500000,"Севастополь, р-н Нахимовский, улица Горпищенко","Объект 16118. Продам новый, современный, комфо...",2024-06-17 08:27:31.304082
30307,https://www.avito.ru/3656911558,sevastopol,"Дом 129,7 м² на участке 3,9 сот.",NaN,11500000,"садоводческое товарищество Рассвет-2, 8",Продам дом общей площадью 129.7 м2 на участке ...,2024-08-12 11:27:30.996664
50885,https://www.avito.ru/1797604394,bahchisaray,Дом 100 м² на участке 8 сот.,NaN,8000000,пгт. Куйбышево,Продаётся 2-х этажный дом в Бахчисарайском рай...,2024-09-03 13:49:48.105323
47816,https://www.avito.ru/3322804486,sevastopol,Дом 215 м² на участке 9 сот.,NaN,20000000,"с. Осипенко, Камская ул.",Продаётся двухэтажный экологически чистый дом ...,2024-08-20 09:57:45.024714

In [11]:
display( len(df_house) )
df_house = df_house[ df_house['price'].str.match(r'\d+') ].reset_index(drop=True)
display( len(df_house) )

63904

63902

In [12]:
# cols = ['title','address','place','url']
# df_house[ (df_house['place']=='sevastopol') & (df_house['address'].str.match(r'.*Судак.*')) ][cols]

In [13]:
from lib.cleaner import CleanerHouse

df_house = CleanerHouse().transform(df_house)

display( len(df_house) )
display(df_house.sample(9))

63902

,url,place,title,subtitle,price,address,description,ts,house_area,is_part,is_townhouse,is_SNT,land_area,priceM,land_size_category,house_size_category
14619,https://krym.cian.ru/sale/suburban/304120130/,sudak,"дом, 372 м², 5.6 сот., ижс",,7200000,"Республика Крым, Судак, улица Ароматная, 2",Продаём 3 этажный дом площадью 372 кв. в г. Су...,2024-08-12 11:12:38.365973,372.0,False,False,False,6.0,7.2,4-8,300+
18736,https://sevastopol.cian.ru/sale/suburban/29741...,sevastopol,"дом, 80 м², 5 сот., садоводство",,3400000,"Севастополь, р-н Нахимовский, Качинский муници...","Объект 415. Продается дом 80 м² на участке 2,5...",2024-06-07 11:42:40.789431,80.0,False,False,False,5.0,3.4,4-8,70-110
35255,https://www.avito.ru/3849359644,sevastopol,дом 136 м² на участке 5 сот.,NaN,12500000,"с. Осипенко, Енисейская ул.",Собственник.,2024-10-07 10:29:36.863530,136.0,False,False,False,5.0,12.5,4-8,110-180
57562,https://www.avito.ru/3921537641,sevastopol,дом 85 м² на участке 4 сот.,NaN,9200000,"садоводческое товарищество Дергачи-3, 2",Объект №198. Продам небольшой дом в Балаклавск...,2024-07-22 11:20:00.587621,85.0,False,False,True,4.0,9.2,2-4,70-110
39914,https://www.avito.ru/3137817345,sevastopol,дом 100 м² на участке 4 сот.,NaN,8600000,СТ Милосердие,Продам жилой дом 100 м2 на 4 сот. В доме три к...,2024-10-15 10:47:10.424961,100.0,False,False,True,4.0,8.6,2-4,70-110
5902,https://sevastopol.cian.ru/sale/suburban/30234...,sevastopol,"дом, 198,4 м², 7.56 сот., садоводство",,8500000,"Севастополь, р-н Гагаринский, Слип садоводческ...","Продается дом в Гагаринском районе, территория...",2024-06-13 11:22:19.008525,198.4,False,False,True,56.0,8.5,20+,180-300
25033,https://www.avito.ru/3718480526,sudak,дом 150 м² на участке 10 сот.,NaN,17500000,Восточное ш.,"Электричество 15 квт, газ, вода подключены, ка...",2024-06-24 13:03:38.751089,150.0,False,False,False,10.0,17.5,8-12,110-180
15216,https://sevastopol.cian.ru/sale/suburban/30392...,sevastopol,"дом, 54,7 м², 4.62 сот., ижс",,5000000,"Севастополь, р-н Балаклавский, Гавань садовое ...",Продам участок с домом в черте города. Тихое м...,2024-07-08 14:05:28.543820,54.7,False,False,True,62.0,5.0,20+,50-70
31586,https://www.avito.ru/4174031093,sevastopol,дом 70 м² на участке 4 сот.,NaN,8000000,"пос. Кача, Ударная ул.","Продaм новый сoвременный дом в Кaче, на второй...",2024-09-16 13:25:28.302908,70.0,False,False,False,4.0,8.0,2-4,50-70

## обновляем таблицу адресов

In [14]:
# !pip install geopy

In [15]:
# df_flat['address'].str.strip().drop_duplicates().sort_values().to_csv('tmp/flat_address.txt',index=False,header=False)
# df_land['address'].str.strip().drop_duplicates().sort_values().to_csv('tmp/land_address.txt',index=False,header=False)
# df_house['address'].str.strip().drop_duplicates().sort_values().to_csv('tmp/house_address.txt',index=False,header=False)

In [16]:
from lib.locator import AddressTransformer

atr = AddressTransformer()

places = { 
# поле 'place' и название города
'bahchisaray': 'Бахчисарай,',
      'sudak': 'Судак,',
  'sevastopol': 'Севастополь,',
}

def address_norm(df,atr=atr):
    df['address_orig'] =  df['address']
    df['address'] =  df['address'].apply(atr.transform)
    df['place_'] =  df['place'].map(places)
    df['address'] = df[['address','place_']].apply(lambda d: d[0] if d[1] in d[0] else d[1]+','+d[0],axis=1) 
    df['address'] = (
        df['address']
        .str.replace(', ',',')
        .str.replace(',,',',')
        .str.replace('. ','.')
        .str.replace('\n',' ')
        .str.replace('  ',' ')
        .str.lower()
    )
    return df

In [17]:
df_flat = address_norm(df_flat)
df_land = address_norm(df_land)
df_house = address_norm(df_house)

/tmp/ipykernel_1848498/776805188.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['address'] = df[['address','place_']].apply(lambda d: d[0] if d[1] in d[0] else d[1]+','+d[0],axis=1)
/tmp/ipykernel_1848498/776805188.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['address'] = df[['address','place_']].apply(lambda d: d[0] if d[1] in d[0] else d[1]+','+d[0],axis=1)
/tmp/ipykernel_1848498/776805188.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['address'] = df[['address','place_']].apply(lambda d: d[0] if d[1] in d[0] else d[1]+','+d[0],axis=1)

In [18]:
# df_flat[['address','address_orig']]

In [19]:
address = pd.concat([
        df_flat[['address','address_orig']],
        df_land[['address','address_orig']],
        df_house[['address','address_orig']],
    ]).drop_duplicates(['address']).reset_index(drop=True)

display(len(address))
display(address.sample(5))

14594

,address,address_orig
8735,"севастополь,садоводческое некоммерческое товар...",садоводческое некоммерческое товарищество Скал...
3277,"севастополь,комплекс апартаментов «акватория» ...",Комплекс апартаментов «Акватория»\n улица Пляж...
10125,"севастополь,р-н гагаринский,мкр.фиолент,шоссе ...","Севастополь, р-н Гагаринский, мкр. Фиолент, шо..."
10931,"судак,республика крым,судак городской округ,с....","Республика Крым, Судак городской округ, с. Бог..."
14544,"севастополь,садоводческое товарищество колос,6","Севастополь, садоводческое товарищество Колос, 6"

In [20]:
from os.path import exists as path_exists
loc_file_path = 'data/location.pkl' # таблица адресов

location = pd.DataFrame([],columns=['address','latitude','longitude',])
if path_exists( loc_file_path ):
    location = pd.read_pickle(loc_file_path).drop_duplicates(['address']).reset_index(drop=True)
    
display(len(location))
display(location.sample(5))

20749

                                                 address   latitude  longitude
6413   севастополь,р-н гагаринский,мкр.камышовая бухт...  44.591081  33.444907
13480  севастополь,садоводческое товарищество нахимов...  44.742206  33.552004
6099   севастополь,р-н балаклавский,успех садовое тов...  44.508678  33.501231
7445   севастополь,р-н гагаринский,рыбак-6 садовое то...  44.569386  33.431378
19674  судак,республика крым,алушта городской округ,п...  44.717866  34.462599

---

In [21]:
# def address_norm_(df):
#     df['address_orig'] =  df['address']
#     # df['address'] =  df['address'].apply(atr.transform)
#     df['address'] = (
#         df['address']
#         .str.replace(', ',',')
#         .str.replace(',,',',')
#         .str.replace('. ','.')
#         .str.replace('\n',' ')
#         .str.replace('  ',' ')
#         .str.lower()
#     )
#     return df

In [22]:
# location = address_norm_(location)

In [23]:
# location = location[['address','latitude','longitude']]

---

In [24]:
# собираем все адреса в один список
location = location.merge(
        address[['address']].drop_duplicates(),
        how='outer',
        on='address',
    ).drop_duplicates(['address']).reset_index(drop=True)

display(len(location))
display(location.sample(5))

20923

                                                 address   latitude  longitude
18688                  севастополь,улица куликово поле,3  44.586163  33.519763
1017   жк «жемчужина севастополя» севастополь,гагарин...   44.59438  33.437684
12114          севастополь,с.пироговка,пальметная ул.,28  44.683474  33.728882
20582  судак,с.миндальное,снт солнечная долина,прибре...  44.831167  35.045085
1824   севастополь,балаклава,садоводческое товарищест...   44.50916  33.611742

In [25]:
display(len(location))
display(location['latitude'].isnull().sum())

20923

174

In [26]:
# собираем все адреса с геопозицией
location_def = location[~location['latitude'].isna()].reset_index(drop=True)
display(len(location_def))

# собираем все адреса без геопозиции
location_undef = location[location['latitude'].isna()][['address']].reset_index(drop=True)
display(len(location_undef))

20749

174

In [27]:
display(location_undef)

                                               address
0          бахчисарай,пгт.куйбышево,спортивная ул.,12а
1               бахчисарай,с.баштановка,весёлая ул.,32
2          бахчисарай,с.баштановка,первомайская ул.,1а
3                   бахчисарай,с.новенькое,ул.авдет,41
4            бахчисарай,с.предущельное,ул.гагарина,63а
..                                                 ...
169  судак,с.миндальное,снт солнечная долина,ул.дру...
170             судак,с.солнечная долина,ул.строителей
171            судак,с.солнечная долина,ул.эким-кара,3
172               судак,село дачное,садовая улица ,11а
173                       судак,ул.имени вернадского,4

[174 rows x 1 columns]

In [28]:
from tqdm.auto import tqdm
tqdm.pandas()

In [29]:
# from lib.locator import GeocoderSimpleOSM
from lib.locator import GeocoderYandex
from yandex_keys import keys

atr = AddressTransformer()
locator = GeocoderYandex(keys[0])
# locator = GeocoderSimpleOSM()

if len(location_undef)>0:
    # определяем координаты по строке адреса
    location_undef = location_undef.join( 
            location_undef['address'].progress_apply(locator.transform).apply(pd.Series) 
        ).dropna()     
    display(f'LocationUpdater: {len(location_undef)} new addresses found')
    location = pd.concat([location_def,location_undef]).reset_index(drop=True) 
    assert len(location)>0
    # location.to_pickle(loc_file_path)

  0%|          | 0/174 [00:00<?, ?it/s]

'LocationUpdater: 174 new addresses found'

In [30]:
display( len(location) )
display( location.sample(3) )

20923

                                                 address   latitude  longitude
10536  севастополь,район гагаринский,стрелецкая бухта...  44.594322  33.492886
16333                      севастополь,тсн снт гидрограф  44.544639  33.446039
5644   севастополь,р-н балаклавский,с.орлиное,улица п...  44.445409  33.781488

In [31]:
assert len(location)>0
location.to_pickle(loc_file_path)

## дополняем данные геометкой

In [32]:
display( len(df_flat) )
df_flat  = df_flat.merge(location,on='address').reset_index(drop=True) 
display( len(df_flat) )
display( df_flat.sample(3) )

86568

86568

,url,place,title,subtitle,price,address,description,ts,nrooms,floor,...,is_auction,is_openspace,is_roof,is_SNT,priceM,is_last_floor,address_orig,place_,latitude,longitude
24371,https://sevastopol.cian.ru/sale/flat/299737390/,sevastopol,"1-комн. апартаменты, 75,8 м², 3/3 этаж",,16676000,"севастополь,р-н нахимовский,набережная адмирал...","Однокомнатная квартира 75.8 м2, 3/3 эт. Одноко...",2024-06-18 10:45:27.403294,0,3,...,False,False,False,False,16.6760,True,"Севастополь, р-н Нахимовский, набережная Адмир...","Севастополь,",44.616963,33.51776
78473,https://www.avito.ru/3624972557,sevastopol,"1-к. квартира, 52,2 м², 5/9 эт.",NaN,8560800,"севастополь,жк «доброгород» улица токарева,8 э...","Доступна ипотека! Ипотека с господдержкой, вое...",2024-06-11 10:25:30.856703,1,5,...,False,False,False,False,8.5608,False,"ЖК «Доброгород»\n улица Токарева, 8 этап, блок 4","Севастополь,",44.5807,33.506621
76329,https://www.avito.ru/3625638235,sevastopol,"1-к. квартира, 43,8 м², 6/9 эт.",NaN,7095600,"севастополь,жк «доброгород» улица токарева,8 э...","Доступна ипотека! Ипотека с господдержкой, вое...",2024-06-07 11:27:07.236636,1,6,...,False,False,False,False,7.0956,False,"ЖК «Доброгород»\n улица Токарева, 8 этап, блок 3","Севастополь,",44.5807,33.506621

In [33]:
display( len(df_land) )
df_land  = df_land.merge(location,on='address').reset_index(drop=True) 
display( len(df_land) )
display( df_land.sample(3) )

71743

71743

,url,place,title,subtitle,price,address,description,ts,area,is_IJS,priceM,priceMU,area_size_category,address_orig,place_,latitude,longitude
24345,https://www.avito.ru/3501229892,sevastopol,"участок 7,5 сот. (снт, днп)",NaN,6000000,"севастополь,садоводческое товарищество энтузиа...",Арт. 58655512. К продаже предлагается шикарный...,2024-06-17 08:36:13.464806,7.5,False,6.0,0.800000,4-8,"садоводческое товарищество Энтузиаст, 8","Севастополь,",44.588025,33.472674
1806,https://sevastopol.cian.ru/sale/suburban/29505...,sevastopol,"участок, 9.8 сот., ижс",,4400000,"севастополь,р-н нахимовский,переулок 1-й аквам...",Участок 10 соток ИЖС Участок 10 соток (ИЖС) в ...,2024-06-07 11:37:10.690720,8.0,True,4.4,0.550000,4-8,"Севастополь, р-н Нахимовский, переулок 1-й Акв...","Севастополь,",44.580694,33.531397
45137,https://www.avito.ru/3214991633,sevastopol,"участок 4,2 сот. (ижс)",NaN,4500000,"севастополь,ст медик-7","Прямоугольный ровный участок, на котором распо...",2024-06-14 13:13:27.377070,4.2,True,4.5,1.071429,4-8,СТ Медик-7,"Севастополь,",44.563466,33.490937

In [34]:
display( len(df_house) )
df_house = df_house.merge(location,on='address').reset_index(drop=True) 
display( len(df_house) )
display( df_house.sample(3) )

63902

63902

,url,place,title,subtitle,price,address,description,ts,house_area,is_part,is_townhouse,is_SNT,land_area,priceM,land_size_category,house_size_category,address_orig,place_,latitude,longitude
45547,https://www.avito.ru/4000002636,sevastopol,дом 64 м² на участке 5 сот.,NaN,5000000,"севастополь,фёдоровская ул.","Объект №2965. Продается участок в Любимовке, н...",2024-06-24 13:01:06.410833,64.0,False,False,False,5.0,5.0,4-8,50-70,Фёдоровская ул.,"Севастополь,",44.673738,33.560861
23558,https://www.avito.ru/3947091747,sevastopol,дом 120 м² на участке 8 сот.,NaN,5800000,"севастополь,ялтинское кольцо","Прекрасные соседи. Сахарная головка. Газ, чере...",2024-08-26 15:01:44.774514,120.0,False,False,False,8.0,5.8,4-8,110-180,Ялтинское кольцо,"Севастополь,",44.542487,33.594171
20878,https://sevastopol.cian.ru/sale/suburban/27485...,sevastopol,"дом, 251,2 м², 6 сот., садоводство",,25000000,"севастополь,р-н нахимовский,мираж садовое това...",Объект 209. Отличный гостевой дом площадью 251...,2024-10-07 10:09:21.991663,251.2,False,False,True,6.0,25.0,4-8,180-300,"Севастополь, р-н Нахимовский, Мираж садовое то...","Севастополь,",44.718359,33.552193

In [35]:
# def address_filter(df):
#     #           46.319437, 33.911048
#     #
#     # 45.402617, 32.455625 |  45.545301, 36.684702
#     #
#     #          44.320887, 33.917013

#     df['latitude'] = pd.to_numeric( df['latitude'], errors='coerce' )
#     df['longitude'] = pd.to_numeric( df['longitude'], errors='coerce' )

#     df = df.query('(32.4<longitude<36.7) & (44.3<latitude<46.4)') 

#     df.loc[ df['url']=='https://avito.ru/2322251740', ['latitude','longitude']] = None

#     df.loc[ df['address']=='Севастополь,Чёрное море', ['latitude','longitude'] ] = None
#     df.loc[ df['address'].str.lower().str.match('чёрное море'), ['latitude','longitude'] ] = None 

#     df.loc[ df['address']=='квартал Старый Город', 'place'] = 'turkie'
#     df.loc[ df['address'].str.lower().str.match('анталья'), 'place' ] = 'turkie' 

#     df.loc[ df['address'].str.lower().str.match(r'.*бахчисарай.*'), 'place' ] = 'bahchisaray'
#     df.loc[ df['address'].str.lower().str.match(r'.*севастополь,.*'), 'place' ] = 'sevastopol'

#     df.loc[ df['address'].str.lower().str.match(r'.*мысовское.*'), 'place' ] = 'kerch'
#     df.loc[ df['address'].str.lower().str.match(r'.*алушта.*'), 'place' ] = 'alushta'
#     df.loc[ df['address'].str.lower().str.match(r'.*гурзуф.*'), 'place' ] = 'gurzuf'

#     df.loc[ df['address'].str.lower().str.match(r'.*с.лучистое.*'), 'place' ] = 'alushta'
#     df.loc[ df['address'].str.lower().str.match(r'.*снт солнечная долина.*'), 'place' ] = 'sudak'
#     df.loc[ df['address'].str.lower().str.match(r'.*пгт.новоозёрное.*'), 'place' ] = 'evpatoria'

#     df.loc[ df['address'].str.lower().str.match(r'.*с.мирное.*'), 'place' ] = 'simferopol'
#     df.loc[ df['address'].str.lower().str.match(r'.*тсн аэрофлот.*'), 'place' ] = 'simferopol'

#     df.loc[ df['address'].str.lower().str.match(r'.*семисот.*'), 'place' ] = 'kerch'

#     df.loc[ df['address'].str.lower().str.match(r'.*ялта.*') , 'place' ] = 'yalta'
#     df.loc[ df['address'].str.lower().str.match(r'.*феодосия.*') , 'place' ] = 'feodosia'
#     df.loc[ df['address'].str.lower().str.match(r'.*окуневка.*') , 'place' ] = 'tarkhankut'
#     df.loc[ df['address'].str.lower().str.match(r'.*заветное.*') , 'place' ] = 'kerch'
#     df.loc[ df['address'].str.lower().str.match(r'.*евпатория.*') , 'place' ] = 'evpatoria'
#     df.loc[ df['address'].str.lower().str.match(r'.*симферопольский район.*'), 'place' ] = 'simferopol'

#     df.loc[df['address'].str.match(r'.*белогорск.*'),'place'] = 'belogorsk'
#     df.loc[df['address'].str.match(r'.*кировский.*'),'place'] = 'kirovsky'
#     df.loc[df['address'].str.match(r'.*сакский район.*'),'place'] = 'saki'
#     df.loc[df['address'].str.match(r'.*керчь.*'),'place'] = 'kerch'
#     df.loc[df['address'].str.match(r'.*белогорский.*'),'place'] = 'belogorsk'
#     df.loc[df['address'].str.match(r'.*кировский.*'),'place'] = 'kirovski'

#     df.loc[df['address'].str.match(r'.*кореиз.*'),'place'] = 'ubk'
#     df.loc[df['address'].str.match(r'.*малый маяк.*'),'place'] = 'ubk'
#     df.loc[df['address'].str.match(r'.*светлый мир.*'),'place'] = 'simferopol'
#     df.loc[df['address'].str.match(r'.*доброе.*'),'place'] = 'simferopol'
#     df.loc[df['address'].str.match(r'.*родниково.*'),'place'] = 'simferopol'
#     df.loc[df['address'].str.match(r'.*уютное.*'),'place'] = 'evpatoria'
#     df.loc[df['address'].str.match(r'.*коктебель.*'),'place'] = 'koktebel'
#     df.loc[df['address'].str.match(r'.*новосельское.*'),'place'] = 'tarhankut'

#     df = df.dropna(subset=['latitude','longitude'])
    
#     return df

In [36]:
# display(len(df_flat))
# df_flat = address_filter(df_flat)
# display(len(df_flat))

# display(len(df_land))
# df_land = address_filter(df_land)
# display(len(df_land))

# display(len(df_house))
# df_house = address_filter(df_house)
# display(len(df_house))

In [37]:
assert len(df_flat)>0
df_flat.to_pickle(f'{data_root_folder}/df_flat.pkl')

assert len(df_land)>0
df_land.to_pickle(f'{data_root_folder}/df_land.pkl')

assert len(df_house)>0
df_house.to_pickle(f'{data_root_folder}/df_house.pkl')

In [38]:
!date

Вт 15 окт 2024 10:55:52 MSK